// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dbdriver$0 from "../dbdriver/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * ConnectionProfile is the persisted, non-secret half of a connection. The
 * password lives in the keyring under the same ID.
 * 
 * Use time.Time RFC3339 in JSON; the SQLite columns are stored as INTEGER
 * unix-epoch seconds for trivial portability.
 */
export class ConnectionProfile {
    "id": string;
    "name": string;
    "driver": string;
    "groupId"?: string;
    "host": string;
    "port": number;
    "user": string;
    "database"?: string;
    "params"?: { [_ in string]?: string };
    "ssl"?: dbdriver$0.SSLConfig | null;
    "sshTunnel"?: dbdriver$0.SSHConfig | null;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new ConnectionProfile instance. */
    constructor($$source: Partial<ConnectionProfile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("driver" in $$source)) {
            this["driver"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionProfile {
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType2;
        const $$createField10_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField8_0($$parsedSource["params"]);
        }
        if ("ssl" in $$parsedSource) {
            $$parsedSource["ssl"] = $$createField9_0($$parsedSource["ssl"]);
        }
        if ("sshTunnel" in $$parsedSource) {
            $$parsedSource["sshTunnel"] = $$createField10_0($$parsedSource["sshTunnel"]);
        }
        return new ConnectionProfile($$parsedSource as Partial<ConnectionProfile>);
    }
}

/**
 * Group is a logical folder for connections in the sidebar tree.
 */
export class Group {
    "id": string;
    "name": string;
    "sortOrder": number;
    "createdAt": time$0.Time;

    /** Creates a new Group instance. */
    constructor($$source: Partial<Group> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Group instance from a string or object.
     */
    static createFrom($$source: any = {}): Group {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Group($$parsedSource as Partial<Group>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = dbdriver$0.SSLConfig.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = dbdriver$0.SSHConfig.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
