// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dbdriver$0 from "../dbdriver/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * AgentAuditEntry is one audited statement execution (§5 "审计"). Rows and
 * DurationMS are nil when not applicable (e.g. a rejected statement never
 * ran). Error is "" when Status is not "error".
 */
export class AgentAuditEntry {
    "id": string;
    "sessionId": string;
    "connId": string;
    "sql": string;
    "class": string;
    "approval": string;
    "rows"?: number | null;
    "durationMs"?: number | null;
    "status": string;
    "error"?: string;
    "createdAt": time$0.Time;

    /** Creates a new AgentAuditEntry instance. */
    constructor($$source: Partial<AgentAuditEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("connId" in $$source)) {
            this["connId"] = "";
        }
        if (!("sql" in $$source)) {
            this["sql"] = "";
        }
        if (!("class" in $$source)) {
            this["class"] = "";
        }
        if (!("approval" in $$source)) {
            this["approval"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentAuditEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentAuditEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentAuditEntry($$parsedSource as Partial<AgentAuditEntry>);
    }
}

/**
 * AgentMessage is one turn in a session's message log (role: user | assistant
 * | tool). Content holds the raw JSON blob the agent package already
 * serialized (text/tool-call/tool-result) — storage does not interpret it.
 * TokensIn/TokensOut are nil when unknown (e.g. user messages, or providers
 * without usage reporting).
 */
export class AgentMessage {
    "id": string;
    "sessionId": string;
    "seq": number;
    "role": string;
    "content": string;
    "tokensIn"?: number | null;
    "tokensOut"?: number | null;
    "compacted": boolean;
    "createdAt": time$0.Time;

    /** Creates a new AgentMessage instance. */
    constructor($$source: Partial<AgentMessage> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("seq" in $$source)) {
            this["seq"] = 0;
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("compacted" in $$source)) {
            this["compacted"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentMessage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentMessage($$parsedSource as Partial<AgentMessage>);
    }
}

/**
 * AgentSession is a persisted AI Agent conversation, bound to one connection
 * for its whole lifetime (see AGENT_DESIGN.md §10.2). Grants is the
 * session-level statement-class allowlist (§5 gate 3); it round-trips to the
 * "grants" column as a JSON array.
 */
export class AgentSession {
    "id": string;
    "connId": string;
    "title": string;

    /**
     * ask | agent
     */
    "mode": string;
    "providerId": string;
    "model": string;
    "grants": string[];
    "currentDb"?: string;
    "currentSchema"?: string;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new AgentSession instance. */
    constructor($$source: Partial<AgentSession> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("connId" in $$source)) {
            this["connId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("providerId" in $$source)) {
            this["providerId"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("grants" in $$source)) {
            this["grants"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentSession instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentSession {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("grants" in $$parsedSource) {
            $$parsedSource["grants"] = $$createField6_0($$parsedSource["grants"]);
        }
        return new AgentSession($$parsedSource as Partial<AgentSession>);
    }
}

/**
 * ConnectionProfile is the persisted, non-secret half of a connection. The
 * password lives in the keyring under the same ID.
 * 
 * Use time.Time RFC3339 in JSON; the SQLite columns are stored as INTEGER
 * unix-epoch seconds for trivial portability.
 */
export class ConnectionProfile {
    "id": string;
    "name": string;
    "driver": string;
    "groupId"?: string;

    /**
     * Environment is the deployment-tier label (dev/test/staging/prod, "" =
     * unmarked). Non-secret; it is the data basis for the AI Agent safety
     * model's environment gate — prod connections are hard read-only for the
     * Agent (docs/AGENT_DESIGN.md §5 gate 1).
     */
    "environment": string;
    "host": string;
    "port": number;
    "user": string;
    "database"?: string;
    "params"?: { [_ in string]?: string };
    "ssl"?: dbdriver$0.SSLConfig | null;
    "sshTunnel"?: dbdriver$0.SSHConfig | null;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new ConnectionProfile instance. */
    constructor($$source: Partial<ConnectionProfile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("driver" in $$source)) {
            this["driver"] = "";
        }
        if (!("environment" in $$source)) {
            this["environment"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionProfile {
        const $$createField9_0 = $$createType1;
        const $$createField10_0 = $$createType3;
        const $$createField11_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField9_0($$parsedSource["params"]);
        }
        if ("ssl" in $$parsedSource) {
            $$parsedSource["ssl"] = $$createField10_0($$parsedSource["ssl"]);
        }
        if ("sshTunnel" in $$parsedSource) {
            $$parsedSource["sshTunnel"] = $$createField11_0($$parsedSource["sshTunnel"]);
        }
        return new ConnectionProfile($$parsedSource as Partial<ConnectionProfile>);
    }
}

/**
 * Group is a logical folder for connections in the sidebar tree.
 */
export class Group {
    "id": string;
    "name": string;
    "sortOrder": number;
    "createdAt": time$0.Time;

    /** Creates a new Group instance. */
    constructor($$source: Partial<Group> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Group instance from a string or object.
     */
    static createFrom($$source: any = {}): Group {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Group($$parsedSource as Partial<Group>);
    }
}

/**
 * SavedQuery is a named SQL snippet shown under the object tree's 「查询」
 * group. Scoped by (ConnID, DBName, SchemaName) — SchemaName is "" for
 * drivers without a schema level (MySQL). SQL text holds no secrets so it
 * lives in SQLite alongside the connection profile.
 */
export class SavedQuery {
    "id": string;
    "connId": string;
    "dbName": string;
    "schemaName": string;
    "name": string;
    "sqlText": string;
    "sortOrder": number;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new SavedQuery instance. */
    constructor($$source: Partial<SavedQuery> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("connId" in $$source)) {
            this["connId"] = "";
        }
        if (!("dbName" in $$source)) {
            this["dbName"] = "";
        }
        if (!("schemaName" in $$source)) {
            this["schemaName"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("sqlText" in $$source)) {
            this["sqlText"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): SavedQuery {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedQuery($$parsedSource as Partial<SavedQuery>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = dbdriver$0.SSLConfig.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = dbdriver$0.SSHConfig.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
