package mysqldrv

import "catdb/internal/dbdriver"

// UIDialect is MySQL's declarative UI descriptor. This is the single home of
// MySQL knowledge the front-end needs (type catalog, completion functions,
// snippets, …) — ported out of the former hard-coded lists in
// frontend/src/lib/alterPlan.ts and frontend/src/editor/sqlCompletion.ts.
func (driver) UIDialect() dbdriver.UIDialect {
	return dbdriver.UIDialect{
		EditorDialect:          "mysql",
		IdentQuote:             "`",
		StringBackslashEscapes: true,
		SystemSchemas: []string{"information_schema", "mysql", "performance_schema", "sys"},
		Keywords: []string{
			"AUTO_INCREMENT", "ENGINE", "CHARSET", "COLLATE", "UNSIGNED",
			"SHOW TABLES", "SHOW DATABASES", "SHOW CREATE TABLE", "SHOW COLUMNS FROM",
			"SHOW INDEX FROM", "SHOW PROCESSLIST", "SHOW VARIABLES", "SHOW STATUS",
			"USE", "DESCRIBE", "MODIFY COLUMN", "CHANGE COLUMN",
			"REPLACE INTO", "ON DUPLICATE KEY UPDATE", "STRAIGHT_JOIN",
			"TINYINT", "MEDIUMINT", "LONGTEXT", "MEDIUMTEXT", "TINYTEXT",
			"LONGBLOB", "MEDIUMBLOB", "TINYBLOB", "ENUM", "SET", "YEAR",
		},
		Functions:   mysqlFunctions,
		Snippets:    mysqlSnippets,
		TypeGroups:  mysqlTypeGroups,
		TypeFormats: mysqlTypeFormats,

		DefaultColumnType:   "VARCHAR",
		DefaultColumnParams: "255",
		HasUnsigned:         true,
		AutoIncrement: dbdriver.UIAutoIncrement{
			Supported:   true,
			BaseTypes:   []string{"TINYINT", "SMALLINT", "MEDIUMINT", "INT", "INTEGER", "BIGINT"},
			MaxPerTable: 1,
		},
		PrimaryKeyForcesNotNull: true,
		IndexTypes:              []string{"BTREE", "HASH", "FULLTEXT"},
		DefaultCharset:          "utf8mb4",
	}
}

var mysqlTypeGroups = []dbdriver.UITypeGroup{
	{Key: "string", Types: []string{"VARCHAR", "CHAR", "TEXT", "TINYTEXT", "MEDIUMTEXT", "LONGTEXT"}},
	{Key: "integer", Types: []string{"INT", "BIGINT", "TINYINT", "SMALLINT", "MEDIUMINT"}},
	{Key: "decimal", Types: []string{"DECIMAL", "FLOAT", "DOUBLE"}},
	{Key: "datetime", Types: []string{"DATETIME", "TIMESTAMP", "DATE", "TIME", "YEAR"}},
	{Key: "binary", Types: []string{"BINARY", "VARBINARY", "BLOB", "TINYBLOB", "MEDIUMBLOB", "LONGBLOB"}},
	{Key: "other", Types: []string{"JSON", "BIT", "ENUM", "SET", "GEOMETRY"}},
}

var mysqlTypeFormats = map[string]dbdriver.UITypeFormat{
	"VARCHAR":   {Kind: "length", ParamsRequired: true},
	"VARBINARY": {Kind: "length", ParamsRequired: true},
	"CHAR":      {Kind: "length"},
	"BINARY":    {Kind: "length"},
	"TINYINT":   {Kind: "displayWidth", SupportsUnsigned: true},
	"SMALLINT":  {Kind: "displayWidth", SupportsUnsigned: true},
	"MEDIUMINT": {Kind: "displayWidth", SupportsUnsigned: true},
	"INT":       {Kind: "displayWidth", SupportsUnsigned: true},
	"INTEGER":   {Kind: "displayWidth", SupportsUnsigned: true},
	"BIGINT":    {Kind: "displayWidth", SupportsUnsigned: true},
	"BIT":       {Kind: "displayWidth"},
	"DECIMAL":   {Kind: "precisionScale", SupportsUnsigned: true},
	"NUMERIC":   {Kind: "precisionScale", SupportsUnsigned: true},
	"FLOAT":     {Kind: "precisionScale", SupportsUnsigned: true},
	"DOUBLE":    {Kind: "precisionScale", SupportsUnsigned: true},
	"REAL":      {Kind: "precisionScale", SupportsUnsigned: true},
	"DATETIME":  {Kind: "fractionalSeconds"},
	"TIMESTAMP": {Kind: "fractionalSeconds"},
	"TIME":      {Kind: "fractionalSeconds"},
	"ENUM":      {Kind: "enumValues", ParamsRequired: true},
	"SET":       {Kind: "enumValues", ParamsRequired: true},
}

var mysqlSnippets = []dbdriver.UISnippet{
	{
		Label:  "createtable",
		Detail: "CREATE TABLE …",
		Body: "CREATE TABLE ${name} (\n  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,\n" +
			"  ${cols}\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4${}",
	},
}

var mysqlFunctions = []dbdriver.UIFunction{
	{Name: "COUNT", Category: "aggregate", Info: "COUNT(expr) — number of non-NULL rows", Params: []string{"expr"}},
	{Name: "SUM", Category: "aggregate", Info: "SUM(expr) — sum of expr", Params: []string{"expr"}},
	{Name: "AVG", Category: "aggregate", Info: "AVG(expr) — average of expr", Params: []string{"expr"}},
	{Name: "MIN", Category: "aggregate", Info: "MIN(expr)", Params: []string{"expr"}},
	{Name: "MAX", Category: "aggregate", Info: "MAX(expr)", Params: []string{"expr"}},
	{Name: "GROUP_CONCAT", Category: "aggregate", Info: "GROUP_CONCAT([DISTINCT] expr [ORDER BY …] [SEPARATOR str])", Params: []string{"expr", "separator"}},
	{Name: "CONCAT", Category: "string", Info: "CONCAT(str1, str2, …) — concatenate strings", Params: []string{"str", "…"}},
	{Name: "CONCAT_WS", Category: "string", Info: "CONCAT_WS(sep, str1, str2, …)", Params: []string{"separator", "str", "…"}},
	{Name: "SUBSTRING", Category: "string", Info: "SUBSTRING(str, pos[, len])", Params: []string{"str", "pos", "len"}},
	{Name: "LENGTH", Category: "string", Info: "LENGTH(str) — byte length"},
	{Name: "CHAR_LENGTH", Category: "string", Info: "CHAR_LENGTH(str) — character length"},
	{Name: "TRIM", Category: "string"},
	{Name: "LTRIM", Category: "string"},
	{Name: "RTRIM", Category: "string"},
	{Name: "LOWER", Category: "string"},
	{Name: "UPPER", Category: "string"},
	{Name: "REPLACE", Category: "string", Info: "REPLACE(str, from, to)", Params: []string{"str", "from", "to"}},
	{Name: "LEFT", Category: "string", Info: "LEFT(str, len)", Params: []string{"str", "len"}},
	{Name: "RIGHT", Category: "string", Info: "RIGHT(str, len)", Params: []string{"str", "len"}},
	{Name: "LOCATE", Category: "string", Info: "LOCATE(substr, str[, pos])", Params: []string{"substr", "str", "pos"}},
	{Name: "INSTR", Category: "string", Info: "INSTR(str, substr)", Params: []string{"str", "substr"}},
	{Name: "LPAD", Category: "string", Params: []string{"str", "len", "pad"}},
	{Name: "RPAD", Category: "string", Params: []string{"str", "len", "pad"}},
	{Name: "FORMAT", Category: "string", Info: "FORMAT(num, decimals)", Params: []string{"num", "decimals"}},
	{Name: "ROUND", Category: "numeric", Info: "ROUND(x[, d])", Params: []string{"x", "decimals"}},
	{Name: "FLOOR", Category: "numeric"},
	{Name: "CEIL", Category: "numeric"},
	{Name: "ABS", Category: "numeric"},
	{Name: "MOD", Category: "numeric", Params: []string{"n", "m"}},
	{Name: "POWER", Category: "numeric", Params: []string{"base", "exp"}},
	{Name: "RAND", Category: "numeric", NoArgs: true},
	{Name: "GREATEST", Category: "numeric"},
	{Name: "LEAST", Category: "numeric"},
	{Name: "NOW", Category: "datetime", Info: "NOW() — current DATETIME", NoArgs: true},
	{Name: "CURDATE", Category: "datetime", NoArgs: true},
	{Name: "CURTIME", Category: "datetime", NoArgs: true},
	{Name: "CURRENT_TIMESTAMP", Category: "datetime", NoArgs: true},
	{Name: "UNIX_TIMESTAMP", Category: "datetime", Info: "UNIX_TIMESTAMP([date])", NoArgs: true},
	{Name: "FROM_UNIXTIME", Category: "datetime", Info: "FROM_UNIXTIME(ts[, format])", Params: []string{"ts", "format"}},
	{Name: "DATE", Category: "datetime"},
	{Name: "DATE_FORMAT", Category: "datetime", Info: "DATE_FORMAT(date, format)", Params: []string{"date", "format"}},
	{Name: "STR_TO_DATE", Category: "datetime", Info: "STR_TO_DATE(str, format)", Params: []string{"str", "format"}},
	{Name: "DATE_ADD", Category: "datetime", Info: "DATE_ADD(date, INTERVAL n unit)", Params: []string{"date", "INTERVAL n unit"}},
	{Name: "DATE_SUB", Category: "datetime", Info: "DATE_SUB(date, INTERVAL n unit)", Params: []string{"date", "INTERVAL n unit"}},
	{Name: "DATEDIFF", Category: "datetime", Info: "DATEDIFF(date1, date2) — days between", Params: []string{"date1", "date2"}},
	{Name: "TIMESTAMPDIFF", Category: "datetime", Info: "TIMESTAMPDIFF(unit, dt1, dt2)", Params: []string{"unit", "dt1", "dt2"}},
	{Name: "YEAR", Category: "datetime"},
	{Name: "MONTH", Category: "datetime"},
	{Name: "DAY", Category: "datetime"},
	{Name: "HOUR", Category: "datetime"},
	{Name: "MINUTE", Category: "datetime"},
	{Name: "SECOND", Category: "datetime"},
	{Name: "IFNULL", Category: "control", Info: "IFNULL(expr, alt)", Params: []string{"expr", "alt"}},
	{Name: "NULLIF", Category: "control", Info: "NULLIF(a, b) — NULL if a=b", Params: []string{"a", "b"}},
	{Name: "COALESCE", Category: "control", Info: "COALESCE(a, b, …) — first non-NULL", Params: []string{"a", "b", "…"}},
	{Name: "IF", Category: "control", Info: "IF(cond, a, b)", Params: []string{"cond", "then", "else"}},
	{Name: "JSON_EXTRACT", Category: "json"},
	{Name: "JSON_UNQUOTE", Category: "json"},
	{Name: "JSON_OBJECT", Category: "json"},
	{Name: "JSON_ARRAY", Category: "json"},
	{Name: "CAST", Category: "cast", Info: "CAST(expr AS type)", Params: []string{"expr AS type"}},
	{Name: "CONVERT", Category: "cast", Info: "CONVERT(expr, type)", Params: []string{"expr", "type"}},
	{Name: "VERSION", Category: "system", NoArgs: true},
	{Name: "DATABASE", Category: "system", NoArgs: true},
	{Name: "USER", Category: "system", NoArgs: true},
	{Name: "LAST_INSERT_ID", Category: "system", NoArgs: true},
	{Name: "UUID", Category: "system", NoArgs: true},
}
