// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dbdriver$0 from "../../dbdriver/models.js";

/**
 * Column is one desired column. OrigName links it back to the current table:
 * "" means newly added; a non-empty OrigName different from Name means rename.
 */
export class Column {
    "origName"?: string;
    "name": string;
    "nativeType": string;
    "nullable": boolean;

    /**
     * nil = no DEFAULT clause
     */
    "default"?: string | null;
    "isPrimaryKey"?: boolean;
    "isAutoIncrement"?: boolean;
    "comment"?: string;

    /** Creates a new Column instance. */
    constructor($$source: Partial<Column> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("nativeType" in $$source)) {
            this["nativeType"] = "";
        }
        if (!("nullable" in $$source)) {
            this["nullable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Column instance from a string or object.
     */
    static createFrom($$source: any = {}): Column {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Column($$parsedSource as Partial<Column>);
    }
}

/**
 * ForeignKey is one desired FK constraint.
 */
export class ForeignKey {
    "origName"?: string;
    "name": string;
    "columns": string[];
    "referencedSchema"?: string;
    "referencedTable": string;
    "referencedColumns": string[];
    "onUpdate"?: string;
    "onDelete"?: string;

    /** Creates a new ForeignKey instance. */
    constructor($$source: Partial<ForeignKey> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("referencedTable" in $$source)) {
            this["referencedTable"] = "";
        }
        if (!("referencedColumns" in $$source)) {
            this["referencedColumns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForeignKey instance from a string or object.
     */
    static createFrom($$source: any = {}): ForeignKey {
        const $$createField2_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField2_0($$parsedSource["columns"]);
        }
        if ("referencedColumns" in $$parsedSource) {
            $$parsedSource["referencedColumns"] = $$createField5_0($$parsedSource["referencedColumns"]);
        }
        return new ForeignKey($$parsedSource as Partial<ForeignKey>);
    }
}

/**
 * Index is one desired secondary index (or the PRIMARY entry, which the diff
 * ignores — the PK pipeline owns it).
 */
export class Index {
    "origName"?: string;
    "name": string;
    "columns": dbdriver$0.IndexColumn[];
    "unique"?: boolean;
    "primary"?: boolean;
    "type"?: string;
    "comment"?: string;

    /** Creates a new Index instance. */
    constructor($$source: Partial<Index> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Index instance from a string or object.
     */
    static createFrom($$source: any = {}): Index {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField2_0($$parsedSource["columns"]);
        }
        return new Index($$parsedSource as Partial<Index>);
    }
}

/**
 * Table is the desired shape handed to Diff.
 */
export class Table {
    "columns": Column[];
    "indexes": Index[];
    "foreignKeys": ForeignKey[];
    "comment": string;

    /** Creates a new Table instance. */
    constructor($$source: Partial<Table> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("indexes" in $$source)) {
            this["indexes"] = [];
        }
        if (!("foreignKeys" in $$source)) {
            this["foreignKeys"] = [];
        }
        if (!("comment" in $$source)) {
            this["comment"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Table instance from a string or object.
     */
    static createFrom($$source: any = {}): Table {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType6;
        const $$createField2_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("indexes" in $$parsedSource) {
            $$parsedSource["indexes"] = $$createField1_0($$parsedSource["indexes"]);
        }
        if ("foreignKeys" in $$parsedSource) {
            $$parsedSource["foreignKeys"] = $$createField2_0($$parsedSource["foreignKeys"]);
        }
        return new Table($$parsedSource as Partial<Table>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = dbdriver$0.IndexColumn.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = Column.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = Index.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = ForeignKey.createFrom;
const $$createType8 = $Create.Array($$createType7);
