//go:build integration

// Integration test: spins a real PostgreSQL via testcontainers and runs the
// shared dbdriver contract suite against postgresdrv.
//
// Run locally:
//
//	go test -tags=integration ./plugins/postgresdrv/...
//
// Requires Docker (testcontainers connects to the local daemon).
package postgresdrv

import (
	"context"
	"fmt"
	"testing"
	"time"

	tcpostgres "github.com/testcontainers/testcontainers-go/modules/postgres"

	"catdb/internal/dbdriver"
	"catdb/internal/dbdriver/contract"
)

func TestPostgresContract(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()

	container, err := tcpostgres.Run(ctx, "postgres:16-alpine",
		tcpostgres.WithDatabase("test"),
		tcpostgres.WithUsername("postgres"),
		tcpostgres.WithPassword("secret"),
		tcpostgres.BasicWaitStrategies(),
	)
	if err != nil {
		t.Fatalf("start postgres container: %v", err)
	}
	t.Cleanup(func() { _ = container.Terminate(context.Background()) })

	host, err := container.Host(ctx)
	if err != nil {
		t.Fatalf("host: %v", err)
	}
	port, err := container.MappedPort(ctx, "5432/tcp")
	if err != nil {
		t.Fatalf("port: %v", err)
	}

	cfg := dbdriver.ConnConfig{
		Host:     host,
		Port:     int(port.Num()),
		User:     "postgres",
		Password: "secret",
		Database: "test",
	}

	contract.Run(t, ctx, driver{}, cfg, contract.Fixtures{
		SleepSQL: "SELECT pg_sleep(2)",
		CreateTableSQL: func(qualified string) string {
			return fmt.Sprintf(`CREATE TABLE %s (
				id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				name VARCHAR(64) NOT NULL,
				created_at TIMESTAMP NULL
			)`, qualified)
		},
	})
}
