package postgresdrv

import (
	"fmt"
	"strings"

	"catdb/internal/dbdriver"
)

// DDL generation for PostgreSQL — CREATE TABLE from a TableSchema and ALTER
// statements from a schemadiff ChangeSet. Differences from the MySQL
// renderer that shape this file:
//   - comments are separate COMMENT ON statements, never inline;
//   - indexes are schema-level objects (CREATE INDEX, not a table clause);
//   - column changes are granular ALTER COLUMN sub-commands (TYPE / NOT NULL
//     / DEFAULT), there is no MODIFY COLUMN that rewrites the definition;
//   - columns cannot be repositioned — ColumnPosition is ignored;
//   - dropping the PK requires the constraint name, which the ChangeSet does
//     not carry, so it is resolved server-side in a DO block.

// quoteString renders a Postgres string literal: single quotes doubled.
// (standard_conforming_strings is on by default — backslash is literal.)
func quoteString(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// defaultKeywords pass through unquoted when found as a DEFAULT value.
var defaultKeywords = map[string]bool{
	"NULL": true, "CURRENT_TIMESTAMP": true, "CURRENT_DATE": true,
	"CURRENT_TIME": true, "NOW()": true, "TRUE": true, "FALSE": true,
	"CURRENT_USER": true, "LOCALTIMESTAMP": true,
}

// formatDefaultExpr renders the right-hand side of `DEFAULT …`. Values read
// back from pg_attrdef arrive as expressions ("'x'::character varying",
// "nextval('…')", "now()") and pass through verbatim; bare user input is
// quoted unless it is a keyword or numeric literal.
func formatDefaultExpr(raw string) string {
	trimmed := strings.TrimSpace(raw)
	if trimmed == "" {
		return "''"
	}
	// Keywords pass through as written — Postgres renders its own defaults
	// lowercase ("now()"), so don't fight the catalog's casing.
	if defaultKeywords[strings.ToUpper(trimmed)] {
		return trimmed
	}
	// Expressions: casts, function calls, parenthesized — keep verbatim.
	if strings.Contains(trimmed, "::") ||
		(strings.Contains(trimmed, "(") && strings.HasSuffix(trimmed, ")")) {
		return trimmed
	}
	if isNumericLiteral(trimmed) {
		return trimmed
	}
	return quoteString(trimmed)
}

// isNumericLiteral matches integers, decimals and scientific notation
// (incl. negative) — same acceptance as the MySQL renderer.
func isNumericLiteral(s string) bool {
	i := 0
	if i < len(s) && s[i] == '-' {
		i++
	}
	digits := func() bool {
		start := i
		for i < len(s) && s[i] >= '0' && s[i] <= '9' {
			i++
		}
		return i > start
	}
	if !digits() {
		return false
	}
	if i < len(s) && s[i] == '.' {
		i++
		if !digits() {
			return false
		}
	}
	if i < len(s) && (s[i] == 'e' || s[i] == 'E') {
		i++
		if i < len(s) && s[i] == '-' {
			i++
		}
		if !digits() {
			return false
		}
	}
	return i == len(s)
}

// isSerialType reports whether the written type is already auto-incrementing
// by itself, so no IDENTITY clause may be added.
func isSerialType(nativeType string) bool {
	switch strings.ToUpper(strings.TrimSpace(nativeType)) {
	case "SERIAL", "SERIAL2", "SERIAL4", "SERIAL8", "SMALLSERIAL", "BIGSERIAL":
		return true
	}
	return false
}

// columnDefBody renders everything after the column name. Comments are NOT
// part of the definition in Postgres — callers emit COMMENT ON separately.
func columnDefBody(c dbdriver.ColumnMeta) string {
	parts := []string{c.NativeType}
	if c.IsAutoIncrement && !isSerialType(c.NativeType) {
		parts = append(parts, "GENERATED BY DEFAULT AS IDENTITY")
	}
	if c.Nullable {
		parts = append(parts, "NULL")
	} else {
		parts = append(parts, "NOT NULL")
	}
	// Identity/serial columns own their sequence default.
	if c.Default != nil && !c.IsAutoIncrement {
		parts = append(parts, "DEFAULT "+formatDefaultExpr(*c.Default))
	}
	return strings.Join(parts, " ")
}

func (d dialect) fullColumnDef(c dbdriver.ColumnMeta) string {
	return d.QuoteIdentifier(c.Name) + " " + columnDefBody(c)
}

// indexColumnList renders the parenthesized key list. ASC is the default and
// omitted; DESC only applies to ordered (btree) methods.
func (d dialect) indexColumnList(ix dbdriver.IndexInfo) string {
	cols := make([]string, len(ix.Columns))
	for i, c := range ix.Columns {
		spec := d.QuoteIdentifier(c.Name)
		if strings.EqualFold(c.Order, "DESC") {
			spec += " DESC"
		}
		cols[i] = spec
	}
	return "(" + strings.Join(cols, ", ") + ")"
}

// createIndexSQL renders "CREATE [UNIQUE] INDEX name ON table [USING m] (…)".
// schema qualifies the table; the index inherits the table's schema.
func (d dialect) createIndexSQL(schema, table string, ix dbdriver.IndexInfo) string {
	kw := "CREATE INDEX"
	if ix.Unique {
		kw = "CREATE UNIQUE INDEX"
	}
	using := ""
	if t := strings.ToLower(strings.TrimSpace(ix.Type)); t != "" && t != "btree" {
		using = " USING " + t
	}
	return fmt.Sprintf("%s %s ON %s%s %s;", kw, d.QuoteIdentifier(ix.Name),
		dbdriver.QualifyTable(d, "", schema, table), using, d.indexColumnList(ix))
}

// fkSpec renders "CONSTRAINT name FOREIGN KEY (…) REFERENCES … (…)[ ON UPDATE …][ ON DELETE …]".
// NO ACTION is Postgres's default and is omitted (metadata maps it to "").
func (d dialect) fkSpec(fk dbdriver.ForeignKeyInfo) string {
	quoteAll := func(names []string) string {
		out := make([]string, len(names))
		for i, n := range names {
			out[i] = d.QuoteIdentifier(n)
		}
		return strings.Join(out, ", ")
	}
	refTable := dbdriver.QualifyTable(d, "", fk.ReferencedSchema, fk.ReferencedTable)
	s := fmt.Sprintf("CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s)",
		d.QuoteIdentifier(fk.Name), quoteAll(fk.Columns), refTable, quoteAll(fk.ReferencedColumns))
	if u := strings.ToUpper(fk.OnUpdate); u != "" && u != "NO ACTION" {
		s += " ON UPDATE " + u
	}
	if u := strings.ToUpper(fk.OnDelete); u != "" && u != "NO ACTION" {
		s += " ON DELETE " + u
	}
	return s
}

// GenerateCreateTable emits the CREATE TABLE statement followed by CREATE
// INDEX / COMMENT ON statements as needed, newline-joined. The pool runs in
// simple-protocol mode, so the multi-statement string executes in one Exec.
func (d dialect) GenerateCreateTable(t dbdriver.TableSchema) (string, error) {
	name := strings.TrimSpace(t.Name)
	if name == "" {
		return "", fmt.Errorf("postgresdrv: GenerateCreateTable: table name is empty")
	}
	if len(t.Columns) == 0 {
		return "", fmt.Errorf("postgresdrv: GenerateCreateTable: table %q has no columns", name)
	}

	fq := dbdriver.QualifyTable(d, "", t.Schema, name)
	var lines []string
	for _, c := range t.Columns {
		lines = append(lines, "  "+d.fullColumnDef(c))
	}

	// PK: explicit list wins; otherwise collect per-column flags in order.
	pk := t.PrimaryKey
	if len(pk) == 0 {
		for _, c := range t.Columns {
			if c.IsPrimaryKey {
				pk = append(pk, c.Name)
			}
		}
	}
	if len(pk) > 0 {
		quoted := make([]string, len(pk))
		for i, n := range pk {
			quoted[i] = d.QuoteIdentifier(n)
		}
		lines = append(lines, fmt.Sprintf("  PRIMARY KEY (%s)", strings.Join(quoted, ", ")))
	}

	for _, fk := range t.ForeignKeys {
		if strings.TrimSpace(fk.Name) == "" || len(fk.Columns) == 0 ||
			strings.TrimSpace(fk.ReferencedTable) == "" || len(fk.ReferencedColumns) == 0 {
			continue
		}
		lines = append(lines, "  "+d.fkSpec(fk))
	}

	stmts := []string{fmt.Sprintf("CREATE TABLE %s (\n%s\n);", fq, strings.Join(lines, ",\n"))}

	for _, ix := range t.Indexes {
		if ix.Primary || strings.TrimSpace(ix.Name) == "" || len(ix.Columns) == 0 {
			continue
		}
		stmts = append(stmts, d.createIndexSQL(t.Schema, name, ix))
		if ix.Comment != "" {
			stmts = append(stmts, d.commentOnIndex(t.Schema, ix.Name, ix.Comment))
		}
	}
	if t.Comment != "" {
		stmts = append(stmts, fmt.Sprintf("COMMENT ON TABLE %s IS %s;", fq, quoteString(t.Comment)))
	}
	for _, c := range t.Columns {
		if c.Comment != "" {
			stmts = append(stmts, d.commentOnColumn(fq, c.Name, c.Comment))
		}
	}
	return strings.Join(stmts, "\n"), nil
}

func (d dialect) commentOnColumn(fqTable, column, comment string) string {
	val := "NULL"
	if comment != "" {
		val = quoteString(comment)
	}
	return fmt.Sprintf("COMMENT ON COLUMN %s.%s IS %s;", fqTable, d.QuoteIdentifier(column), val)
}

func (d dialect) commentOnIndex(schema, index, comment string) string {
	val := "NULL"
	if comment != "" {
		val = quoteString(comment)
	}
	return fmt.Sprintf("COMMENT ON INDEX %s IS %s;", dbdriver.QualifyTable(d, "", schema, index), val)
}

// dropPrimaryKeySQL resolves the PK constraint name server-side — the
// ChangeSet doesn't carry it — and drops it if present.
func (d dialect) dropPrimaryKeySQL(fq string) string {
	target := quoteString(fq) // '"schema"."table"'::regclass
	return fmt.Sprintf(`DO $$
DECLARE pk name;
BEGIN
  SELECT conname INTO pk FROM pg_constraint WHERE conrelid = %s::regclass AND contype = 'p';
  IF pk IS NOT NULL THEN
    EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %%I', pk);
  END IF;
END $$;`, target, strings.ReplaceAll(fq, "'", "''"))
}

// alterColumnStatements renders the granular sub-commands that reconcile one
// column to the desired definition. The ChangeSet doesn't say which aspect
// changed, so type / nullability / default / comment are all (re)applied —
// each is idempotent. Identity changes are not reconciled here (rare, and
// not expressible without knowing the current state).
func (d dialect) alterColumnStatements(fq string, c dbdriver.ColumnMeta) []string {
	col := d.QuoteIdentifier(c.Name)
	out := []string{
		fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s TYPE %s USING %s::%s;", fq, col, c.NativeType, col, c.NativeType),
	}
	if c.Nullable {
		out = append(out, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s DROP NOT NULL;", fq, col))
	} else {
		out = append(out, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s SET NOT NULL;", fq, col))
	}
	if c.Default != nil && !c.IsAutoIncrement {
		out = append(out, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s SET DEFAULT %s;", fq, col, formatDefaultExpr(*c.Default)))
	} else if !c.IsAutoIncrement {
		out = append(out, fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s DROP DEFAULT;", fq, col))
	}
	out = append(out, d.commentOnColumn(fq, c.Name, c.Comment))
	return out
}

// GenerateAlterTable renders a ChangeSet into DDL statements in safe
// execution order: columns → primary key → indexes → foreign keys → options.
// Column positions (FIRST/AFTER) are ignored — Postgres cannot reorder.
func (d dialect) GenerateAlterTable(db, schema, table string, cs dbdriver.ChangeSet) ([]string, error) {
	if strings.TrimSpace(table) == "" {
		return nil, fmt.Errorf("postgresdrv: GenerateAlterTable: table name is empty")
	}
	ns := resolveSchema(db, schema)
	fq := dbdriver.QualifyTable(d, "", ns, table)
	var stmts []string

	for _, ch := range cs.Columns {
		switch ch.Kind {
		case dbdriver.ColumnDrop:
			stmts = append(stmts, fmt.Sprintf("ALTER TABLE %s DROP COLUMN %s;", fq, d.QuoteIdentifier(ch.Name)))
		case dbdriver.ColumnAdd:
			if ch.Column == nil {
				return nil, fmt.Errorf("postgresdrv: add column change without definition")
			}
			stmts = append(stmts, fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s;", fq, d.fullColumnDef(*ch.Column)))
			if ch.Column.Comment != "" {
				stmts = append(stmts, d.commentOnColumn(fq, ch.Column.Name, ch.Column.Comment))
			}
		case dbdriver.ColumnModify:
			if ch.Column == nil {
				return nil, fmt.Errorf("postgresdrv: modify column change without definition")
			}
			stmts = append(stmts, d.alterColumnStatements(fq, *ch.Column)...)
		case dbdriver.ColumnRename:
			if ch.Column == nil {
				return nil, fmt.Errorf("postgresdrv: rename column change without definition")
			}
			stmts = append(stmts, fmt.Sprintf("ALTER TABLE %s RENAME COLUMN %s TO %s;",
				fq, d.QuoteIdentifier(ch.Name), d.QuoteIdentifier(ch.Column.Name)))
			stmts = append(stmts, d.alterColumnStatements(fq, *ch.Column)...)
		default:
			return nil, fmt.Errorf("postgresdrv: unknown column change kind %q", ch.Kind)
		}
	}

	if pk := cs.PrimaryKey; pk != nil {
		if pk.Drop {
			stmts = append(stmts, d.dropPrimaryKeySQL(fq))
		}
		if len(pk.Columns) > 0 {
			quoted := make([]string, len(pk.Columns))
			for i, n := range pk.Columns {
				quoted[i] = d.QuoteIdentifier(n)
			}
			stmts = append(stmts, fmt.Sprintf("ALTER TABLE %s ADD PRIMARY KEY (%s);", fq, strings.Join(quoted, ", ")))
		}
	}

	for _, ch := range cs.Indexes {
		switch ch.Kind {
		case "drop":
			stmts = append(stmts, fmt.Sprintf("DROP INDEX %s;", dbdriver.QualifyTable(d, "", ns, ch.Name)))
		case "add":
			if ch.Index == nil {
				return nil, fmt.Errorf("postgresdrv: add index change without definition")
			}
			stmts = append(stmts, d.createIndexSQL(ns, table, *ch.Index))
			if ch.Index.Comment != "" {
				stmts = append(stmts, d.commentOnIndex(ns, ch.Index.Name, ch.Index.Comment))
			}
		default:
			return nil, fmt.Errorf("postgresdrv: unknown index change kind %q", ch.Kind)
		}
	}

	for _, ch := range cs.ForeignKeys {
		switch ch.Kind {
		case "drop":
			stmts = append(stmts, fmt.Sprintf("ALTER TABLE %s DROP CONSTRAINT %s;", fq, d.QuoteIdentifier(ch.Name)))
		case "add":
			if ch.ForeignKey == nil {
				return nil, fmt.Errorf("postgresdrv: add foreign-key change without definition")
			}
			stmts = append(stmts, fmt.Sprintf("ALTER TABLE %s ADD %s;", fq, d.fkSpec(*ch.ForeignKey)))
		default:
			return nil, fmt.Errorf("postgresdrv: unknown foreign-key change kind %q", ch.Kind)
		}
	}

	for _, opt := range cs.Options {
		switch opt.Name {
		case "comment":
			val := "NULL"
			if opt.Value != "" {
				val = quoteString(opt.Value)
			}
			stmts = append(stmts, fmt.Sprintf("COMMENT ON TABLE %s IS %s;", fq, val))
		default:
			return nil, fmt.Errorf("postgresdrv: unknown table option %q", opt.Name)
		}
	}
	return stmts, nil
}
