package postgresdrv

import (
	"strings"
	"testing"

	"catdb/internal/dbdriver"
)

func strPtr(s string) *string { return &s }

func TestGenerateCreateTable(t *testing.T) {
	d := dialect{}
	got, err := d.GenerateCreateTable(dbdriver.TableSchema{
		Name:   "users",
		Schema: "public",
		Columns: []dbdriver.ColumnMeta{
			{Name: "id", NativeType: "BIGINT", IsPrimaryKey: true, IsAutoIncrement: true},
			{Name: "name", NativeType: "VARCHAR(64)", Nullable: false},
			{Name: "note", NativeType: "TEXT", Nullable: true, Comment: "free text"},
			{Name: "created_at", NativeType: "TIMESTAMPTZ", Nullable: false, Default: strPtr("now()")},
		},
		Indexes: []dbdriver.IndexInfo{
			{Name: "users_pkey", Primary: true, Columns: []dbdriver.IndexColumn{{Name: "id"}}},
			{Name: "ix_name", Unique: true, Type: "BTREE", Columns: []dbdriver.IndexColumn{{Name: "name", Order: "DESC"}}},
			{Name: "ix_note", Type: "GIN", Columns: []dbdriver.IndexColumn{{Name: "note"}}},
		},
		ForeignKeys: []dbdriver.ForeignKeyInfo{
			{Name: "fk_org", Columns: []string{"org_id"}, ReferencedSchema: "public",
				ReferencedTable: "orgs", ReferencedColumns: []string{"id"}, OnDelete: "CASCADE"},
		},
		Comment: "app users",
	})
	if err != nil {
		t.Fatalf("GenerateCreateTable: %v", err)
	}
	wantFragments := []string{
		`CREATE TABLE "public"."users" (`,
		`"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL`,
		`"name" VARCHAR(64) NOT NULL`,
		`"note" TEXT NULL`,
		`"created_at" TIMESTAMPTZ NOT NULL DEFAULT now()`,
		`PRIMARY KEY ("id")`,
		`CONSTRAINT "fk_org" FOREIGN KEY ("org_id") REFERENCES "public"."orgs" ("id") ON DELETE CASCADE`,
		`CREATE UNIQUE INDEX "ix_name" ON "public"."users" ("name" DESC);`,
		`CREATE INDEX "ix_note" ON "public"."users" USING gin ("note");`,
		`COMMENT ON TABLE "public"."users" IS 'app users';`,
		`COMMENT ON COLUMN "public"."users"."note" IS 'free text';`,
	}
	for _, w := range wantFragments {
		if !strings.Contains(got, w) {
			t.Errorf("missing fragment %q in:\n%s", w, got)
		}
	}
	// The primary index must not become a duplicate CREATE INDEX.
	if strings.Contains(got, "users_pkey") {
		t.Errorf("primary index leaked into CREATE INDEX:\n%s", got)
	}
	// No inline COMMENT clause — Postgres has none.
	if strings.Contains(got, "NULL COMMENT") || strings.Contains(got, `TEXT NULL 'free text'`) {
		t.Errorf("inline comment leaked into column def:\n%s", got)
	}
}

func TestGenerateCreateTableSerialPassthrough(t *testing.T) {
	d := dialect{}
	got, err := d.GenerateCreateTable(dbdriver.TableSchema{
		Name: "t",
		Columns: []dbdriver.ColumnMeta{
			{Name: "id", NativeType: "SERIAL", IsPrimaryKey: true, IsAutoIncrement: true},
		},
	})
	if err != nil {
		t.Fatalf("GenerateCreateTable: %v", err)
	}
	if strings.Contains(got, "IDENTITY") {
		t.Errorf("SERIAL column must not get an extra IDENTITY clause:\n%s", got)
	}
}

func TestGenerateCreateTableErrors(t *testing.T) {
	d := dialect{}
	if _, err := d.GenerateCreateTable(dbdriver.TableSchema{Name: " "}); err == nil {
		t.Error("empty name must error")
	}
	if _, err := d.GenerateCreateTable(dbdriver.TableSchema{Name: "t"}); err == nil {
		t.Error("no columns must error")
	}
}

func TestGenerateAlterTableColumns(t *testing.T) {
	d := dialect{}
	stmts, err := d.GenerateAlterTable("app", "public", "users", dbdriver.ChangeSet{
		Columns: []dbdriver.ColumnChange{
			{Kind: dbdriver.ColumnDrop, Name: "legacy"},
			{Kind: dbdriver.ColumnAdd, Column: &dbdriver.ColumnMeta{Name: "age", NativeType: "INTEGER", Nullable: true}},
			{Kind: dbdriver.ColumnModify, Column: &dbdriver.ColumnMeta{Name: "name", NativeType: "VARCHAR(128)", Nullable: false}},
			{Kind: dbdriver.ColumnRename, Name: "old", Column: &dbdriver.ColumnMeta{Name: "new", NativeType: "TEXT", Nullable: true}},
		},
	})
	if err != nil {
		t.Fatalf("GenerateAlterTable: %v", err)
	}
	joined := strings.Join(stmts, "\n")
	wantFragments := []string{
		`ALTER TABLE "public"."users" DROP COLUMN "legacy";`,
		`ALTER TABLE "public"."users" ADD COLUMN "age" INTEGER NULL;`,
		`ALTER TABLE "public"."users" ALTER COLUMN "name" TYPE VARCHAR(128) USING "name"::VARCHAR(128);`,
		`ALTER TABLE "public"."users" ALTER COLUMN "name" SET NOT NULL;`,
		`ALTER TABLE "public"."users" RENAME COLUMN "old" TO "new";`,
		`ALTER TABLE "public"."users" ALTER COLUMN "new" DROP NOT NULL;`,
	}
	for _, w := range wantFragments {
		if !strings.Contains(joined, w) {
			t.Errorf("missing statement %q in:\n%s", w, joined)
		}
	}
}

func TestGenerateAlterTablePKIndexFKComment(t *testing.T) {
	d := dialect{}
	stmts, err := d.GenerateAlterTable("app", "public", "users", dbdriver.ChangeSet{
		PrimaryKey: &dbdriver.PrimaryKeyChange{Drop: true, Columns: []string{"id", "tenant"}},
		Indexes: []dbdriver.IndexChange{
			{Kind: "drop", Name: "ix_old"},
			{Kind: "add", Index: &dbdriver.IndexInfo{Name: "ix_new", Columns: []dbdriver.IndexColumn{{Name: "a"}}, Type: "HASH"}},
		},
		ForeignKeys: []dbdriver.ForeignKeyChange{
			{Kind: "drop", Name: "fk_old"},
			{Kind: "add", ForeignKey: &dbdriver.ForeignKeyInfo{
				Name: "fk_new", Columns: []string{"b"},
				ReferencedSchema: "public", ReferencedTable: "p", ReferencedColumns: []string{"id"},
				OnUpdate: "RESTRICT",
			}},
		},
		Options: []dbdriver.TableOptionChange{{Name: "comment", Value: "hi"}},
	})
	if err != nil {
		t.Fatalf("GenerateAlterTable: %v", err)
	}
	joined := strings.Join(stmts, "\n")
	wantFragments := []string{
		`contype = 'p'`, // DO-block PK drop resolves the constraint name server-side
		`ALTER TABLE "public"."users" ADD PRIMARY KEY ("id", "tenant");`,
		`DROP INDEX "public"."ix_old";`,
		`CREATE INDEX "ix_new" ON "public"."users" USING hash ("a");`,
		`ALTER TABLE "public"."users" DROP CONSTRAINT "fk_old";`,
		`ADD CONSTRAINT "fk_new" FOREIGN KEY ("b") REFERENCES "public"."p" ("id") ON UPDATE RESTRICT;`,
		`COMMENT ON TABLE "public"."users" IS 'hi';`,
	}
	for _, w := range wantFragments {
		if !strings.Contains(joined, w) {
			t.Errorf("missing statement %q in:\n%s", w, joined)
		}
	}
}

func TestGenerateAlterTableEmpty(t *testing.T) {
	d := dialect{}
	stmts, err := d.GenerateAlterTable("app", "public", "users", dbdriver.ChangeSet{})
	if err != nil {
		t.Fatalf("GenerateAlterTable: %v", err)
	}
	if len(stmts) != 0 {
		t.Errorf("empty ChangeSet must yield no statements, got %v", stmts)
	}
}

func TestFormatDefaultExpr(t *testing.T) {
	cases := map[string]string{
		"":                       "''",
		"hello":                  "'hello'",
		"o'clock":                "'o''clock'",
		"42":                     "42",
		"-1.5":                   "-1.5",
		"NULL":                   "NULL",
		"now()":                  "now()",
		"CURRENT_TIMESTAMP":      "CURRENT_TIMESTAMP",
		"'x'::character varying": "'x'::character varying",
		"nextval('s'::regclass)": "nextval('s'::regclass)",
		"(random() * 100)":       "(random() * 100)",
	}
	for in, want := range cases {
		if got := formatDefaultExpr(in); got != want {
			t.Errorf("formatDefaultExpr(%q) = %q, want %q", in, got, want)
		}
	}
}
