package postgresdrv

import "catdb/internal/dbdriver"

// UIDialect is PostgreSQL's declarative UI descriptor — the single home of
// Postgres knowledge the front-end needs (type catalog, completion functions,
// snippets, …). See plugins/mysqldrv/uidialect.go for the field contract.
func (driver) UIDialect() dbdriver.UIDialect {
	return dbdriver.UIDialect{
		EditorDialect:          "postgresql",
		IdentQuote:             `"`,
		StringBackslashEscapes: false,
		SystemSchemas:          []string{"pg_catalog", "information_schema", "pg_toast"},
		DefaultSchema:          "public",
		Keywords: []string{
			"RETURNING", "ILIKE", "SIMILAR TO", "OFFSET", "FETCH FIRST",
			"ON CONFLICT", "DO NOTHING", "DO UPDATE SET", "LATERAL",
			"TABLESAMPLE", "SEARCH_PATH", "SET search_path TO",
			"GENERATED BY DEFAULT AS IDENTITY", "GENERATED ALWAYS AS IDENTITY",
			"SERIAL", "BIGSERIAL", "SMALLSERIAL",
			"TEXT", "BYTEA", "UUID", "JSONB", "TIMESTAMPTZ", "TIMETZ",
			"DOUBLE PRECISION", "MATERIALIZED VIEW", "REFRESH MATERIALIZED VIEW",
			"VACUUM", "ANALYZE", "EXPLAIN ANALYZE", "TRUNCATE",
		},
		Functions:   pgFunctions,
		Snippets:    pgSnippets,
		TypeGroups:  pgTypeGroups,
		TypeFormats: pgTypeFormats,

		DefaultColumnType:   "VARCHAR",
		DefaultColumnParams: "255",
		HasUnsigned:         false,
		AutoIncrement: dbdriver.UIAutoIncrement{
			Supported: true,
			BaseTypes: []string{"SMALLINT", "INT", "INTEGER", "BIGINT"},
			// Identity columns are per-column; Postgres allows several, but one
			// per table is the sane editor default — no cap enforced.
		},
		PrimaryKeyForcesNotNull: true,
		IndexTypes:              []string{"BTREE", "HASH", "GIN", "GIST", "BRIN", "SPGIST"},
		// No charset picker — Postgres encodings are per-database at creation
		// time, not a table-level knob.
		DefaultCharset: "",
	}
}

var pgTypeGroups = []dbdriver.UITypeGroup{
	{Key: "string", Types: []string{"VARCHAR", "TEXT", "CHAR"}},
	{Key: "integer", Types: []string{"INTEGER", "BIGINT", "SMALLINT"}},
	{Key: "decimal", Types: []string{"NUMERIC", "REAL", "DOUBLE PRECISION"}},
	{Key: "datetime", Types: []string{"TIMESTAMP", "TIMESTAMPTZ", "DATE", "TIME", "TIMETZ", "INTERVAL"}},
	{Key: "binary", Types: []string{"BYTEA"}},
	{Key: "boolean", Types: []string{"BOOLEAN"}},
	{Key: "other", Types: []string{"JSONB", "JSON", "UUID", "INET", "CIDR", "XML"}},
}

var pgTypeFormats = map[string]dbdriver.UITypeFormat{
	"VARCHAR":     {Kind: "length"},
	"CHAR":        {Kind: "length"},
	"NUMERIC":     {Kind: "precisionScale"},
	"DECIMAL":     {Kind: "precisionScale"},
	"TIMESTAMP":   {Kind: "fractionalSeconds"},
	"TIMESTAMPTZ": {Kind: "fractionalSeconds"},
	"TIME":        {Kind: "fractionalSeconds"},
	"TIMETZ":      {Kind: "fractionalSeconds"},
}

var pgSnippets = []dbdriver.UISnippet{
	{
		Label:  "createtable",
		Detail: "CREATE TABLE …",
		Body: "CREATE TABLE ${name} (\n  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
			"  ${cols}\n)${}",
	},
	{
		Label:  "upsert",
		Detail: "INSERT … ON CONFLICT DO UPDATE",
		Body: "INSERT INTO ${table} (${cols}) VALUES (${values})\n" +
			"ON CONFLICT (${key}) DO UPDATE SET ${assignments}${}",
	},
}

var pgFunctions = []dbdriver.UIFunction{
	{Name: "COUNT", Category: "aggregate", Info: "COUNT(expr) — number of non-NULL rows", Params: []string{"expr"}},
	{Name: "SUM", Category: "aggregate", Info: "SUM(expr) — sum of expr", Params: []string{"expr"}},
	{Name: "AVG", Category: "aggregate", Info: "AVG(expr) — average of expr", Params: []string{"expr"}},
	{Name: "MIN", Category: "aggregate", Info: "MIN(expr)", Params: []string{"expr"}},
	{Name: "MAX", Category: "aggregate", Info: "MAX(expr)", Params: []string{"expr"}},
	{Name: "STRING_AGG", Category: "aggregate", Info: "STRING_AGG(expr, delimiter [ORDER BY …])", Params: []string{"expr", "delimiter"}},
	{Name: "ARRAY_AGG", Category: "aggregate", Info: "ARRAY_AGG(expr [ORDER BY …])", Params: []string{"expr"}},
	{Name: "JSONB_AGG", Category: "aggregate", Info: "JSONB_AGG(expr) — aggregate values as a JSON array", Params: []string{"expr"}},
	{Name: "CONCAT", Category: "string", Info: "CONCAT(str1, str2, …) — concatenate, NULL-safe", Params: []string{"str", "…"}},
	{Name: "CONCAT_WS", Category: "string", Info: "CONCAT_WS(sep, str1, str2, …)", Params: []string{"separator", "str", "…"}},
	{Name: "SUBSTRING", Category: "string", Info: "SUBSTRING(str FROM pos [FOR len])", Params: []string{"str", "pos", "len"}},
	{Name: "LENGTH", Category: "string", Info: "LENGTH(str) — character length"},
	{Name: "OCTET_LENGTH", Category: "string", Info: "OCTET_LENGTH(str) — byte length"},
	{Name: "TRIM", Category: "string"},
	{Name: "LTRIM", Category: "string"},
	{Name: "RTRIM", Category: "string"},
	{Name: "LOWER", Category: "string"},
	{Name: "UPPER", Category: "string"},
	{Name: "INITCAP", Category: "string", Info: "INITCAP(str) — capitalize each word"},
	{Name: "REPLACE", Category: "string", Info: "REPLACE(str, from, to)", Params: []string{"str", "from", "to"}},
	{Name: "LEFT", Category: "string", Info: "LEFT(str, len)", Params: []string{"str", "len"}},
	{Name: "RIGHT", Category: "string", Info: "RIGHT(str, len)", Params: []string{"str", "len"}},
	{Name: "POSITION", Category: "string", Info: "POSITION(substr IN str)", Params: []string{"substr IN str"}},
	{Name: "STRPOS", Category: "string", Info: "STRPOS(str, substr)", Params: []string{"str", "substr"}},
	{Name: "LPAD", Category: "string", Params: []string{"str", "len", "pad"}},
	{Name: "RPAD", Category: "string", Params: []string{"str", "len", "pad"}},
	{Name: "SPLIT_PART", Category: "string", Info: "SPLIT_PART(str, delimiter, n)", Params: []string{"str", "delimiter", "n"}},
	{Name: "REGEXP_REPLACE", Category: "string", Info: "REGEXP_REPLACE(str, pattern, replacement [, flags])", Params: []string{"str", "pattern", "replacement"}},
	{Name: "TO_CHAR", Category: "string", Info: "TO_CHAR(value, format)", Params: []string{"value", "format"}},
	{Name: "ROUND", Category: "numeric", Info: "ROUND(x[, d])", Params: []string{"x", "decimals"}},
	{Name: "FLOOR", Category: "numeric"},
	{Name: "CEIL", Category: "numeric"},
	{Name: "ABS", Category: "numeric"},
	{Name: "MOD", Category: "numeric", Params: []string{"n", "m"}},
	{Name: "POWER", Category: "numeric", Params: []string{"base", "exp"}},
	{Name: "RANDOM", Category: "numeric", NoArgs: true},
	{Name: "TRUNC", Category: "numeric", Info: "TRUNC(x[, d])", Params: []string{"x", "decimals"}},
	{Name: "GREATEST", Category: "numeric"},
	{Name: "LEAST", Category: "numeric"},
	{Name: "NOW", Category: "datetime", Info: "NOW() — current timestamp with time zone", NoArgs: true},
	{Name: "CURRENT_DATE", Category: "datetime", NoArgs: true},
	{Name: "CURRENT_TIME", Category: "datetime", NoArgs: true},
	{Name: "CURRENT_TIMESTAMP", Category: "datetime", NoArgs: true},
	{Name: "AGE", Category: "datetime", Info: "AGE(timestamp[, timestamp]) — symbolic interval", Params: []string{"timestamp"}},
	{Name: "DATE_TRUNC", Category: "datetime", Info: "DATE_TRUNC('field', source)", Params: []string{"field", "source"}},
	{Name: "DATE_PART", Category: "datetime", Info: "DATE_PART('field', source)", Params: []string{"field", "source"}},
	{Name: "EXTRACT", Category: "datetime", Info: "EXTRACT(field FROM source)", Params: []string{"field FROM source"}},
	{Name: "TO_DATE", Category: "datetime", Info: "TO_DATE(str, format)", Params: []string{"str", "format"}},
	{Name: "TO_TIMESTAMP", Category: "datetime", Info: "TO_TIMESTAMP(str, format)", Params: []string{"str", "format"}},
	{Name: "MAKE_INTERVAL", Category: "datetime", Info: "MAKE_INTERVAL(years => 0, months => 0, …)", Params: []string{"…"}},
	{Name: "NULLIF", Category: "control", Info: "NULLIF(a, b) — NULL if a=b", Params: []string{"a", "b"}},
	{Name: "COALESCE", Category: "control", Info: "COALESCE(a, b, …) — first non-NULL", Params: []string{"a", "b", "…"}},
	{Name: "JSONB_BUILD_OBJECT", Category: "json", Info: "JSONB_BUILD_OBJECT(k1, v1, …)", Params: []string{"key", "value", "…"}},
	{Name: "JSONB_BUILD_ARRAY", Category: "json", Params: []string{"…"}},
	{Name: "JSONB_EXTRACT_PATH", Category: "json", Info: "JSONB_EXTRACT_PATH(jsonb, path…)", Params: []string{"jsonb", "path"}},
	{Name: "JSONB_ARRAY_ELEMENTS", Category: "json", Info: "JSONB_ARRAY_ELEMENTS(jsonb) — set of elements", Params: []string{"jsonb"}},
	{Name: "JSONB_EACH", Category: "json", Info: "JSONB_EACH(jsonb) — set of key/value pairs", Params: []string{"jsonb"}},
	{Name: "TO_JSONB", Category: "json", Params: []string{"value"}},
	{Name: "CAST", Category: "cast", Info: "CAST(expr AS type)", Params: []string{"expr AS type"}},
	{Name: "VERSION", Category: "system", NoArgs: true},
	{Name: "CURRENT_DATABASE", Category: "system", NoArgs: true},
	{Name: "CURRENT_SCHEMA", Category: "system", NoArgs: true},
	{Name: "CURRENT_USER", Category: "system", NoArgs: true},
	{Name: "PG_SLEEP", Category: "system", Info: "PG_SLEEP(seconds)", Params: []string{"seconds"}},
	{Name: "GEN_RANDOM_UUID", Category: "system", NoArgs: true},
	{Name: "PG_TOTAL_RELATION_SIZE", Category: "system", Info: "PG_TOTAL_RELATION_SIZE(regclass)", Params: []string{"regclass"}},
	{Name: "PG_SIZE_PRETTY", Category: "system", Params: []string{"bytes"}},
}
