// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "connection:saved": { [_ in string]?: any };
            "custom:switch-english-input": { [_ in string]?: any };
            "transfer:progress": { [_ in string]?: any };
            "window:close-blocked": { [_ in string]?: any };
        }
    }
}
