//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "agent:delta": $$createType0,
        "agent:done": $$createType0,
        "agent:error": $$createType0,
        "agent:thinking": $$createType0,
        "agent:tool": $$createType0,
        "agent:usage": $$createType0,
        "connection:saved": $$createType0,
        "custom:switch-english-input": $$createType0,
        "transfer:progress": $$createType0,
        "update:progress": $$createType0,
        "window:close-blocked": $$createType0,
    }));
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);

configure();
