// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DiffSample is one retained difference for the preview UI. Key holds the
 * primary-key values; Columns names the changed columns (updates only).
 */
export class DiffSample {
    /**
     * "insert" | "update" | "delete"
     */
    "kind": string;
    "key": any[];
    "columns"?: string[];

    /** Creates a new DiffSample instance. */
    constructor($$source: Partial<DiffSample> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffSample instance from a string or object.
     */
    static createFrom($$source: any = {}): DiffSample {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("key" in $$parsedSource) {
            $$parsedSource["key"] = $$createField1_0($$parsedSource["key"]);
        }
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField2_0($$parsedSource["columns"]);
        }
        return new DiffSample($$parsedSource as Partial<DiffSample>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
