<script setup lang="ts">
// TableStructure — editable Columns / Indexes / Foreign Keys / Options
// panels driven by MetadataService.GetTableSummary + GetCreateTable.
//
// Editing happens against a local StructureDraft (see lib/alterPlan.ts) that
// snapshots the original column/index/FK lists when the table is loaded. As
// the user edits, buildAlterPlan() diffs original-vs-draft in the Go backend
// (schemadiff + the driver's Dialect) and returns ALTER statements; those
// land in the AlterSqlPanel under each tab. Apply executes them sequentially
// via QueryService and reloads. Editor behavior (type catalog, modifier and
// auto-increment rules) is driven by the driver's UIDialect descriptor.
//
// "new" mode reuses the same editor for creating a brand-new table: the
// backend metadata load is skipped, a single CREATE TABLE statement is
// generated by buildCreateTable() from the draft, and on Apply the tab is
// promoted to a regular edit-mode structure tab anchored to the just-created
// table.
import { computed, onMounted, ref, watch } from 'vue'
import { NInput, NSpin, NTabPane, NTabs, useMessage } from 'naive-ui'
import { metadata as metaApi, query as queryApi } from '../../api'
import { genericUIDialect, uiDialectForConnection, type UIDialect } from '../../api/dialect'
import { t } from '../../i18n'
import type { TableSummary } from '../../api/metadata'
import { useMetadataStore } from '../../stores/metadata'
import { useQueryStore } from '../../stores/query'
import {
  columnToDraft,
  draftToWire,
  emptyAlterPlan,
  emptyColumnDraft,
  foreignKeyToDraft,
  indexToDraft,
  type AlterPlan,
  type StructureDraft,
} from '../../lib/alterPlan'
import AlterSqlPanel from '../structure/AlterSqlPanel.vue'
import ColumnsTab from '../structure/ColumnsTab.vue'
import IndexesTab from '../structure/IndexesTab.vue'
import ForeignKeysTab from '../structure/ForeignKeysTab.vue'
import OptionsTab from '../structure/OptionsTab.vue'
import DdlPanel from '../shared/DdlPanel.vue'

const props = withDefaults(
  defineProps<{
    connId: string
    db: string
    /** Schema between db and table for schema-ful databases; '' otherwise. */
    schema?: string
    table: string
    /** 'edit' loads an existing table; 'new' creates one from a blank draft. */
    mode?: 'edit' | 'new'
    /** Tab id — required in 'new' mode so we can promote it after CREATE. */
    tabId?: string
  }>(),
  { mode: 'edit', tabId: '' },
)

const message = useMessage()
const queryStore = useQueryStore()
const metaStore = useMetadataStore()

// The driver's UI descriptor — resolves async; the generic fallback keeps the
// editor rendering until it lands.
const dialect = ref<UIDialect>(genericUIDialect())
watch(() => props.connId, async (id) => {
  dialect.value = id ? await uiDialectForConnection(id) : genericUIDialect()
}, { immediate: true })
const summary = ref<TableSummary | null>(null)
const origComment = ref<string>('')
const ddl = ref<string>('')
const loading = ref(false)
const busy = ref(false)
const activeTab = ref('cols')

// In 'new' mode the user types the table name directly here; in 'edit' mode
// it mirrors the `table` prop (read-only display).
const newTableName = ref<string>('')

// Draft state — the user-edited mirror of summary + origComment.
// Re-built whenever load() runs (initial mount, table switch, after Apply).
const draft = ref<StructureDraft>({
  columns: [],
  indexes: [],
  foreignKeys: [],
  options: { comment: '' },
})

// ---- 数据懒加载 ------------------------------------------------------------
//
// 首次挂载只拉 Columns（默认激活的 tab），Indexes / Foreign Keys / DDL 等用户第
// 一次切到对应 tab 才调用独立接口。每个数据段用 loaded 标记去重，换表时重置。
const loaded = ref({ columns: false, indexes: false, foreignKeys: false, ddl: false })

async function load() {
  if (props.mode === 'new') {
    // No backend round-trip: synthesize an empty "original" so the diff
    // helpers still work (they only matter for the edit path, but plan is
    // reactive on summary.value).
    summary.value = { columns: [], indexes: [], foreignKeys: [] } as unknown as TableSummary
    ddl.value = ''
    origComment.value = ''
    newTableName.value = props.table ?? ''
    loaded.value = { columns: true, indexes: true, foreignKeys: true, ddl: true }
    resetDraft()
    return
  }
  // Reset loaded flags — table changed, data must be re-fetched.
  loaded.value = { columns: false, indexes: false, foreignKeys: false, ddl: false }
  summary.value = null
  ddl.value = ''
  origComment.value = ''

  loading.value = true
  try {
    await ensureColumns()
  } finally {
    loading.value = false
  }
}

async function ensureColumns() {
  if (loaded.value.columns) return
  loaded.value.columns = true
  try {
    const cols = await metaApi.listColumns(props.connId, props.db, props.table, props.schema ?? '')
    summary.value = { columns: cols, indexes: [], foreignKeys: [] }
    resetDraft()
  } catch (e) {
    message.error(t('tableStructure.loadColumnsFailed', { error: String(e) }))
  }
}

async function ensureIndexes() {
  if (loaded.value.indexes) return
  loaded.value.indexes = true
  try {
    const indexes = await metaApi.listIndexes(props.connId, props.db, props.table, props.schema ?? '')
    summary.value = { ...summary.value!, indexes }
    // 首次加载 → 用后端数据填充 draft.indexes（用户尚未编辑过索引）
    if (!(draft.value.indexes ?? []).some((d) => d.origName)) {
      draft.value = { ...draft.value, indexes: (indexes ?? []).map(indexToDraft) }
    }
  } catch (e) {
    message.error(t('tableStructure.loadIndexesFailed', { error: String(e) }))
  }
}

async function ensureForeignKeys() {
  if (loaded.value.foreignKeys) return
  loaded.value.foreignKeys = true
  try {
    const fks = await metaApi.listForeignKeys(props.connId, props.db, props.table, props.schema ?? '')
    summary.value = { ...summary.value!, foreignKeys: fks }
    if (!(draft.value.foreignKeys ?? []).some((d) => d.origName)) {
      draft.value = { ...draft.value, foreignKeys: (fks ?? []).map(foreignKeyToDraft) }
    }
  } catch (e) {
    message.error(t('tableStructure.loadForeignKeysFailed', { error: String(e) }))
  }
}

async function ensureDDL() {
  if (loaded.value.ddl) return
  loaded.value.ddl = true
  try {
    const [d, comment] = await Promise.all([
      metaApi.getCreateTable(props.connId, props.db, props.table, props.schema ?? ''),
      metaApi.getTableComment(props.connId, props.db, props.table, props.schema ?? ''),
    ])
    ddl.value = d
    origComment.value = comment
    // 更新 options draft 中的 comment
    draft.value = { ...draft.value, options: { comment: origComment.value } }
  } catch (e) {
    message.error(t('tableStructure.loadDdlFailed', { error: String(e) }))
  }
}

onMounted(load)
watch(() => [props.connId, props.db, props.schema, props.table, props.mode], load)

// 切 tab 时懒加载对应的数据
watch(activeTab, (tab) => {
  switch (tab) {
    case 'ix':
      ensureIndexes()
      break
    case 'fk':
      ensureForeignKeys()
      break
    case 'opts':
    case 'ddl':
      ensureDDL()
      break
  }
})

function resetDraft() {
  if (props.mode === 'new') {
    // Seed with one blank column row so the editor has something to click on.
    draft.value = {
      columns: [emptyColumnDraft(dialect.value)],
      indexes: [],
      foreignKeys: [],
      options: { comment: '' },
    }
    return
  }
  if (!summary.value) return
  const s = summary.value
  draft.value = {
    columns: (s.columns ?? []).map((c, i) => columnToDraft(c, i)),
    indexes: loaded.value.indexes ? (s.indexes ?? []).map(indexToDraft) : [],
    foreignKeys: loaded.value.foreignKeys ? (s.foreignKeys ?? []).map(foreignKeyToDraft) : [],
    options: loaded.value.ddl ? { comment: origComment.value } : { comment: '' },
  }
}

// ---- plan (CREATE in new mode, ALTER diff in edit mode) -------------------
//
// The diff runs in the Go backend (schemadiff + Dialect). Edits are frequent,
// so refreshes are debounced and guarded by a sequence number — a stale
// response never overwrites a newer plan.

const plan = ref<AlterPlan>(emptyAlterPlan())
let planSeq = 0
let planTimer: ReturnType<typeof setTimeout> | undefined

watch(
  [draft, summary, origComment, newTableName, () => props.mode],
  () => {
    if (planTimer) clearTimeout(planTimer)
    planTimer = setTimeout(refreshPlan, 150)
  },
  { deep: true, immediate: true },
)

async function refreshPlan() {
  const seq = ++planSeq
  try {
    if (props.mode === 'new') {
      const stmt = await metaApi.buildCreateTable(
        props.connId, props.db, newTableName.value, draftToWire(dialect.value, draft.value),
        props.schema ?? '',
      )
      if (seq !== planSeq) return
      const stmts = stmt ? [stmt] : []
      plan.value = { columns: stmts, indexes: stmts, foreignKeys: stmts, options: stmts, all: stmts }
      return
    }
    if (!summary.value) {
      if (seq === planSeq) plan.value = emptyAlterPlan()
      return
    }
    const res = await metaApi.buildAlterPlan(
      props.connId, props.db, props.table,
      summary.value, origComment.value, draftToWire(dialect.value, draft.value),
      props.schema ?? '',
    )
    if (seq !== planSeq) return
    plan.value = res
  } catch (e) {
    // Per-keystroke preview refresh — log instead of toasting on every edit.
    console.warn('alter plan refresh failed:', e)
  }
}

// ---- apply ----------------------------------------------------------------

async function applyStatements(stmts: string[]) {
  if (stmts.length === 0 || busy.value) return
  busy.value = true

  if (props.mode === 'new') {
    // Single CREATE TABLE statement. On success, invalidate the table list so
    // the object tree picks up the new table, then promote this tab.
    try {
      const created = newTableName.value.trim()
      await queryApi.runQuery(props.connId, stmts[0].trim().replace(/;$/, ''))
      metaStore.invalidateTables(props.connId, props.db, props.schema ?? '')
      const qualified = [props.db, props.schema, created].filter(Boolean).join('.')
      message.success(t('tableStructure.tableCreated', { name: qualified }))
      if (props.tabId) {
        queryStore.promoteNewTableTab(props.tabId, created)
      }
    } catch (e) {
      message.error(t('tableStructure.createFailed', { error: String(e) }))
    } finally {
      busy.value = false
    }
    return
  }

  let executed = 0
  try {
    for (const raw of stmts) {
      const trimmed = raw.trim().replace(/;$/, '')
      if (!trimmed) continue
      await queryApi.runQuery(props.connId, trimmed)
      executed++
    }
    message.success(t('tableStructure.statementsApplied', { count: executed }))
    await load()
  } catch (e) {
    message.error(
      t('tableStructure.applyFailed', {
        executed,
        total: stmts.length,
        error: String(e),
      }),
    )
    // Reload anyway so the UI reflects whatever did land.
    await load()
  } finally {
    busy.value = false
  }
}

// In 'new' mode Apply needs at least a table name + one named column.
const newApplyDisabled = computed(() => {
  if (props.mode !== 'new') return false
  if (!newTableName.value.trim()) return true
  if (!(draft.value.columns ?? []).some((c) => c.name.trim() !== '')) return true
  return false
})

// ---- DDL display (delegated to DdlPanel) --------------------------------
</script>

<template>
  <n-spin :show="loading" class="ts">
    <!-- Header bar: in 'new' mode show a table-name input so the user can
         pick what they're creating. In edit mode this is omitted (the tab
         title already shows db.table). -->
    <div v-if="mode === 'new'" class="new-table-header">
      <span class="ntb-label">{{ $t('tableStructure.newTableLabel', { db }) }}</span>
      <n-input
        v-model:value="newTableName"
        size="small"
        :placeholder="$t('tableStructure.tableNamePlaceholder')"
        class="ntb-name"
        :disabled="busy"
      />
    </div>
    <n-tabs
      v-model:value="activeTab"
      type="segment"
      size="small"
      class="group-tabs"
    >
      <!-- Columns -->
      <n-tab-pane name="cols" tab="Columns" display-directive="show:lazy">
        <div class="tab-body">
          <ColumnsTab v-model="draft.columns" :dialect="dialect" :busy="busy" />
          <AlterSqlPanel
            :dialect="dialect"
            :statements="plan.columns"
            :busy="busy"
            :apply-disabled="newApplyDisabled"
            :apply-confirm-title="mode === 'new' ? $t('tableStructure.createTable') : $t('tableStructure.applyColumnChanges')"
            @apply="applyStatements(plan.columns)"
            @reset="resetDraft"
          />
        </div>
      </n-tab-pane>

      <!-- Indexes -->
      <n-tab-pane name="ix" tab="Indexes" display-directive="show:lazy">
        <div class="tab-body">
          <IndexesTab
            v-model="draft.indexes"
            :columns-draft="draft.columns"
            :busy="busy"
          />
          <AlterSqlPanel
            :dialect="dialect"
            :statements="plan.indexes"
            :busy="busy"
            :apply-disabled="newApplyDisabled"
            :apply-confirm-title="mode === 'new' ? $t('tableStructure.createTable') : $t('tableStructure.applyIndexChanges')"
            @apply="applyStatements(plan.indexes)"
            @reset="resetDraft"
          />
        </div>
      </n-tab-pane>

      <!-- Foreign Keys -->
      <n-tab-pane name="fk" tab="Foreign Keys" display-directive="show:lazy">
        <div class="tab-body">
          <ForeignKeysTab
            v-model="draft.foreignKeys"
            :columns-draft="draft.columns"
            :current-db="db"
            :busy="busy"
          />
          <AlterSqlPanel
            :dialect="dialect"
            :statements="plan.foreignKeys"
            :busy="busy"
            :apply-disabled="newApplyDisabled"
            :apply-confirm-title="mode === 'new' ? $t('tableStructure.createTable') : $t('tableStructure.applyForeignKeyChanges')"
            @apply="applyStatements(plan.foreignKeys)"
            @reset="resetDraft"
          />
        </div>
      </n-tab-pane>

      <!-- Options (table-level: comment etc.) -->
      <n-tab-pane name="opts" tab="Options" display-directive="show:lazy">
        <div class="tab-body">
          <OptionsTab v-model="draft.options" :busy="busy" />
          <AlterSqlPanel
            :dialect="dialect"
            :statements="plan.options"
            :busy="busy"
            :apply-disabled="newApplyDisabled"
            :apply-confirm-title="mode === 'new' ? $t('tableStructure.createTable') : $t('tableStructure.applyTableOptions')"
            @apply="applyStatements(plan.options)"
            @reset="resetDraft"
          />
        </div>
      </n-tab-pane>

      <!-- DDL (read-only). Hidden in 'new' mode — the AlterSqlPanel already
           shows the CREATE TABLE statement for every tab. -->
      <n-tab-pane v-if="mode !== 'new'" name="ddl" tab="DDL" display-directive="show:lazy">
        <DdlPanel variant="tab" :ddl="ddl" :dialect="dialect" />
      </n-tab-pane>
    </n-tabs>
  </n-spin>
</template>

<style scoped>
/* ---- root flex container ---- */
.ts { height: 100%; display: flex; flex-direction: column; min-width: 0; min-height: 0; overflow: hidden; }
.ts :deep(.n-spin-container),
.ts :deep(.n-spin-content) { height: 100%; min-width: 0; min-height: 0; display: flex; flex-direction: column; }

/* ---- new-table header (only shown in mode="new") ---- */
.new-table-header {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 8px 10px;
  border-bottom: 1px solid var(--n-border-color);
  flex: 0 0 auto;
}
.new-table-header .ntb-label {
  font-size: 12px;
  opacity: 0.75;
  flex: 0 0 auto;
  white-space: nowrap;
}
.new-table-header .ntb-name {
  max-width: 280px;
}

/* ---- segmented tabs (liquid glass, matching ConnectionForm) ---- */
.group-tabs {
  height: 35px;
  flex: 1;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  min-width: 0;
  min-height: 0;
}
.group-tabs :deep(.n-tabs-nav) {
  display: flex;
  justify-content: center;
}
.group-tabs :deep(.n-tabs-rail) {
  min-width: 0;
  margin: 6px;
  padding: 3px;
  border-radius: 8px;
  background:
    linear-gradient(180deg,
      rgba(255, 255, 255, 0.5) 0%,
      rgba(255, 255, 255, 0.18) 100%);
  backdrop-filter: blur(18px) saturate(180%);
  -webkit-backdrop-filter: blur(18px) saturate(180%);
  box-shadow:
    inset 0 1px 0 rgba(255, 255, 255, 0.75),
    inset 0 -1px 0 rgba(0, 0, 0, 0.04),
    0 0 0 0.5px rgba(0, 0, 0, 0.1),
    0 1px 2px rgba(0, 0, 0, 0.08);
}
.group-tabs :deep(.n-tabs-tab) {
  padding: 2px 14px;
  font-size: 12px;
  border-radius: 8px;
  font-weight: 500;
  color: inherit;
  opacity: 0.7;
  transition: opacity 120ms ease, background 120ms ease;
}
.group-tabs :deep(.n-tabs-tab:hover) {
  opacity: 0.95;
  background: rgba(255, 255, 255, 0.35);
}
.group-tabs :deep(.n-tabs-tab--active) {
  opacity: 1;
  font-weight: 600;
  color: inherit;
  background:
    linear-gradient(180deg,
      rgba(255, 255, 255, 0.85) 0%,
      rgba(255, 255, 255, 0.55) 100%);
  box-shadow:
    inset 0 1px 0 rgba(255, 255, 255, 0.95),
    inset 0 -1px 0 rgba(0, 0, 0, 0.04),
    0 0.5px 1px rgba(0, 0, 0, 0.08);
}

@media (prefers-color-scheme: dark) {
  .group-tabs :deep(.n-tabs-rail) {
    background:
      linear-gradient(180deg,
        rgba(255, 255, 255, 0.12) 0%,
        rgba(255, 255, 255, 0.04) 100%);
    box-shadow:
      inset 0 1px 0 rgba(255, 255, 255, 0.18),
      inset 0 -1px 0 rgba(0, 0, 0, 0.3),
      0 0 0 0.5px rgba(255, 255, 255, 0.06),
      0 1px 2px rgba(0, 0, 0, 0.3);
  }
  .group-tabs :deep(.n-tabs-tab:hover) {
    background: rgba(255, 255, 255, 0.1);
  }
  .group-tabs :deep(.n-tabs-tab--active) {
    background:
      linear-gradient(180deg,
        rgba(255, 255, 255, 0.2) 0%,
        rgba(255, 255, 255, 0.08) 100%);
    box-shadow:
      inset 0 1px 0 rgba(255, 255, 255, 0.25),
      inset 0 -1px 0 rgba(0, 0, 0, 0.25),
      0 0.5px 1px rgba(0, 0, 0, 0.25);
  }
}

@supports not ((backdrop-filter: blur(1px)) or (-webkit-backdrop-filter: blur(1px))) {
  .group-tabs :deep(.n-tabs-rail) { background: rgba(255, 255, 255, 0.6); }
  @media (prefers-color-scheme: dark) {
    .group-tabs :deep(.n-tabs-rail) { background: rgba(255, 255, 255, 0.1); }
  }
}

.group-tabs :deep(.n-tabs-pane-wrapper) {
  flex: 1;
  overflow: hidden;
  min-height: 0;
}
.group-tabs :deep(.n-tab-pane) {
  height: 100%;
  overflow: hidden;
  padding: 0;
}

/* tab-body: editor on top, AlterSqlPanel pinned at the bottom */
.tab-body {
  height: 100%;
  display: flex;
  flex-direction: column;
  min-height: 0;
  overflow: hidden;
}

</style>
