// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as llm$0 from "../llm/models.js";

/**
 * ProviderConfig 是一个 Provider 实例的非敏感配置（存 SQLite，绝不含密钥）。
 * Models 为内置/自定义模型清单：ContextWindow 供上下文水位计算，SupportsTools
 * 决定工具能力，二者对 openai-compat 自定义模型无法探测，由配置提供（§3.1）。
 */
export class ProviderConfig {
    "id": string;
    "name": string;
    "type": string;
    "baseURL": string;
    "models": llm$0.ModelInfo[];
    "defaultModel": string;

    /** Creates a new ProviderConfig instance. */
    constructor($$source: Partial<ProviderConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("baseURL" in $$source)) {
            this["baseURL"] = "";
        }
        if (!("models" in $$source)) {
            this["models"] = [];
        }
        if (!("defaultModel" in $$source)) {
            this["defaultModel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderConfig {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField4_0($$parsedSource["models"]);
        }
        return new ProviderConfig($$parsedSource as Partial<ProviderConfig>);
    }
}

// Private type creation functions
const $$createType0 = llm$0.ModelInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
