// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentTraceService exposes the dev-only agent interaction traces (see
 * internal/agenttrace) to the Trace window. In production builds every method
 * reports the subsystem as disabled/empty — the front-end hides the entry.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearTraces deletes all trace files.
 */
export function ClearTraces(): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.AgentTraceService.ClearTraces");
}

/**
 * GetTrace returns the session's raw JSONL trace; the front-end parses lines.
 */
export function GetTrace(sessID: string): $CancellablePromise<string> {
    return $Call.ByName("catdb/internal/services.AgentTraceService.GetTrace", sessID);
}

/**
 * ListTraceSessions returns traced sessions, most recently updated first.
 */
export function ListTraceSessions(): $CancellablePromise<$models.TraceSession[]> {
    return $Call.ByName("catdb/internal/services.AgentTraceService.ListTraceSessions").then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * OpenTraceWindow opens (or focuses) the Trace child window, optionally
 * pre-selecting a session.
 */
export function OpenTraceWindow(sessID: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.AgentTraceService.OpenTraceWindow", sessID);
}

/**
 * TraceEnabled reports whether this build records traces (dev builds only).
 */
export function TraceEnabled(): $CancellablePromise<boolean> {
    return $Call.ByName("catdb/internal/services.AgentTraceService.TraceEnabled");
}

// Private type creation functions
const $$createType0 = $models.TraceSession.createFrom;
const $$createType1 = $Create.Array($$createType0);
