// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentService is the thin Wails binding over internal/agent: input
 * validation, forwarding to the engine, and session CRUD. Streaming output
 * travels over agent:* events, not return values (AGENT_DESIGN.md §13).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";

/**
 * Approve resolves a pending statement approval or task plan.
 * scope: "once" | "task-verb" (auto-approve same verb for the rest of the task).
 */
export function Approve(approvalID: string, scope: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.AgentService.Approve", approvalID, scope);
}

/**
 * Cancel stops the session's running loop, if any.
 */
export function Cancel(sessID: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.AgentService.Cancel", sessID);
}

/**
 * CommitTx commits the session's pending task transaction.
 */
export function CommitTx(sessID: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.AgentService.CommitTx", sessID);
}

/**
 * Compact manually folds the session's early rounds into a summary (§9).
 */
export function Compact(sessID: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.AgentService.Compact", sessID);
}

/**
 * CreateSession opens a new session bound to connID. mode is "ask" or
 * "agent"; provider/model default from settings when empty.
 */
export function CreateSession(connID: string, mode: string): $CancellablePromise<storage$0.AgentSession> {
    return $Call.ByName("catdb/internal/services.AgentService.CreateSession", connID, mode).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteSession removes a session and its messages (audit is preserved).
 */
export function DeleteSession(sessID: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.AgentService.DeleteSession", sessID);
}

/**
 * GetMessages returns a session's full message history (compacted included —
 * the chat panel always shows everything, §9).
 */
export function GetMessages(sessID: string): $CancellablePromise<storage$0.AgentMessage[]> {
    return $Call.ByName("catdb/internal/services.AgentService.GetMessages", sessID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ListSessions returns the sessions of a connection, most recent first.
 */
export function ListSessions(connID: string): $CancellablePromise<storage$0.AgentSession[]> {
    return $Call.ByName("catdb/internal/services.AgentService.ListSessions", connID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Reject declines a pending approval; reason (optional) is fed back to the model.
 */
export function Reject(approvalID: string, reason: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.AgentService.Reject", approvalID, reason);
}

/**
 * RenameSession sets a session's title.
 */
export function RenameSession(sessID: string, title: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.AgentService.RenameSession", sessID, title);
}

/**
 * RollbackTx rolls the session's pending task transaction back.
 */
export function RollbackTx(sessID: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.AgentService.RollbackTx", sessID);
}

/**
 * SendMessage runs one agent turn. mentions are @table chips (§10.3) resolved
 * against the session's current namespace. It blocks until the turn
 * completes; cancelling the front-end promise aborts the loop.
 */
export function SendMessage(sessID: string, text: string, mentions: string[]): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.AgentService.SendMessage", sessID, text, mentions);
}

/**
 * SetGrants replaces the session's statement grants (§5 gate 3).
 */
export function SetGrants(sessID: string, grants: string[]): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.AgentService.SetGrants", sessID, grants);
}

/**
 * SetMode switches a session between ask and agent mode.
 */
export function SetMode(sessID: string, mode: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.AgentService.SetMode", sessID, mode);
}

/**
 * SetNamespace switches the session's selected database/schema (§10.2).
 */
export function SetNamespace(sessID: string, db: string, schema: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.AgentService.SetNamespace", sessID, db, schema);
}

/**
 * SetSessionModel switches the session's provider/model (takes effect next turn).
 */
export function SetSessionModel(sessID: string, providerID: string, model: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.AgentService.SetSessionModel", sessID, providerID, model);
}

// Private type creation functions
const $$createType0 = storage$0.AgentSession.createFrom;
const $$createType1 = storage$0.AgentMessage.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($$createType0);
