// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentSettingsService exposes AI Agent Provider configuration to the settings
 * window: Provider CRUD + keyring-backed API keys + default provider/model +
 * a connectivity test. It is a thin binding — all persistence logic lives in
 * internal/llmconfig; keys live in keyring (never SQLite), per CLAUDE.md #8.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as llm$0 from "../llm/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as llmconfig$0 from "../llmconfig/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearAudit deletes audit entries created strictly before beforeUnixSec.
 */
export function ClearAudit(beforeUnixSec: number): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.AgentSettingsService.ClearAudit", beforeUnixSec);
}

/**
 * DeleteProvider removes a Provider instance, its keyring key, and clears the
 * default provider/model if they pointed at it.
 */
export function DeleteProvider(id: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.AgentSettingsService.DeleteProvider", id);
}

/**
 * ExportAudit writes every audit entry matching the filter (no pagination) to
 * path as JSON or CSV. Rows are written straight to disk (never crossing IPC as
 * a bulk payload, 铁律 5); the front-end picks path via system.pickSaveFile.
 * format is "json" or "csv".
 */
export function ExportAudit(q: $models.AuditQuery, format: string, path: string): $CancellablePromise<$models.AuditExportResult> {
    return $Call.ByName("catdb/internal/services.AgentSettingsService.ExportAudit", q, format, path).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * FetchProviderModels queries the provider's live model list using draft
 * (possibly unsaved) config — the settings page "fetch from API" button. It
 * never touches Provider.Models(), which agent loop relies on to stay the
 * static, user-configured list.
 */
export function FetchProviderModels(req: $models.FetchModelsRequest): $CancellablePromise<llm$0.ModelInfo[]> {
    return $Call.ByName("catdb/internal/services.AgentSettingsService.FetchProviderModels", req).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetAgentSettings returns the Agent runtime settings, unset keys falling back
 * to their defaults (AGENT_DESIGN.md §12).
 */
export function GetAgentSettings(): $CancellablePromise<llmconfig$0.AgentSettings> {
    return $Call.ByName("catdb/internal/services.AgentSettingsService.GetAgentSettings").then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetDefaults returns the default Provider instance + model.
 */
export function GetDefaults(): $CancellablePromise<$models.AgentDefaults> {
    return $Call.ByName("catdb/internal/services.AgentSettingsService.GetDefaults").then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * HasProviderKey reports whether a non-empty API key is stored for the Provider,
 * without ever revealing it — the settings page shows a "configured" state only.
 */
export function HasProviderKey(id: string): $CancellablePromise<boolean> {
    return $Call.ByName("catdb/internal/services.AgentSettingsService.HasProviderKey", id);
}

/**
 * ListAudit returns one page of audit entries, most recent first.
 */
export function ListAudit(q: $models.AuditQuery): $CancellablePromise<$models.AuditPage> {
    return $Call.ByName("catdb/internal/services.AgentSettingsService.ListAudit", q).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ListProviders returns all configured Provider instances (never any key).
 */
export function ListProviders(): $CancellablePromise<llmconfig$0.ProviderConfig[]> {
    return $Call.ByName("catdb/internal/services.AgentSettingsService.ListProviders").then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * SaveProvider upserts a Provider instance. An empty ID means "create" and gets
 * a fresh UUID; the saved config (with its final ID) is returned. Never touches
 * the keyring — use SetProviderKey for the API key.
 */
export function SaveProvider(p: llmconfig$0.ProviderConfig): $CancellablePromise<llmconfig$0.ProviderConfig> {
    return $Call.ByName("catdb/internal/services.AgentSettingsService.SaveProvider", p).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * SetAgentSettings persists all Agent runtime settings at once (privacy switch,
 * limits, compaction, per-model pricing table).
 */
export function SetAgentSettings(settings: llmconfig$0.AgentSettings): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.AgentSettingsService.SetAgentSettings", settings);
}

/**
 * SetDefaults persists the default Provider instance + model.
 */
export function SetDefaults(providerID: string, model: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.AgentSettingsService.SetDefaults", providerID, model);
}

/**
 * SetProviderKey stores (write-only) the API key for a Provider in the keyring.
 * An empty key is rejected — use DeleteProvider to clear a key with its config.
 */
export function SetProviderKey(id: string, key: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.AgentSettingsService.SetProviderKey", id, key);
}

/**
 * TestProvider probes connectivity by resolving the Provider and firing one
 * minimal MaxTokens=1 "ping" stream. Success = the stream established and read
 * without error. Technical errors are returned verbatim (English, per §14).
 */
export function TestProvider(id: string, model: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.AgentSettingsService.TestProvider", id, model);
}

// Private type creation functions
const $$createType0 = $models.AuditExportResult.createFrom;
const $$createType1 = llm$0.ModelInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = llmconfig$0.AgentSettings.createFrom;
const $$createType4 = $models.AgentDefaults.createFrom;
const $$createType5 = $models.AuditPage.createFrom;
const $$createType6 = llmconfig$0.ProviderConfig.createFrom;
const $$createType7 = $Create.Array($$createType6);
