// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentSettingsService exposes AI Agent Provider configuration to the settings
 * window: Provider CRUD + keyring-backed API keys + default provider/model +
 * a connectivity test. It is a thin binding — all persistence logic lives in
 * internal/llmconfig; keys live in keyring (never SQLite), per CLAUDE.md #8.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as llmconfig$0 from "../llmconfig/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteProvider removes a Provider instance, its keyring key, and clears the
 * default provider/model if they pointed at it.
 */
export function DeleteProvider(id: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.AgentSettingsService.DeleteProvider", id);
}

/**
 * GetDefaults returns the default Provider instance + model.
 */
export function GetDefaults(): $CancellablePromise<$models.AgentDefaults> {
    return $Call.ByName("catdb/internal/services.AgentSettingsService.GetDefaults").then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * HasProviderKey reports whether a non-empty API key is stored for the Provider,
 * without ever revealing it — the settings page shows a "configured" state only.
 */
export function HasProviderKey(id: string): $CancellablePromise<boolean> {
    return $Call.ByName("catdb/internal/services.AgentSettingsService.HasProviderKey", id);
}

/**
 * ListProviders returns all configured Provider instances (never any key).
 */
export function ListProviders(): $CancellablePromise<llmconfig$0.ProviderConfig[]> {
    return $Call.ByName("catdb/internal/services.AgentSettingsService.ListProviders").then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SaveProvider upserts a Provider instance. An empty ID means "create" and gets
 * a fresh UUID; the saved config (with its final ID) is returned. Never touches
 * the keyring — use SetProviderKey for the API key.
 */
export function SaveProvider(p: llmconfig$0.ProviderConfig): $CancellablePromise<llmconfig$0.ProviderConfig> {
    return $Call.ByName("catdb/internal/services.AgentSettingsService.SaveProvider", p).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SetDefaults persists the default Provider instance + model.
 */
export function SetDefaults(providerID: string, model: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.AgentSettingsService.SetDefaults", providerID, model);
}

/**
 * SetProviderKey stores (write-only) the API key for a Provider in the keyring.
 * An empty key is rejected — use DeleteProvider to clear a key with its config.
 */
export function SetProviderKey(id: string, key: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.AgentSettingsService.SetProviderKey", id, key);
}

/**
 * TestProvider probes connectivity by resolving the Provider and firing one
 * minimal MaxTokens=1 "ping" stream. Success = the stream established and read
 * without error. Technical errors are returned verbatim (English, per §14).
 */
export function TestProvider(id: string, model: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.AgentSettingsService.TestProvider", id, model);
}

// Private type creation functions
const $$createType0 = $models.AgentDefaults.createFrom;
const $$createType1 = llmconfig$0.ProviderConfig.createFrom;
const $$createType2 = $Create.Array($$createType1);
