// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionService is the Wails Service that owns connection profiles and
 * the live-connection lifecycle. Per ARCHITECTURE.md §2 it stays THIN:
 * validates input, calls into storage/session, no business logic.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dbdriver$0 from "../dbdriver/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Connect opens (or returns the cached) live Connection for id.
 */
export function Connect(id: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.ConnectionService.Connect", id);
}

/**
 * ConnectedIDs returns the set of currently-open connection IDs.
 */
export function ConnectedIDs(): $CancellablePromise<string[]> {
    return $Call.ByName("catdb/internal/services.ConnectionService.ConnectedIDs").then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DeleteConnection removes the profile, its secret, and closes any live
 * connection. Idempotent regarding secrets / live state.
 */
export function DeleteConnection(id: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.ConnectionService.DeleteConnection", id);
}

/**
 * DeleteGroup removes a group. Refuses non-empty groups
 * (storage.ErrGroupNotEmpty) — the user must move members elsewhere first.
 */
export function DeleteGroup(id: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.ConnectionService.DeleteGroup", id);
}

/**
 * Disconnect closes a live Connection. Idempotent.
 */
export function Disconnect(id: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.ConnectionService.Disconnect", id);
}

/**
 * GetConnection returns one profile (no secret).
 */
export function GetConnection(id: string): $CancellablePromise<storage$0.ConnectionProfile> {
    return $Call.ByName("catdb/internal/services.ConnectionService.GetConnection", id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetServerInfo returns runtime metadata (version, current user) for a live
 * Connection. Returns ErrNotOpen if the connection is not active.
 */
export function GetServerInfo(id: string): $CancellablePromise<dbdriver$0.ServerInfo> {
    return $Call.ByName("catdb/internal/services.ConnectionService.GetServerInfo", id).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * IsConnected reports whether a Connection is live.
 */
export function IsConnected(id: string): $CancellablePromise<boolean> {
    return $Call.ByName("catdb/internal/services.ConnectionService.IsConnected", id);
}

/**
 * ListConnections returns every saved profile (no secrets).
 */
export function ListConnections(): $CancellablePromise<storage$0.ConnectionProfile[]> {
    return $Call.ByName("catdb/internal/services.ConnectionService.ListConnections").then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListDrivers returns the set of registered drivers and their connection
 * schemas. The connection form is rendered from this data — no front-end
 * change is needed when a new driver lands.
 */
export function ListDrivers(): $CancellablePromise<$models.DriverInfo[]> {
    return $Call.ByName("catdb/internal/services.ConnectionService.ListDrivers").then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ListGroups returns the sidebar's folder list.
 */
export function ListGroups(): $CancellablePromise<storage$0.Group[]> {
    return $Call.ByName("catdb/internal/services.ConnectionService.ListGroups").then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * MoveConnection reassigns a connection to a different group, or detaches
 * it (groupID == "" → 未分组). Used by the sidebar's drag-to-group flow.
 * This is intentionally separate from SaveConnection so the move never
 * reads/writes secrets — only group_id changes.
 */
export function MoveConnection(id: string, groupID: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.ConnectionService.MoveConnection", id, groupID);
}

/**
 * Ping pings a live Connection.
 */
export function Ping(id: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.ConnectionService.Ping", id);
}

/**
 * SaveConnection upserts a profile and writes secrets to the keyring.
 * New profiles get a fresh UUID. Returns the persisted profile (with ID +
 * timestamps populated). Secrets are write-only: on edit, a blank password
 * field keeps the stored keyring value (same semantics as the AI provider
 * API key) — only a non-empty value overwrites.
 */
export function SaveConnection(d: $models.ConnectionDraft): $CancellablePromise<storage$0.ConnectionProfile> {
    return $Call.ByName("catdb/internal/services.ConnectionService.SaveConnection", d).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveGroup upserts a group.
 */
export function SaveGroup(g: storage$0.Group): $CancellablePromise<storage$0.Group> {
    return $Call.ByName("catdb/internal/services.ConnectionService.SaveGroup", g).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * TestConnection opens a Connection from the draft, calls Ping, and closes —
 * nothing is persisted. Used by the form's "Test" button. When editing an
 * existing profile, blank password fields fall back to the stored secrets so
 * the test matches what SaveConnection would persist.
 */
export function TestConnection(d: $models.ConnectionDraft): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.ConnectionService.TestConnection", d);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = storage$0.ConnectionProfile.createFrom;
const $$createType2 = dbdriver$0.ServerInfo.createFrom;
const $$createType3 = $Create.Array($$createType1);
const $$createType4 = $models.DriverInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = storage$0.Group.createFrom;
const $$createType7 = $Create.Array($$createType6);
