// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EditService is the IPC entry point for row-level editing on tables. The
 * Service stays thin: input validation + driver dispatch. The safety
 * invariants (no keyless writes, parameterized SQL) live in the driver's
 * Editor.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyChange executes a single RowChange via the driver's Editor. Returns
 * the SQL it issued so the front-end can show the user what really ran.
 */
export function ApplyChange(connID: string, ch: $models.RowChange): $CancellablePromise<$models.RowChangeResult> {
    return $Call.ByName("catdb/internal/services.EditService.ApplyChange", connID, ch).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetPrimaryKey returns the primary-key columns (or chosen unique key) for a
 * table. An empty result means the table is editable READ-ONLY: the front-end
 * hides the row-edit affordances and shows a banner.
 */
export function GetPrimaryKey(connID: string, db: string, table: string): $CancellablePromise<string[]> {
    return $Call.ByName("catdb/internal/services.EditService.GetPrimaryKey", connID, db, table).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.RowChangeResult.createFrom;
const $$createType1 = $Create.Array($Create.Any);
