// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MetadataService is the Wails Service that drives the object tree, the
 * structure viewer, and autocomplete. It stays THIN: validates input and
 * forwards to the driver's Metadata.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dbdriver$0 from "../dbdriver/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AutocompleteFor returns the table+column map for one database (tables first,
 * then views). Column fetching is capped to a generous-but-finite number of
 * relations so the IPC payload is bounded; relations past the cap fall back to
 * "name only, no columns" — better than nothing for completion.
 */
export function AutocompleteFor(connID: string, db: string, schema: string): $CancellablePromise<$models.AutocompleteSnapshot> {
    return $Call.ByName("catdb/internal/services.MetadataService.AutocompleteFor", connID, db, schema).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * BrowseTable runs `SELECT * FROM db.table [WHERE …] [ORDER BY …] LIMIT … OFFSET …`
 * and returns the rows + columns + primary-key info needed by the data browser.
 * 
 * Pass orderBy to request an ORDER BY clause (the column name is quoted via the
 * active Dialect). orderDir defaults to "ASC" when empty; valid values are
 * "ASC" and "DESC" (case-insensitive).
 * whereClause and orderByClause are raw SQL snippets injected directly after
 * WHERE and ORDER BY respectively — supplied by the FilterBar component.
 * When orderByClause is non-empty it takes precedence over the simple
 * orderBy/orderDir pair.
 * Pass limit < 0 to fetch all rows (no LIMIT/OFFSET clause). limit == 0 is
 * reserved as "use default" and resolves to 200.
 */
export function BrowseTable(connID: string, db: string, schema: string, table: string, orderBy: string, orderDir: string, limit: number, offset: number, whereClause: string, orderByClause: string): $CancellablePromise<$models.BrowseResult> {
    return $Call.ByName("catdb/internal/services.MetadataService.BrowseTable", connID, db, schema, table, orderBy, orderDir, limit, offset, whereClause, orderByClause).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * BuildAlterPlan diffs the draft against the original snapshot and renders
 * ALTER statements through the connection's Dialect.
 */
export function BuildAlterPlan(connID: string, req: $models.AlterPlanRequest): $CancellablePromise<$models.AlterPlanResult> {
    return $Call.ByName("catdb/internal/services.MetadataService.BuildAlterPlan", connID, req).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * BuildCreateTable renders a CREATE TABLE statement from a structure draft.
 * Mirrors the editor's preview contract: an empty table name or a draft with
 * no named columns yields "" (empty preview), not an error.
 */
export function BuildCreateTable(connID: string, req: $models.CreateTableRequest): $CancellablePromise<string> {
    return $Call.ByName("catdb/internal/services.MetadataService.BuildCreateTable", connID, req);
}

/**
 * CountTableRows runs `SELECT COUNT(*) FROM db.table [WHERE …]` so the data
 * browser can show the exact total on demand (it's a potentially slow scan,
 * hence user-triggered rather than automatic). whereClause is the same raw
 * FilterBar snippet BrowseTable accepts.
 */
export function CountTableRows(connID: string, db: string, schema: string, table: string, whereClause: string): $CancellablePromise<number> {
    return $Call.ByName("catdb/internal/services.MetadataService.CountTableRows", connID, db, schema, table, whereClause);
}

export function GetCreateTable(connID: string, db: string, schema: string, table: string): $CancellablePromise<string> {
    return $Call.ByName("catdb/internal/services.MetadataService.GetCreateTable", connID, db, schema, table);
}

export function GetTableSummary(connID: string, db: string, schema: string, table: string): $CancellablePromise<$models.TableSummary> {
    return $Call.ByName("catdb/internal/services.MetadataService.GetTableSummary", connID, db, schema, table).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListColumns(connID: string, db: string, schema: string, table: string): $CancellablePromise<dbdriver$0.ColumnMeta[]> {
    return $Call.ByName("catdb/internal/services.MetadataService.ListColumns", connID, db, schema, table).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ListDatabases(connID: string): $CancellablePromise<string[]> {
    return $Call.ByName("catdb/internal/services.MetadataService.ListDatabases", connID).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListForeignKeys(connID: string, db: string, schema: string, table: string): $CancellablePromise<dbdriver$0.ForeignKeyInfo[]> {
    return $Call.ByName("catdb/internal/services.MetadataService.ListForeignKeys", connID, db, schema, table).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ListIndexes(connID: string, db: string, schema: string, table: string): $CancellablePromise<dbdriver$0.IndexInfo[]> {
    return $Call.ByName("catdb/internal/services.MetadataService.ListIndexes", connID, db, schema, table).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ListRoutines(connID: string, db: string, schema: string): $CancellablePromise<dbdriver$0.RoutineInfo[]> {
    return $Call.ByName("catdb/internal/services.MetadataService.ListRoutines", connID, db, schema).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * ListSchemas returns the schemas under db. Empty for databases without a
 * schema level (Capabilities.Schemas == false, e.g. MySQL).
 */
export function ListSchemas(connID: string, db: string): $CancellablePromise<string[]> {
    return $Call.ByName("catdb/internal/services.MetadataService.ListSchemas", connID, db).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListTables(connID: string, db: string, schema: string): $CancellablePromise<dbdriver$0.TableInfo[]> {
    return $Call.ByName("catdb/internal/services.MetadataService.ListTables", connID, db, schema).then(($result: any) => {
        return $$createType14($result);
    });
}

export function ListViews(connID: string, db: string, schema: string): $CancellablePromise<dbdriver$0.ViewInfo[]> {
    return $Call.ByName("catdb/internal/services.MetadataService.ListViews", connID, db, schema).then(($result: any) => {
        return $$createType16($result);
    });
}

// Private type creation functions
const $$createType0 = $models.AutocompleteSnapshot.createFrom;
const $$createType1 = $models.BrowseResult.createFrom;
const $$createType2 = $models.AlterPlanResult.createFrom;
const $$createType3 = $models.TableSummary.createFrom;
const $$createType4 = dbdriver$0.ColumnMeta.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = dbdriver$0.ForeignKeyInfo.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = dbdriver$0.IndexInfo.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = dbdriver$0.RoutineInfo.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = dbdriver$0.TableInfo.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = dbdriver$0.ViewInfo.createFrom;
const $$createType16 = $Create.Array($$createType15);
