// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MetadataService is the Wails Service that drives the object tree, the
 * structure viewer, and autocomplete. It stays THIN: validates input and
 * forwards to the driver's Metadata.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dbdriver$0 from "../dbdriver/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AutocompleteFor returns the table+column map for one database. Capped to a
 * generous-but-finite number of tables so the IPC payload is bounded; tables
 * past the cap fall back to "table name only, no columns" — better than
 * nothing for completion.
 */
export function AutocompleteFor(connID: string, db: string): $CancellablePromise<$models.AutocompleteSnapshot> {
    return $Call.ByName("catdb/internal/services.MetadataService.AutocompleteFor", connID, db).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * BrowseTable runs `SELECT * FROM db.table ORDER BY … LIMIT … OFFSET …` and
 * returns the rows + columns + primary-key info needed by the data browser.
 * 
 * Pass orderBy to request an ORDER BY clause (the column name is quoted via the
 * active Dialect). orderDir defaults to "ASC" when empty; valid values are
 * "ASC" and "DESC" (case-insensitive).
 * Pass limit < 0 to fetch all rows (no LIMIT/OFFSET clause). limit == 0 is
 * reserved as "use default" and resolves to 200.
 */
export function BrowseTable(connID: string, db: string, table: string, orderBy: string, orderDir: string, limit: number, offset: number): $CancellablePromise<$models.BrowseResult> {
    return $Call.ByName("catdb/internal/services.MetadataService.BrowseTable", connID, db, table, orderBy, orderDir, limit, offset).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetCreateTable(connID: string, db: string, table: string): $CancellablePromise<string> {
    return $Call.ByName("catdb/internal/services.MetadataService.GetCreateTable", connID, db, table);
}

export function GetTableSummary(connID: string, db: string, table: string): $CancellablePromise<$models.TableSummary> {
    return $Call.ByName("catdb/internal/services.MetadataService.GetTableSummary", connID, db, table).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListColumns(connID: string, db: string, table: string): $CancellablePromise<dbdriver$0.ColumnMeta[]> {
    return $Call.ByName("catdb/internal/services.MetadataService.ListColumns", connID, db, table).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ListDatabases(connID: string): $CancellablePromise<string[]> {
    return $Call.ByName("catdb/internal/services.MetadataService.ListDatabases", connID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ListForeignKeys(connID: string, db: string, table: string): $CancellablePromise<dbdriver$0.ForeignKeyInfo[]> {
    return $Call.ByName("catdb/internal/services.MetadataService.ListForeignKeys", connID, db, table).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ListIndexes(connID: string, db: string, table: string): $CancellablePromise<dbdriver$0.IndexInfo[]> {
    return $Call.ByName("catdb/internal/services.MetadataService.ListIndexes", connID, db, table).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ListRoutines(connID: string, db: string): $CancellablePromise<dbdriver$0.RoutineInfo[]> {
    return $Call.ByName("catdb/internal/services.MetadataService.ListRoutines", connID, db).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ListTables(connID: string, db: string): $CancellablePromise<dbdriver$0.TableInfo[]> {
    return $Call.ByName("catdb/internal/services.MetadataService.ListTables", connID, db).then(($result: any) => {
        return $$createType13($result);
    });
}

export function ListViews(connID: string, db: string): $CancellablePromise<dbdriver$0.ViewInfo[]> {
    return $Call.ByName("catdb/internal/services.MetadataService.ListViews", connID, db).then(($result: any) => {
        return $$createType15($result);
    });
}

// Private type creation functions
const $$createType0 = $models.AutocompleteSnapshot.createFrom;
const $$createType1 = $models.BrowseResult.createFrom;
const $$createType2 = $models.TableSummary.createFrom;
const $$createType3 = dbdriver$0.ColumnMeta.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = dbdriver$0.ForeignKeyInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = dbdriver$0.IndexInfo.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = dbdriver$0.RoutineInfo.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = dbdriver$0.TableInfo.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = dbdriver$0.ViewInfo.createFrom;
const $$createType15 = $Create.Array($$createType14);
