// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dbdriver$0 from "../dbdriver/models.js";

/**
 * AutocompleteSnapshot is the cache the front-end hands to CodeMirror's
 * schemaCompletionSource. We ship it as one big map per refresh — small in
 * practice and cleaner than incremental updates.
 */
export class AutocompleteSnapshot {
    "database": string;
    "tables": AutocompleteTable[];

    /** Creates a new AutocompleteSnapshot instance. */
    constructor($$source: Partial<AutocompleteSnapshot> = {}) {
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("tables" in $$source)) {
            this["tables"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AutocompleteSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): AutocompleteSnapshot {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField1_0($$parsedSource["tables"]);
        }
        return new AutocompleteSnapshot($$parsedSource as Partial<AutocompleteSnapshot>);
    }
}

export class AutocompleteTable {
    "name": string;
    "columns": string[];

    /** Creates a new AutocompleteTable instance. */
    constructor($$source: Partial<AutocompleteTable> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AutocompleteTable instance from a string or object.
     */
    static createFrom($$source: any = {}): AutocompleteTable {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField1_0($$parsedSource["columns"]);
        }
        return new AutocompleteTable($$parsedSource as Partial<AutocompleteTable>);
    }
}

/**
 * BrowseResult is the one-shot pageful BrowseTable returns.
 */
export class BrowseResult {
    "columns": dbdriver$0.ColumnMeta[];
    "rows": any[][];
    "primaryKey": string[];
    "hasUniqueKey": boolean;

    /** Creates a new BrowseResult instance. */
    constructor($$source: Partial<BrowseResult> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("primaryKey" in $$source)) {
            this["primaryKey"] = [];
        }
        if (!("hasUniqueKey" in $$source)) {
            this["hasUniqueKey"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrowseResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BrowseResult {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType6;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        if ("primaryKey" in $$parsedSource) {
            $$parsedSource["primaryKey"] = $$createField2_0($$parsedSource["primaryKey"]);
        }
        return new BrowseResult($$parsedSource as Partial<BrowseResult>);
    }
}

/**
 * ConnectionDraft is what the front-end sends to Save/Test. Secrets are
 * passed via dedicated fields so we never persist them into the SQLite blob.
 */
export class ConnectionDraft {
    "id"?: string;
    "name": string;
    "driver": string;
    "groupId"?: string;
    "host": string;
    "port": number;
    "user": string;
    "database"?: string;
    "params"?: { [_ in string]?: string };
    "ssl"?: dbdriver$0.SSLConfig | null;
    "sshTunnel"?: dbdriver$0.SSHConfig | null;
    "password"?: string;
    "sshPassword"?: string;
    "sshKeyPassword"?: string;

    /** Creates a new ConnectionDraft instance. */
    constructor($$source: Partial<ConnectionDraft> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("driver" in $$source)) {
            this["driver"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionDraft instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionDraft {
        const $$createField8_0 = $$createType7;
        const $$createField9_0 = $$createType9;
        const $$createField10_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField8_0($$parsedSource["params"]);
        }
        if ("ssl" in $$parsedSource) {
            $$parsedSource["ssl"] = $$createField9_0($$parsedSource["ssl"]);
        }
        if ("sshTunnel" in $$parsedSource) {
            $$parsedSource["sshTunnel"] = $$createField10_0($$parsedSource["sshTunnel"]);
        }
        return new ConnectionDraft($$parsedSource as Partial<ConnectionDraft>);
    }
}

/**
 * DriverInfo describes one registered driver to the front-end.
 */
export class DriverInfo {
    "name": string;
    "version": string;
    "capabilities": dbdriver$0.Capabilities;
    "schema": dbdriver$0.ConnParamField[];

    /** Creates a new DriverInfo instance. */
    constructor($$source: Partial<DriverInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("capabilities" in $$source)) {
            this["capabilities"] = (new dbdriver$0.Capabilities());
        }
        if (!("schema" in $$source)) {
            this["schema"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DriverInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DriverInfo {
        const $$createField2_0 = $$createType12;
        const $$createField3_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField2_0($$parsedSource["capabilities"]);
        }
        if ("schema" in $$parsedSource) {
            $$parsedSource["schema"] = $$createField3_0($$parsedSource["schema"]);
        }
        return new DriverInfo($$parsedSource as Partial<DriverInfo>);
    }
}

/**
 * ExportOptions is what the front-end sends to ExportQuery.
 */
export class ExportOptions {
    "format": TransferFormat;
    "path": string;
    "batchSize"?: number;

    /**
     * CSV: write column row
     */
    "includeHeader"?: boolean;

    /**
     * SQL: include CREATE TABLE (single-table exports only)
     */
    "includeDDL"?: boolean;

    /**
     * SQL: target table name for INSERTs
     */
    "tableName"?: string;

    /** Creates a new ExportOptions instance. */
    constructor($$source: Partial<ExportOptions> = {}) {
        if (!("format" in $$source)) {
            this["format"] = TransferFormat.$zero;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportOptions($$parsedSource as Partial<ExportOptions>);
    }
}

/**
 * ExportResult is the synchronous return — progress events still fire during.
 */
export class ExportResult {
    "transferId": string;
    "path": string;
    "rowsTotal": number;
    "bytesTotal": number;
    "elapsedMs": number;

    /** Creates a new ExportResult instance. */
    constructor($$source: Partial<ExportResult> = {}) {
        if (!("transferId" in $$source)) {
            this["transferId"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("rowsTotal" in $$source)) {
            this["rowsTotal"] = 0;
        }
        if (!("bytesTotal" in $$source)) {
            this["bytesTotal"] = 0;
        }
        if (!("elapsedMs" in $$source)) {
            this["elapsedMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportResult($$parsedSource as Partial<ExportResult>);
    }
}

/**
 * FileFilterDescriptor is the JSON-shaped filter the front-end sends.
 */
export class FileFilterDescriptor {
    "displayName": string;
    "pattern": string;

    /** Creates a new FileFilterDescriptor instance. */
    constructor($$source: Partial<FileFilterDescriptor> = {}) {
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("pattern" in $$source)) {
            this["pattern"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileFilterDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): FileFilterDescriptor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileFilterDescriptor($$parsedSource as Partial<FileFilterDescriptor>);
    }
}

/**
 * ImportFormat enumerates the supported import file types. Same string values
 * the front-end uses (matched by lower-case).
 */
export enum ImportFormat {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ImportCSV = "csv",
    ImportSQL = "sql",
};

/**
 * ImportOptions describes how to ingest a local file into a connection.
 * 
 * For CSV:
 *   - HasHeader=true uses the first row as column names; otherwise Columns
 *     must be provided.
 *   - Each non-empty row becomes one INSERT.
 * 
 * For SQL:
 *   - The file is read as a series of statements separated by ';'.
 *   - Pure -- line comments are stripped; block comments / inline -- are left
 *     to the server (which handles them correctly).
 */
export class ImportOptions {
    "format": ImportFormat;
    "path": string;
    "db"?: string;

    /**
     * CSV only
     */
    "table"?: string;
    "hasHeader"?: boolean;

    /**
     * CSV only when HasHeader=false
     */
    "columns"?: string[];
    "delimiter"?: string;
    "batchSize"?: number;

    /** Creates a new ImportOptions instance. */
    constructor($$source: Partial<ImportOptions> = {}) {
        if (!("format" in $$source)) {
            this["format"] = ImportFormat.$zero;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportOptions {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField5_0($$parsedSource["columns"]);
        }
        return new ImportOptions($$parsedSource as Partial<ImportOptions>);
    }
}

/**
 * ImportResult mirrors ExportResult.
 */
export class ImportResult {
    "transferId": string;
    "rowsAffected": number;
    "statementsRun": number;
    "elapsedMs": number;

    /** Creates a new ImportResult instance. */
    constructor($$source: Partial<ImportResult> = {}) {
        if (!("transferId" in $$source)) {
            this["transferId"] = "";
        }
        if (!("rowsAffected" in $$source)) {
            this["rowsAffected"] = 0;
        }
        if (!("statementsRun" in $$source)) {
            this["statementsRun"] = 0;
        }
        if (!("elapsedMs" in $$source)) {
            this["elapsedMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportResult($$parsedSource as Partial<ImportResult>);
    }
}

/**
 * QueryBatchResult is what FetchMore returns.
 */
export class QueryBatchResult {
    "rows": any[][];
    "rowsTotal": number;
    "done": boolean;
    "truncated": boolean;

    /** Creates a new QueryBatchResult instance. */
    constructor($$source: Partial<QueryBatchResult> = {}) {
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("rowsTotal" in $$source)) {
            this["rowsTotal"] = 0;
        }
        if (!("done" in $$source)) {
            this["done"] = false;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryBatchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryBatchResult {
        const $$createField0_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField0_0($$parsedSource["rows"]);
        }
        return new QueryBatchResult($$parsedSource as Partial<QueryBatchResult>);
    }
}

/**
 * QueryOptions tweaks one call's behaviour. All fields optional.
 */
export class QueryOptions {
    /**
     * first-batch size (default 500)
     */
    "batchSize"?: number;

    /**
     * per-call ctx timeout (default 60s)
     */
    "timeoutMs"?: number;

    /**
     * hard cap for the open handle (default MaxPreviewRows)
     */
    "maxRows"?: number;

    /** Creates a new QueryOptions instance. */
    constructor($$source: Partial<QueryOptions> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueryOptions($$parsedSource as Partial<QueryOptions>);
    }
}

/**
 * QueryRunResult is what RunQuery / Explain return to the front-end.
 * 
 * - When Done=true, Handle is empty (the result fit in one batch); the
 *   front-end need not call FetchMore or Close.
 * - When Done=false, Handle is non-empty and the front-end must eventually
 *   call Close to release the cursor.
 */
export class QueryRunResult {
    "handle"?: string;
    "columns": dbdriver$0.ColumnMeta[];
    "rows": any[][];

    /**
     * running total of rows returned so far
     */
    "rowsTotal": number;
    "done": boolean;

    /**
     * hit MaxRows; cursor closed
     */
    "truncated": boolean;
    "elapsedMs": number;

    /**
     * IsResultSet=true means the SQL returned rows. False means it was an
     * Exec-style statement and the caller should look at ExecResult instead.
     */
    "isResultSet": boolean;
    "execResult"?: dbdriver$0.ExecResult | null;

    /** Creates a new QueryRunResult instance. */
    constructor($$source: Partial<QueryRunResult> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("rowsTotal" in $$source)) {
            this["rowsTotal"] = 0;
        }
        if (!("done" in $$source)) {
            this["done"] = false;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }
        if (!("elapsedMs" in $$source)) {
            this["elapsedMs"] = 0;
        }
        if (!("isResultSet" in $$source)) {
            this["isResultSet"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryRunResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryRunResult {
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType6;
        const $$createField8_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField1_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField2_0($$parsedSource["rows"]);
        }
        if ("execResult" in $$parsedSource) {
            $$parsedSource["execResult"] = $$createField8_0($$parsedSource["execResult"]);
        }
        return new QueryRunResult($$parsedSource as Partial<QueryRunResult>);
    }
}

/**
 * RowChange is the front-end's request to mutate one row.
 * 
 * Op selects the operation:
 * 
 * 	"insert" — uses Values, ignores PK.
 * 	"update" — uses PK to locate the row, Values are the new column values.
 * 	"delete" — uses PK only.
 * 
 * PK must match the columns reported by GetPrimaryKey; the driver enforces
 * "no keyless UPDATE/DELETE" by refusing an empty pk map.
 */
export class RowChange {
    "op": string;
    "db": string;
    "table": string;
    "pk"?: { [_ in string]?: any };
    "values"?: { [_ in string]?: any };

    /** Creates a new RowChange instance. */
    constructor($$source: Partial<RowChange> = {}) {
        if (!("op" in $$source)) {
            this["op"] = "";
        }
        if (!("db" in $$source)) {
            this["db"] = "";
        }
        if (!("table" in $$source)) {
            this["table"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RowChange instance from a string or object.
     */
    static createFrom($$source: any = {}): RowChange {
        const $$createField3_0 = $$createType17;
        const $$createField4_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pk" in $$parsedSource) {
            $$parsedSource["pk"] = $$createField3_0($$parsedSource["pk"]);
        }
        if ("values" in $$parsedSource) {
            $$parsedSource["values"] = $$createField4_0($$parsedSource["values"]);
        }
        return new RowChange($$parsedSource as Partial<RowChange>);
    }
}

/**
 * RowChangeResult reports what the driver did. RowsAffected==0 on UPDATE/
 * DELETE is the front-end's "stale row" signal (optimistic-lock loss).
 */
export class RowChangeResult {
    "rowsAffected": number;
    "lastInsertId"?: number;

    /**
     * the rendered SQL, for the editor's "history" panel
     */
    "sql": string;

    /** Creates a new RowChangeResult instance. */
    constructor($$source: Partial<RowChangeResult> = {}) {
        if (!("rowsAffected" in $$source)) {
            this["rowsAffected"] = 0;
        }
        if (!("sql" in $$source)) {
            this["sql"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RowChangeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): RowChangeResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RowChangeResult($$parsedSource as Partial<RowChangeResult>);
    }
}

/**
 * TableSummary bundles columns/indexes/FKs into one round-trip — handy for
 * the structure viewer so it can render the whole panel without sequencing
 * three calls from the front-end.
 */
export class TableSummary {
    "columns": dbdriver$0.ColumnMeta[];
    "indexes": dbdriver$0.IndexInfo[];
    "foreignKeys": dbdriver$0.ForeignKeyInfo[];

    /** Creates a new TableSummary instance. */
    constructor($$source: Partial<TableSummary> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("indexes" in $$source)) {
            this["indexes"] = [];
        }
        if (!("foreignKeys" in $$source)) {
            this["foreignKeys"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): TableSummary {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType19;
        const $$createField2_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("indexes" in $$parsedSource) {
            $$parsedSource["indexes"] = $$createField1_0($$parsedSource["indexes"]);
        }
        if ("foreignKeys" in $$parsedSource) {
            $$parsedSource["foreignKeys"] = $$createField2_0($$parsedSource["foreignKeys"]);
        }
        return new TableSummary($$parsedSource as Partial<TableSummary>);
    }
}

/**
 * TransferFormat enumerates the supported file types. Strings match
 * front-end identifiers and the file extension we expect.
 */
export enum TransferFormat {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FormatCSV = "csv",
    FormatJSON = "json",
    FormatSQL = "sql",
    FormatXLSX = "xlsx",
};

// Private type creation functions
const $$createType0 = AutocompleteTable.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = dbdriver$0.ColumnMeta.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Map($Create.Any, $Create.Any);
const $$createType8 = dbdriver$0.SSLConfig.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = dbdriver$0.SSHConfig.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = dbdriver$0.Capabilities.createFrom;
const $$createType13 = dbdriver$0.ConnParamField.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = dbdriver$0.ExecResult.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = $Create.Map($Create.Any, $Create.Any);
const $$createType18 = dbdriver$0.IndexInfo.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = dbdriver$0.ForeignKeyInfo.createFrom;
const $$createType21 = $Create.Array($$createType20);
