// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as datasync$0 from "../core/datasync/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as schemadiff$0 from "../core/schemadiff/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dbdriver$0 from "../dbdriver/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";

/**
 * AgentDefaults is the persisted default Provider instance + model.
 */
export class AgentDefaults {
    "providerId": string;
    "model": string;

    /** Creates a new AgentDefaults instance. */
    constructor($$source: Partial<AgentDefaults> = {}) {
        if (!("providerId" in $$source)) {
            this["providerId"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentDefaults instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentDefaults {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentDefaults($$parsedSource as Partial<AgentDefaults>);
    }
}

/**
 * AlterPlanRequest carries the original table snapshot (what the structure
 * editor loaded) and the user-edited draft. The diff runs backend-side in
 * internal/core/schemadiff; the connection is only consulted for its Dialect,
 * so this is a pure computation — no queries hit the database.
 */
export class AlterPlanRequest {
    "db": string;
    "schema": string;
    "table": string;
    "orig": TableSummary;
    "origComment": string;
    "draft": schemadiff$0.Table;

    /** Creates a new AlterPlanRequest instance. */
    constructor($$source: Partial<AlterPlanRequest> = {}) {
        if (!("db" in $$source)) {
            this["db"] = "";
        }
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("table" in $$source)) {
            this["table"] = "";
        }
        if (!("orig" in $$source)) {
            this["orig"] = (new TableSummary());
        }
        if (!("origComment" in $$source)) {
            this["origComment"] = "";
        }
        if (!("draft" in $$source)) {
            this["draft"] = (new schemadiff$0.Table());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AlterPlanRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AlterPlanRequest {
        const $$createField3_0 = $$createType0;
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("orig" in $$parsedSource) {
            $$parsedSource["orig"] = $$createField3_0($$parsedSource["orig"]);
        }
        if ("draft" in $$parsedSource) {
            $$parsedSource["draft"] = $$createField5_0($$parsedSource["draft"]);
        }
        return new AlterPlanRequest($$parsedSource as Partial<AlterPlanRequest>);
    }
}

/**
 * AlterPlanResult groups the generated ALTER statements by structure-editor
 * tab, plus the concatenation in safe execution order.
 */
export class AlterPlanResult {
    "columns": string[];
    "indexes": string[];
    "foreignKeys": string[];
    "options": string[];
    "all": string[];

    /** Creates a new AlterPlanResult instance. */
    constructor($$source: Partial<AlterPlanResult> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("indexes" in $$source)) {
            this["indexes"] = [];
        }
        if (!("foreignKeys" in $$source)) {
            this["foreignKeys"] = [];
        }
        if (!("options" in $$source)) {
            this["options"] = [];
        }
        if (!("all" in $$source)) {
            this["all"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AlterPlanResult instance from a string or object.
     */
    static createFrom($$source: any = {}): AlterPlanResult {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("indexes" in $$parsedSource) {
            $$parsedSource["indexes"] = $$createField1_0($$parsedSource["indexes"]);
        }
        if ("foreignKeys" in $$parsedSource) {
            $$parsedSource["foreignKeys"] = $$createField2_0($$parsedSource["foreignKeys"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField3_0($$parsedSource["options"]);
        }
        if ("all" in $$parsedSource) {
            $$parsedSource["all"] = $$createField4_0($$parsedSource["all"]);
        }
        return new AlterPlanResult($$parsedSource as Partial<AlterPlanResult>);
    }
}

/**
 * AuditExportResult is the synchronous return of ExportAudit.
 */
export class AuditExportResult {
    "path": string;
    "rows": number;

    /** Creates a new AuditExportResult instance. */
    constructor($$source: Partial<AuditExportResult> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuditExportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): AuditExportResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuditExportResult($$parsedSource as Partial<AuditExportResult>);
    }
}

/**
 * AuditPage is one page of audit entries plus whether more exist after it.
 */
export class AuditPage {
    "entries": storage$0.AgentAuditEntry[];
    "hasMore": boolean;

    /** Creates a new AuditPage instance. */
    constructor($$source: Partial<AuditPage> = {}) {
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }
        if (!("hasMore" in $$source)) {
            this["hasMore"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuditPage instance from a string or object.
     */
    static createFrom($$source: any = {}): AuditPage {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField0_0($$parsedSource["entries"]);
        }
        return new AuditPage($$parsedSource as Partial<AuditPage>);
    }
}

/**
 * AuditQuery scopes ListAudit / ExportAudit. SinceUnix/UntilUnix are
 * epoch-seconds bounds (0 = unbounded). Offset+Limit paginate the (most-recent-
 * first) result; storage itself has no OFFSET, so the service over-fetches and
 * slices — audit is small local data, so this stays cheap.
 */
export class AuditQuery {
    "connId": string;
    "sessionId": string;
    "sinceUnix": number;
    "untilUnix": number;
    "limit": number;
    "offset": number;

    /** Creates a new AuditQuery instance. */
    constructor($$source: Partial<AuditQuery> = {}) {
        if (!("connId" in $$source)) {
            this["connId"] = "";
        }
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("sinceUnix" in $$source)) {
            this["sinceUnix"] = 0;
        }
        if (!("untilUnix" in $$source)) {
            this["untilUnix"] = 0;
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuditQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): AuditQuery {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuditQuery($$parsedSource as Partial<AuditQuery>);
    }
}

/**
 * AutocompleteColumn carries the per-column detail the editor shows in the
 * completion popup: native type (e.g. "VARCHAR(255)"), primary-key membership,
 * NOT NULL, and the column comment.
 */
export class AutocompleteColumn {
    "name": string;
    "type": string;
    "pk"?: boolean;
    "notNull"?: boolean;
    "comment"?: string;

    /** Creates a new AutocompleteColumn instance. */
    constructor($$source: Partial<AutocompleteColumn> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AutocompleteColumn instance from a string or object.
     */
    static createFrom($$source: any = {}): AutocompleteColumn {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AutocompleteColumn($$parsedSource as Partial<AutocompleteColumn>);
    }
}

/**
 * AutocompleteSnapshot is the cache the front-end hands to CodeMirror's
 * schemaCompletionSource. We ship it as one big map per refresh — small in
 * practice and cleaner than incremental updates.
 */
export class AutocompleteSnapshot {
    "database": string;
    "tables": AutocompleteTable[];

    /** Creates a new AutocompleteSnapshot instance. */
    constructor($$source: Partial<AutocompleteSnapshot> = {}) {
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("tables" in $$source)) {
            this["tables"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AutocompleteSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): AutocompleteSnapshot {
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField1_0($$parsedSource["tables"]);
        }
        return new AutocompleteSnapshot($$parsedSource as Partial<AutocompleteSnapshot>);
    }
}

export class AutocompleteTable {
    "name": string;

    /**
     * Kind is "table" or "view" — lets the editor render a distinct icon and
     * treat views as query-able relations in completion.
     */
    "kind": string;
    "columns": AutocompleteColumn[];

    /** Creates a new AutocompleteTable instance. */
    constructor($$source: Partial<AutocompleteTable> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AutocompleteTable instance from a string or object.
     */
    static createFrom($$source: any = {}): AutocompleteTable {
        const $$createField2_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField2_0($$parsedSource["columns"]);
        }
        return new AutocompleteTable($$parsedSource as Partial<AutocompleteTable>);
    }
}

/**
 * BrowseResult is the one-shot pageful BrowseTable returns.
 */
export class BrowseResult {
    "columns": dbdriver$0.ColumnMeta[];
    "rows": any[][];
    "primaryKey": string[];
    "hasUniqueKey": boolean;

    /**
     * SQL is the dialect-paginated statement that actually ran. Surfaced to
     * the UI so users can see/copy what catdb executed on their behalf.
     */
    "sql": string;

    /** Creates a new BrowseResult instance. */
    constructor($$source: Partial<BrowseResult> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("primaryKey" in $$source)) {
            this["primaryKey"] = [];
        }
        if (!("hasUniqueKey" in $$source)) {
            this["hasUniqueKey"] = false;
        }
        if (!("sql" in $$source)) {
            this["sql"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrowseResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BrowseResult {
        const $$createField0_0 = $$createType10;
        const $$createField1_0 = $$createType12;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        if ("primaryKey" in $$parsedSource) {
            $$parsedSource["primaryKey"] = $$createField2_0($$parsedSource["primaryKey"]);
        }
        return new BrowseResult($$parsedSource as Partial<BrowseResult>);
    }
}

/**
 * ConnectionDraft is what the front-end sends to Save/Test. Secrets are
 * passed via dedicated fields so we never persist them into the SQLite blob.
 */
export class ConnectionDraft {
    "id"?: string;
    "name": string;
    "driver": string;
    "groupId"?: string;
    "environment"?: string;
    "host": string;
    "port": number;
    "user": string;
    "database"?: string;
    "params"?: { [_ in string]?: string };
    "ssl"?: dbdriver$0.SSLConfig | null;
    "sshTunnel"?: dbdriver$0.SSHConfig | null;
    "password"?: string;
    "sshPassword"?: string;
    "sshKeyPassword"?: string;

    /** Creates a new ConnectionDraft instance. */
    constructor($$source: Partial<ConnectionDraft> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("driver" in $$source)) {
            this["driver"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionDraft instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionDraft {
        const $$createField9_0 = $$createType13;
        const $$createField10_0 = $$createType15;
        const $$createField11_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField9_0($$parsedSource["params"]);
        }
        if ("ssl" in $$parsedSource) {
            $$parsedSource["ssl"] = $$createField10_0($$parsedSource["ssl"]);
        }
        if ("sshTunnel" in $$parsedSource) {
            $$parsedSource["sshTunnel"] = $$createField11_0($$parsedSource["sshTunnel"]);
        }
        return new ConnectionDraft($$parsedSource as Partial<ConnectionDraft>);
    }
}

/**
 * CreateTableRequest is the "new table" flow's draft.
 */
export class CreateTableRequest {
    "db": string;
    "schema": string;
    "table": string;
    "draft": schemadiff$0.Table;

    /** Creates a new CreateTableRequest instance. */
    constructor($$source: Partial<CreateTableRequest> = {}) {
        if (!("db" in $$source)) {
            this["db"] = "";
        }
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("table" in $$source)) {
            this["table"] = "";
        }
        if (!("draft" in $$source)) {
            this["draft"] = (new schemadiff$0.Table());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateTableRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateTableRequest {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("draft" in $$parsedSource) {
            $$parsedSource["draft"] = $$createField3_0($$parsedSource["draft"]);
        }
        return new CreateTableRequest($$parsedSource as Partial<CreateTableRequest>);
    }
}

/**
 * DataCompareRequest names the two databases and (optionally) the tables to
 * compare. Empty Tables = every table present on both sides.
 */
export class DataCompareRequest {
    "sourceConnId": string;
    "sourceDb": string;
    "sourceSchema": string;
    "targetConnId": string;
    "targetDb": string;
    "targetSchema": string;
    "tables": string[];
    "batchSize": number;

    /** Creates a new DataCompareRequest instance. */
    constructor($$source: Partial<DataCompareRequest> = {}) {
        if (!("sourceConnId" in $$source)) {
            this["sourceConnId"] = "";
        }
        if (!("sourceDb" in $$source)) {
            this["sourceDb"] = "";
        }
        if (!("sourceSchema" in $$source)) {
            this["sourceSchema"] = "";
        }
        if (!("targetConnId" in $$source)) {
            this["targetConnId"] = "";
        }
        if (!("targetDb" in $$source)) {
            this["targetDb"] = "";
        }
        if (!("targetSchema" in $$source)) {
            this["targetSchema"] = "";
        }
        if (!("tables" in $$source)) {
            this["tables"] = [];
        }
        if (!("batchSize" in $$source)) {
            this["batchSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataCompareRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DataCompareRequest {
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField6_0($$parsedSource["tables"]);
        }
        return new DataCompareRequest($$parsedSource as Partial<DataCompareRequest>);
    }
}

/**
 * DataCompareResult is the per-table outcome list, in name order.
 */
export class DataCompareResult {
    "syncId": string;
    "tables": DataTableDiff[];

    /** Creates a new DataCompareResult instance. */
    constructor($$source: Partial<DataCompareResult> = {}) {
        if (!("syncId" in $$source)) {
            this["syncId"] = "";
        }
        if (!("tables" in $$source)) {
            this["tables"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataCompareResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DataCompareResult {
        const $$createField1_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField1_0($$parsedSource["tables"]);
        }
        return new DataCompareResult($$parsedSource as Partial<DataCompareResult>);
    }
}

/**
 * DataSyncExecRequest executes the differences for the listed tables.
 * AllowDelete gates DELETE of target-only rows (default false = keep them).
 */
export class DataSyncExecRequest {
    "sourceConnId": string;
    "sourceDb": string;
    "sourceSchema": string;
    "targetConnId": string;
    "targetDb": string;
    "targetSchema": string;
    "tables": string[];
    "allowDelete": boolean;
    "batchSize": number;

    /** Creates a new DataSyncExecRequest instance. */
    constructor($$source: Partial<DataSyncExecRequest> = {}) {
        if (!("sourceConnId" in $$source)) {
            this["sourceConnId"] = "";
        }
        if (!("sourceDb" in $$source)) {
            this["sourceDb"] = "";
        }
        if (!("sourceSchema" in $$source)) {
            this["sourceSchema"] = "";
        }
        if (!("targetConnId" in $$source)) {
            this["targetConnId"] = "";
        }
        if (!("targetDb" in $$source)) {
            this["targetDb"] = "";
        }
        if (!("targetSchema" in $$source)) {
            this["targetSchema"] = "";
        }
        if (!("tables" in $$source)) {
            this["tables"] = [];
        }
        if (!("allowDelete" in $$source)) {
            this["allowDelete"] = false;
        }
        if (!("batchSize" in $$source)) {
            this["batchSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataSyncExecRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DataSyncExecRequest {
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField6_0($$parsedSource["tables"]);
        }
        return new DataSyncExecRequest($$parsedSource as Partial<DataSyncExecRequest>);
    }
}

/**
 * DataSyncExecResult mirrors DataCompareResult for the write pass.
 */
export class DataSyncExecResult {
    "syncId": string;
    "tables": DataTableDiff[];

    /** Creates a new DataSyncExecResult instance. */
    constructor($$source: Partial<DataSyncExecResult> = {}) {
        if (!("syncId" in $$source)) {
            this["syncId"] = "";
        }
        if (!("tables" in $$source)) {
            this["tables"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataSyncExecResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DataSyncExecResult {
        const $$createField1_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField1_0($$parsedSource["tables"]);
        }
        return new DataSyncExecResult($$parsedSource as Partial<DataSyncExecResult>);
    }
}

/**
 * DataTableDiff is one table's compare/execute outcome. Skipped carries a
 * stable slug the front-end localizes; Samples is a bounded preview.
 */
export class DataTableDiff {
    "table": string;
    "inserts": number;
    "updates": number;
    "deletes": number;
    "scannedSource": number;
    "scannedTarget": number;
    "samples"?: datasync$0.DiffSample[];

    /**
     * no-primary-key | pk-mismatch | missing-on-target | no-common-columns
     */
    "skipped"?: string;
    "error"?: string;

    /** Creates a new DataTableDiff instance. */
    constructor($$source: Partial<DataTableDiff> = {}) {
        if (!("table" in $$source)) {
            this["table"] = "";
        }
        if (!("inserts" in $$source)) {
            this["inserts"] = 0;
        }
        if (!("updates" in $$source)) {
            this["updates"] = 0;
        }
        if (!("deletes" in $$source)) {
            this["deletes"] = 0;
        }
        if (!("scannedSource" in $$source)) {
            this["scannedSource"] = 0;
        }
        if (!("scannedTarget" in $$source)) {
            this["scannedTarget"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataTableDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): DataTableDiff {
        const $$createField6_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("samples" in $$parsedSource) {
            $$parsedSource["samples"] = $$createField6_0($$parsedSource["samples"]);
        }
        return new DataTableDiff($$parsedSource as Partial<DataTableDiff>);
    }
}

/**
 * DataTransferRequest is what the front-end sends to StartTransfer.
 */
export class DataTransferRequest {
    "sourceConnId": string;
    "sourceDb": string;
    "sourceSchema"?: string;
    "targetConnId": string;
    "targetDb": string;
    "targetSchema"?: string;
    "tables": string[];
    "createTable": boolean;

    /**
     * "append" or "overwrite"
     */
    "transferMode": string;
    "batchSize": number;

    /** Creates a new DataTransferRequest instance. */
    constructor($$source: Partial<DataTransferRequest> = {}) {
        if (!("sourceConnId" in $$source)) {
            this["sourceConnId"] = "";
        }
        if (!("sourceDb" in $$source)) {
            this["sourceDb"] = "";
        }
        if (!("targetConnId" in $$source)) {
            this["targetConnId"] = "";
        }
        if (!("targetDb" in $$source)) {
            this["targetDb"] = "";
        }
        if (!("tables" in $$source)) {
            this["tables"] = [];
        }
        if (!("createTable" in $$source)) {
            this["createTable"] = false;
        }
        if (!("transferMode" in $$source)) {
            this["transferMode"] = "";
        }
        if (!("batchSize" in $$source)) {
            this["batchSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataTransferRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DataTransferRequest {
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField6_0($$parsedSource["tables"]);
        }
        return new DataTransferRequest($$parsedSource as Partial<DataTransferRequest>);
    }
}

/**
 * DataTransferResult is returned once all tables have been processed (or on
 * first fatal error — partial results are still returned so the UI can show
 * what made it through).
 */
export class DataTransferResult {
    "transferId": string;
    "tableResults": { [_ in string]?: TableTransferResult | null };

    /** Creates a new DataTransferResult instance. */
    constructor($$source: Partial<DataTransferResult> = {}) {
        if (!("transferId" in $$source)) {
            this["transferId"] = "";
        }
        if (!("tableResults" in $$source)) {
            this["tableResults"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataTransferResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DataTransferResult {
        const $$createField1_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tableResults" in $$parsedSource) {
            $$parsedSource["tableResults"] = $$createField1_0($$parsedSource["tableResults"]);
        }
        return new DataTransferResult($$parsedSource as Partial<DataTransferResult>);
    }
}

/**
 * DriverInfo describes one registered driver to the front-end.
 */
export class DriverInfo {
    "name": string;
    "version": string;
    "capabilities": dbdriver$0.Capabilities;
    "schema": dbdriver$0.ConnParamField[];
    "ui": dbdriver$0.UIDialect;

    /** Creates a new DriverInfo instance. */
    constructor($$source: Partial<DriverInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("capabilities" in $$source)) {
            this["capabilities"] = (new dbdriver$0.Capabilities());
        }
        if (!("schema" in $$source)) {
            this["schema"] = [];
        }
        if (!("ui" in $$source)) {
            this["ui"] = (new dbdriver$0.UIDialect());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DriverInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DriverInfo {
        const $$createField2_0 = $$createType25;
        const $$createField3_0 = $$createType27;
        const $$createField4_0 = $$createType28;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField2_0($$parsedSource["capabilities"]);
        }
        if ("schema" in $$parsedSource) {
            $$parsedSource["schema"] = $$createField3_0($$parsedSource["schema"]);
        }
        if ("ui" in $$parsedSource) {
            $$parsedSource["ui"] = $$createField4_0($$parsedSource["ui"]);
        }
        return new DriverInfo($$parsedSource as Partial<DriverInfo>);
    }
}

/**
 * ExportOptions is what the front-end sends to ExportQuery.
 */
export class ExportOptions {
    "format": TransferFormat;
    "path": string;
    "batchSize"?: number;

    /**
     * CSV: write column row
     */
    "includeHeader"?: boolean;

    /**
     * SQL: include CREATE TABLE (single-table exports only)
     */
    "includeDDL"?: boolean;

    /**
     * SQL: target table name for INSERTs
     */
    "tableName"?: string;

    /**
     * database the SQL addresses (per-db routing)
     */
    "db"?: string;

    /** Creates a new ExportOptions instance. */
    constructor($$source: Partial<ExportOptions> = {}) {
        if (!("format" in $$source)) {
            this["format"] = TransferFormat.$zero;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportOptions($$parsedSource as Partial<ExportOptions>);
    }
}

/**
 * ExportResult is the synchronous return — progress events still fire during.
 */
export class ExportResult {
    "transferId": string;
    "path": string;
    "rowsTotal": number;
    "bytesTotal": number;
    "elapsedMs": number;

    /** Creates a new ExportResult instance. */
    constructor($$source: Partial<ExportResult> = {}) {
        if (!("transferId" in $$source)) {
            this["transferId"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("rowsTotal" in $$source)) {
            this["rowsTotal"] = 0;
        }
        if (!("bytesTotal" in $$source)) {
            this["bytesTotal"] = 0;
        }
        if (!("elapsedMs" in $$source)) {
            this["elapsedMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportResult($$parsedSource as Partial<ExportResult>);
    }
}

/**
 * FileFilterDescriptor is the JSON-shaped filter the front-end sends.
 */
export class FileFilterDescriptor {
    "displayName": string;
    "pattern": string;

    /** Creates a new FileFilterDescriptor instance. */
    constructor($$source: Partial<FileFilterDescriptor> = {}) {
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("pattern" in $$source)) {
            this["pattern"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileFilterDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): FileFilterDescriptor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileFilterDescriptor($$parsedSource as Partial<FileFilterDescriptor>);
    }
}

/**
 * ImportFormat enumerates the supported import file types. Same string values
 * the front-end uses (matched by lower-case).
 */
export enum ImportFormat {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ImportCSV = "csv",
    ImportSQL = "sql",
};

/**
 * ImportOptions describes how to ingest a local file into a connection.
 * 
 * For CSV:
 *   - HasHeader=true uses the first row as column names; otherwise Columns
 *     must be provided.
 *   - Each non-empty row becomes one INSERT.
 * 
 * For SQL:
 *   - The file is streamed through the shared statement splitter
 *     (internal/core/sqlscript): statements are separated on the active
 *     delimiter, with strings/comments respected and the DELIMITER directive
 *     honored, so dumps containing routines/triggers import correctly.
 */
export class ImportOptions {
    "format": ImportFormat;
    "path": string;
    "db"?: string;
    "schema"?: string;

    /**
     * CSV only
     */
    "table"?: string;
    "hasHeader"?: boolean;

    /**
     * CSV only when HasHeader=false
     */
    "columns"?: string[];
    "delimiter"?: string;
    "batchSize"?: number;

    /** Creates a new ImportOptions instance. */
    constructor($$source: Partial<ImportOptions> = {}) {
        if (!("format" in $$source)) {
            this["format"] = ImportFormat.$zero;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportOptions {
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField6_0($$parsedSource["columns"]);
        }
        return new ImportOptions($$parsedSource as Partial<ImportOptions>);
    }
}

/**
 * ImportResult mirrors ExportResult.
 */
export class ImportResult {
    "transferId": string;
    "rowsAffected": number;
    "statementsRun": number;
    "elapsedMs": number;

    /** Creates a new ImportResult instance. */
    constructor($$source: Partial<ImportResult> = {}) {
        if (!("transferId" in $$source)) {
            this["transferId"] = "";
        }
        if (!("rowsAffected" in $$source)) {
            this["rowsAffected"] = 0;
        }
        if (!("statementsRun" in $$source)) {
            this["statementsRun"] = 0;
        }
        if (!("elapsedMs" in $$source)) {
            this["elapsedMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportResult($$parsedSource as Partial<ImportResult>);
    }
}

/**
 * QueryBatchResult is what FetchMore returns.
 */
export class QueryBatchResult {
    "rows": any[][];
    "rowsTotal": number;
    "done": boolean;
    "truncated": boolean;

    /** Creates a new QueryBatchResult instance. */
    constructor($$source: Partial<QueryBatchResult> = {}) {
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("rowsTotal" in $$source)) {
            this["rowsTotal"] = 0;
        }
        if (!("done" in $$source)) {
            this["done"] = false;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryBatchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryBatchResult {
        const $$createField0_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField0_0($$parsedSource["rows"]);
        }
        return new QueryBatchResult($$parsedSource as Partial<QueryBatchResult>);
    }
}

/**
 * QueryOptions tweaks one call's behaviour. All fields optional.
 */
export class QueryOptions {
    /**
     * first-batch size (default 500)
     */
    "batchSize"?: number;

    /**
     * per-call ctx timeout (default 60s)
     */
    "timeoutMs"?: number;

    /**
     * hard cap for the open handle (0 = unlimited)
     */
    "maxRows"?: number;

    /**
     * when non-empty, the SQL is run with this database
     */
    "defaultSchema"?: string;

    /**
     * "selected" (e.g. MySQL `USE db`) so unqualified tables resolve to it.
     * DefaultDatabase routes the SQL to this database's session on drivers
     * whose databases are isolation boundaries (Postgres). Empty = the
     * connection's default database.
     */
    "defaultDatabase"?: string;

    /**
     * when non-empty, the query runs inside the referenced transaction
     */
    "txnId"?: string;

    /** Creates a new QueryOptions instance. */
    constructor($$source: Partial<QueryOptions> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueryOptions($$parsedSource as Partial<QueryOptions>);
    }
}

/**
 * QueryRunResult is what RunQuery / Explain return to the front-end.
 * 
 *   - When Done=true, Handle is empty (the result fit in one batch); the
 *     front-end need not call FetchMore or Close.
 *   - When Done=false, Handle is non-empty and the front-end must eventually
 *     call Close to release the cursor.
 */
export class QueryRunResult {
    "handle"?: string;
    "columns": dbdriver$0.ColumnMeta[];
    "rows": any[][];

    /**
     * running total of rows returned so far
     */
    "rowsTotal": number;
    "done": boolean;

    /**
     * hit MaxRows; cursor closed
     */
    "truncated": boolean;
    "elapsedMs": number;

    /**
     * IsResultSet=true means the SQL returned rows. False means it was an
     * Exec-style statement and the caller should look at ExecResult instead.
     */
    "isResultSet": boolean;
    "execResult"?: dbdriver$0.ExecResult | null;

    /**
     * StatementCount is how many statements the submitted script was split into.
     */
    "statementCount": number;

    /**
     * EditTable is non-nil when the result targets a single identifiable table.
     * The front-end uses this to enable inline editing on the result grid.
     */
    "editTable"?: TableRef | null;

    /** Creates a new QueryRunResult instance. */
    constructor($$source: Partial<QueryRunResult> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("rowsTotal" in $$source)) {
            this["rowsTotal"] = 0;
        }
        if (!("done" in $$source)) {
            this["done"] = false;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }
        if (!("elapsedMs" in $$source)) {
            this["elapsedMs"] = 0;
        }
        if (!("isResultSet" in $$source)) {
            this["isResultSet"] = false;
        }
        if (!("statementCount" in $$source)) {
            this["statementCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryRunResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryRunResult {
        const $$createField1_0 = $$createType10;
        const $$createField2_0 = $$createType12;
        const $$createField8_0 = $$createType30;
        const $$createField10_0 = $$createType32;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField1_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField2_0($$parsedSource["rows"]);
        }
        if ("execResult" in $$parsedSource) {
            $$parsedSource["execResult"] = $$createField8_0($$parsedSource["execResult"]);
        }
        if ("editTable" in $$parsedSource) {
            $$parsedSource["editTable"] = $$createField10_0($$parsedSource["editTable"]);
        }
        return new QueryRunResult($$parsedSource as Partial<QueryRunResult>);
    }
}

/**
 * RowChange is the front-end's request to mutate one row.
 * 
 * Op selects the operation:
 * 
 * 	"insert" — uses Values, ignores PK.
 * 	"update" — uses PK to locate the row, Values are the new column values.
 * 	"delete" — uses PK only.
 * 
 * PK must match the columns reported by GetPrimaryKey; the driver enforces
 * "no keyless UPDATE/DELETE" by refusing an empty pk map.
 */
export class RowChange {
    "op": string;
    "db": string;
    "schema"?: string;
    "table": string;
    "pk"?: { [_ in string]?: any };
    "values"?: { [_ in string]?: any };

    /** Creates a new RowChange instance. */
    constructor($$source: Partial<RowChange> = {}) {
        if (!("op" in $$source)) {
            this["op"] = "";
        }
        if (!("db" in $$source)) {
            this["db"] = "";
        }
        if (!("table" in $$source)) {
            this["table"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RowChange instance from a string or object.
     */
    static createFrom($$source: any = {}): RowChange {
        const $$createField4_0 = $$createType33;
        const $$createField5_0 = $$createType33;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pk" in $$parsedSource) {
            $$parsedSource["pk"] = $$createField4_0($$parsedSource["pk"]);
        }
        if ("values" in $$parsedSource) {
            $$parsedSource["values"] = $$createField5_0($$parsedSource["values"]);
        }
        return new RowChange($$parsedSource as Partial<RowChange>);
    }
}

/**
 * RowChangeResult reports what the driver did. RowsAffected==0 on UPDATE/
 * DELETE is the front-end's "stale row" signal (optimistic-lock loss).
 */
export class RowChangeResult {
    "rowsAffected": number;
    "lastInsertId"?: number;

    /**
     * the rendered SQL, for the editor's "history" panel
     */
    "sql": string;

    /** Creates a new RowChangeResult instance. */
    constructor($$source: Partial<RowChangeResult> = {}) {
        if (!("rowsAffected" in $$source)) {
            this["rowsAffected"] = 0;
        }
        if (!("sql" in $$source)) {
            this["sql"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RowChangeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): RowChangeResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RowChangeResult($$parsedSource as Partial<RowChangeResult>);
    }
}

/**
 * SchemaCompareRequest names the two databases to reconcile. Tables narrows
 * the comparison to the listed tables; empty means every table.
 */
export class SchemaCompareRequest {
    "sourceConnId": string;
    "sourceDb": string;
    "sourceSchema": string;
    "targetConnId": string;
    "targetDb": string;
    "targetSchema": string;
    "tables": string[];

    /** Creates a new SchemaCompareRequest instance. */
    constructor($$source: Partial<SchemaCompareRequest> = {}) {
        if (!("sourceConnId" in $$source)) {
            this["sourceConnId"] = "";
        }
        if (!("sourceDb" in $$source)) {
            this["sourceDb"] = "";
        }
        if (!("sourceSchema" in $$source)) {
            this["sourceSchema"] = "";
        }
        if (!("targetConnId" in $$source)) {
            this["targetConnId"] = "";
        }
        if (!("targetDb" in $$source)) {
            this["targetDb"] = "";
        }
        if (!("targetSchema" in $$source)) {
            this["targetSchema"] = "";
        }
        if (!("tables" in $$source)) {
            this["tables"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchemaCompareRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SchemaCompareRequest {
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField6_0($$parsedSource["tables"]);
        }
        return new SchemaCompareRequest($$parsedSource as Partial<SchemaCompareRequest>);
    }
}

/**
 * SchemaCompareResult is the ordered object list (tables first, then views).
 */
export class SchemaCompareResult {
    "syncId": string;
    "objects": SchemaObjectDiff[];

    /** Creates a new SchemaCompareResult instance. */
    constructor($$source: Partial<SchemaCompareResult> = {}) {
        if (!("syncId" in $$source)) {
            this["syncId"] = "";
        }
        if (!("objects" in $$source)) {
            this["objects"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchemaCompareResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SchemaCompareResult {
        const $$createField1_0 = $$createType35;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("objects" in $$parsedSource) {
            $$parsedSource["objects"] = $$createField1_0($$parsedSource["objects"]);
        }
        return new SchemaCompareResult($$parsedSource as Partial<SchemaCompareResult>);
    }
}

/**
 * SchemaObjectDiff is one table/view in the compare result. Statements is the
 * DDL (already rendered for the target) that reconciles the object;
 * Destructive marks statements that can lose data or objects (DROP TABLE /
 * DROP VIEW / column drops) so the UI can default them to unchecked.
 */
export class SchemaObjectDiff {
    "name": string;

    /**
     * "table" | "view"
     */
    "kind": string;

    /**
     * "create" | "drop" | "alter" | "same"
     */
    "status": string;
    "statements": string[];
    "destructive"?: boolean;

    /**
     * Error carries a per-object failure slug + detail; the object is shown
     * but not executable. Other objects still compare.
     */
    "error"?: string;

    /** Creates a new SchemaObjectDiff instance. */
    constructor($$source: Partial<SchemaObjectDiff> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("statements" in $$source)) {
            this["statements"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchemaObjectDiff instance from a string or object.
     */
    static createFrom($$source: any = {}): SchemaObjectDiff {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("statements" in $$parsedSource) {
            $$parsedSource["statements"] = $$createField3_0($$parsedSource["statements"]);
        }
        return new SchemaObjectDiff($$parsedSource as Partial<SchemaObjectDiff>);
    }
}

/**
 * SchemaSyncExecRequest carries the user-approved statements to run on the
 * target, in order. StopOnError halts at the first failure; otherwise the
 * remaining statements still run and failures are reported per statement.
 */
export class SchemaSyncExecRequest {
    "targetConnId": string;

    /**
     * TargetDB routes the statements to the addressed database on drivers
     * whose databases are isolation boundaries (Postgres).
     */
    "targetDb"?: string;
    "statements": string[];
    "stopOnError": boolean;

    /** Creates a new SchemaSyncExecRequest instance. */
    constructor($$source: Partial<SchemaSyncExecRequest> = {}) {
        if (!("targetConnId" in $$source)) {
            this["targetConnId"] = "";
        }
        if (!("statements" in $$source)) {
            this["statements"] = [];
        }
        if (!("stopOnError" in $$source)) {
            this["stopOnError"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchemaSyncExecRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SchemaSyncExecRequest {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("statements" in $$parsedSource) {
            $$parsedSource["statements"] = $$createField2_0($$parsedSource["statements"]);
        }
        return new SchemaSyncExecRequest($$parsedSource as Partial<SchemaSyncExecRequest>);
    }
}

/**
 * SchemaSyncExecResult summarizes an Execute run.
 */
export class SchemaSyncExecResult {
    "syncId": string;
    "executed": number;
    "failed": number;
    "results": SchemaSyncStatementResult[];

    /** Creates a new SchemaSyncExecResult instance. */
    constructor($$source: Partial<SchemaSyncExecResult> = {}) {
        if (!("syncId" in $$source)) {
            this["syncId"] = "";
        }
        if (!("executed" in $$source)) {
            this["executed"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }
        if (!("results" in $$source)) {
            this["results"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchemaSyncExecResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SchemaSyncExecResult {
        const $$createField3_0 = $$createType37;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField3_0($$parsedSource["results"]);
        }
        return new SchemaSyncExecResult($$parsedSource as Partial<SchemaSyncExecResult>);
    }
}

/**
 * SchemaSyncStatementResult reports one executed statement.
 */
export class SchemaSyncStatementResult {
    "statement": string;
    "error"?: string;

    /** Creates a new SchemaSyncStatementResult instance. */
    constructor($$source: Partial<SchemaSyncStatementResult> = {}) {
        if (!("statement" in $$source)) {
            this["statement"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchemaSyncStatementResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SchemaSyncStatementResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SchemaSyncStatementResult($$parsedSource as Partial<SchemaSyncStatementResult>);
    }
}

/**
 * TableRef identifies a single table that the result rows map to, enabling
 * inline editing on query results. nil means the query is too complex for
 * safe inline editing (multi-table, aggregate, etc.).
 */
export class TableRef {
    "db": string;
    "table": string;

    /** Creates a new TableRef instance. */
    constructor($$source: Partial<TableRef> = {}) {
        if (!("db" in $$source)) {
            this["db"] = "";
        }
        if (!("table" in $$source)) {
            this["table"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableRef instance from a string or object.
     */
    static createFrom($$source: any = {}): TableRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TableRef($$parsedSource as Partial<TableRef>);
    }
}

/**
 * TableSummary bundles columns/indexes/FKs into one round-trip — handy for
 * the structure viewer so it can render the whole panel without sequencing
 * three calls from the front-end.
 */
export class TableSummary {
    "columns": dbdriver$0.ColumnMeta[];
    "indexes": dbdriver$0.IndexInfo[];
    "foreignKeys": dbdriver$0.ForeignKeyInfo[];

    /** Creates a new TableSummary instance. */
    constructor($$source: Partial<TableSummary> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("indexes" in $$source)) {
            this["indexes"] = [];
        }
        if (!("foreignKeys" in $$source)) {
            this["foreignKeys"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): TableSummary {
        const $$createField0_0 = $$createType10;
        const $$createField1_0 = $$createType39;
        const $$createField2_0 = $$createType41;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("indexes" in $$parsedSource) {
            $$parsedSource["indexes"] = $$createField1_0($$parsedSource["indexes"]);
        }
        if ("foreignKeys" in $$parsedSource) {
            $$parsedSource["foreignKeys"] = $$createField2_0($$parsedSource["foreignKeys"]);
        }
        return new TableSummary($$parsedSource as Partial<TableSummary>);
    }
}

/**
 * TableTransferResult reports the outcome for one table.
 */
export class TableTransferResult {
    "rows": number;
    "error"?: string;

    /** Creates a new TableTransferResult instance. */
    constructor($$source: Partial<TableTransferResult> = {}) {
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableTransferResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TableTransferResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TableTransferResult($$parsedSource as Partial<TableTransferResult>);
    }
}

/**
 * TransferFormat enumerates the supported file types. Strings match
 * front-end identifiers and the file extension we expect.
 */
export enum TransferFormat {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FormatCSV = "csv",
    FormatJSON = "json",
    FormatSQL = "sql",
    FormatXLSX = "xlsx",
};

/**
 * UpdateCheckResult is what the front-end sees after a CheckForUpdate.
 */
export class UpdateCheckResult {
    /**
     * Available is true when latest > current AND latest != skipped.
     */
    "available": boolean;

    /**
     * LatestVersion is the trimmed tag (e.g. "1.4.2").
     */
    "latestVersion": string;

    /**
     * CurrentVersion echoes what the front-end passed in.
     */
    "currentVersion": string;

    /**
     * ReleaseNotes is the GitHub Release body — markdown.
     */
    "releaseNotes": string;

    /**
     * ReleaseURL points at the GitHub release page.
     */
    "releaseUrl": string;

    /**
     * PublishedAt — RFC3339; "" if missing.
     */
    "publishedAt": string;

    /**
     * AssetName is the matched installer for this OS/arch; "" if none.
     */
    "assetName": string;

    /**
     * HasAsset is true when PickAsset succeeded — used to gate the "install" CTA.
     */
    "hasAsset": boolean;

    /**
     * Skipped is true when LatestVersion equals the user-skipped version.
     */
    "skipped": boolean;

    /**
     * Prerelease is true when the matched release is a GitHub prerelease —
     * the UI badges it as Beta.
     */
    "prerelease": boolean;

    /** Creates a new UpdateCheckResult instance. */
    constructor($$source: Partial<UpdateCheckResult> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = "";
        }
        if (!("releaseNotes" in $$source)) {
            this["releaseNotes"] = "";
        }
        if (!("releaseUrl" in $$source)) {
            this["releaseUrl"] = "";
        }
        if (!("publishedAt" in $$source)) {
            this["publishedAt"] = "";
        }
        if (!("assetName" in $$source)) {
            this["assetName"] = "";
        }
        if (!("hasAsset" in $$source)) {
            this["hasAsset"] = false;
        }
        if (!("skipped" in $$source)) {
            this["skipped"] = false;
        }
        if (!("prerelease" in $$source)) {
            this["prerelease"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateCheckResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateCheckResult($$parsedSource as Partial<UpdateCheckResult>);
    }
}

// Private type creation functions
const $$createType0 = TableSummary.createFrom;
const $$createType1 = schemadiff$0.Table.createFrom;
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = storage$0.AgentAuditEntry.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = AutocompleteTable.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = AutocompleteColumn.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = dbdriver$0.ColumnMeta.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $Create.Array($Create.Any);
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $Create.Map($Create.Any, $Create.Any);
const $$createType14 = dbdriver$0.SSLConfig.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = dbdriver$0.SSHConfig.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = DataTableDiff.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = datasync$0.DiffSample.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = TableTransferResult.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = $Create.Map($Create.Any, $$createType23);
const $$createType25 = dbdriver$0.Capabilities.createFrom;
const $$createType26 = dbdriver$0.ConnParamField.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = dbdriver$0.UIDialect.createFrom;
const $$createType29 = dbdriver$0.ExecResult.createFrom;
const $$createType30 = $Create.Nullable($$createType29);
const $$createType31 = TableRef.createFrom;
const $$createType32 = $Create.Nullable($$createType31);
const $$createType33 = $Create.Map($Create.Any, $Create.Any);
const $$createType34 = SchemaObjectDiff.createFrom;
const $$createType35 = $Create.Array($$createType34);
const $$createType36 = SchemaSyncStatementResult.createFrom;
const $$createType37 = $Create.Array($$createType36);
const $$createType38 = dbdriver$0.IndexInfo.createFrom;
const $$createType39 = $Create.Array($$createType38);
const $$createType40 = dbdriver$0.ForeignKeyInfo.createFrom;
const $$createType41 = $Create.Array($$createType40);
