// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * QueryService is the IPC entry point for SQL execution. It is THIN: parses
 * inputs, picks the right driver via session.Manager, and forwards. Streaming
 * state (open ResultSets) lives in its private registry keyed by handle.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dbdriver$0 from "../dbdriver/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BeginTransaction opens a new transaction on the connection. Returns a
 * transaction ID the front-end passes to RunQuery (via QueryOptions.TxnID),
 * CommitTransaction, or RollbackTransaction.
 */
export function BeginTransaction(connID: string, db: string): $CancellablePromise<string> {
    return $Call.ByName("catdb/internal/services.QueryService.BeginTransaction", connID, db);
}

/**
 * CapabilitiesFor returns the registered driver's Capabilities for the given
 * connID, so the front-end can render UI gates without going through the
 * active connection.
 */
export function CapabilitiesFor(driverName: string): $CancellablePromise<dbdriver$0.Capabilities> {
    return $Call.ByName("catdb/internal/services.QueryService.CapabilitiesFor", driverName).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Close releases a handle and its underlying cursor. Idempotent.
 */
export function Close(handle: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.QueryService.Close", handle);
}

/**
 * CommitTransaction commits the referenced transaction and releases it.
 */
export function CommitTransaction(txnID: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.QueryService.CommitTransaction", txnID);
}

/**
 * CountQuery returns the total row count of the (final) statement in sqlText
 * by wrapping it in SELECT COUNT(*) FROM (…) AS a derived table. The editor
 * fires it alongside a streaming RunQuery so the result grid can show
 * "N / total" before the drain finishes. Only statements that can legally sit
 * in a derived table are countable (SELECT / WITH / TABLE / VALUES); anything
 * else errors and the front-end treats the total as unknown.
 * 
 * The count always runs on the pooled connection, never inside an open
 * user transaction — a Tx serializes on one physical connection, which the
 * concurrently-streaming cursor may be holding.
 */
export function CountQuery(connID: string, sqlText: string, opts: $models.QueryOptions): $CancellablePromise<number> {
    return $Call.ByName("catdb/internal/services.QueryService.CountQuery", connID, sqlText, opts);
}

/**
 * Explain runs EXPLAIN against the SQL and returns the entire plan inline.
 * Caps the rows to DefaultBatchSize — EXPLAIN plans are never huge.
 * 
 * Gated by Capabilities.ExplainPlan (the front-end hides the button when the
 * driver doesn't support it).
 */
export function Explain(connID: string, sqlText: string, opts: $models.QueryOptions): $CancellablePromise<$models.QueryRunResult> {
    return $Call.ByName("catdb/internal/services.QueryService.Explain", connID, sqlText, opts).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * FetchMore reads the next batch from an open handle. Once Done=true the
 * handle is closed automatically — the front-end should drop its reference.
 */
export function FetchMore(handle: string, batch: number): $CancellablePromise<$models.QueryBatchResult> {
    return $Call.ByName("catdb/internal/services.QueryService.FetchMore", handle, batch).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * IsTransactionActive returns true when the referenced transaction exists.
 */
export function IsTransactionActive(txnID: string): $CancellablePromise<boolean> {
    return $Call.ByName("catdb/internal/services.QueryService.IsTransactionActive", txnID);
}

/**
 * RollbackTransaction rolls back the referenced transaction and releases it.
 */
export function RollbackTransaction(txnID: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.QueryService.RollbackTransaction", txnID);
}

/**
 * RunQuery executes sqlText against connID's live Connection, returning the
 * first batch + column metadata. Behaviour:
 *   - SELECT-like (rows): keeps the cursor open, returns Handle for paging.
 *   - Non-SELECT: returns ExecResult, no Handle.
 *   - Cancellation: the Wails CancellablePromise on the front-end cancels
 *     ctx; QueryContext aborts the query server-side.
 *   - Timeout: capped at QueryOptions.TimeoutMs (default 60s).
 */
export function RunQuery(connID: string, sqlText: string, opts: $models.QueryOptions): $CancellablePromise<$models.QueryRunResult> {
    return $Call.ByName("catdb/internal/services.QueryService.RunQuery", connID, sqlText, opts).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = dbdriver$0.Capabilities.createFrom;
const $$createType1 = $models.QueryRunResult.createFrom;
const $$createType2 = $models.QueryBatchResult.createFrom;
