// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * QueryService is the IPC entry point for SQL execution. It is THIN: parses
 * inputs, picks the right driver via session.Manager, and forwards. Streaming
 * state (open ResultSets) lives in its private registry keyed by handle.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dbdriver$0 from "../dbdriver/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CapabilitiesFor returns the registered driver's Capabilities for the given
 * connID, so the front-end can render UI gates without going through the
 * active connection.
 */
export function CapabilitiesFor(driverName: string): $CancellablePromise<dbdriver$0.Capabilities> {
    return $Call.ByID(693442694, driverName).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Close releases a handle and its underlying cursor. Idempotent.
 */
export function Close(handle: string): $CancellablePromise<void> {
    return $Call.ByID(4229270911, handle);
}

/**
 * Explain runs EXPLAIN against the SQL and returns the entire plan inline.
 * Caps the rows to DefaultBatchSize — EXPLAIN plans are never huge.
 * 
 * Gated by Capabilities.ExplainPlan (the front-end hides the button when the
 * driver doesn't support it).
 */
export function Explain(connID: string, sqlText: string): $CancellablePromise<$models.QueryRunResult> {
    return $Call.ByID(3956862712, connID, sqlText).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * FetchMore reads the next batch from an open handle. Once Done=true the
 * handle is closed automatically — the front-end should drop its reference.
 */
export function FetchMore(handle: string, batch: number): $CancellablePromise<$models.QueryBatchResult> {
    return $Call.ByID(1774901466, handle, batch).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * RunQuery executes sqlText against connID's live Connection, returning the
 * first batch + column metadata. Behaviour:
 *   - SELECT-like (rows): keeps the cursor open, returns Handle for paging.
 *   - Non-SELECT: returns ExecResult, no Handle.
 *   - Cancellation: the Wails CancellablePromise on the front-end cancels
 *     ctx; QueryContext aborts the query server-side.
 *   - Timeout: capped at QueryOptions.TimeoutMs (default 60s).
 */
export function RunQuery(connID: string, sqlText: string, opts: $models.QueryOptions): $CancellablePromise<$models.QueryRunResult> {
    return $Call.ByID(920722978, connID, sqlText, opts).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = dbdriver$0.Capabilities.createFrom;
const $$createType1 = $models.QueryRunResult.createFrom;
const $$createType2 = $models.QueryBatchResult.createFrom;
