// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SavedQueryService is the Wails Service that owns named SQL snippets stored
 * under a connection's database node in the object tree. Per ARCHITECTURE.md
 * §2 it stays THIN: validates input, forwards to storage.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";

/**
 * Delete removes a saved query by ID.
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.SavedQueryService.Delete", id);
}

/**
 * List returns the saved queries scoped to a connection + database + schema
 * ("" for schema-less databases).
 */
export function List(connID: string, db: string, schema: string): $CancellablePromise<storage$0.SavedQuery[]> {
    return $Call.ByName("catdb/internal/services.SavedQueryService.List", connID, db, schema).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Save inserts (empty ID) or updates a saved query and returns the persisted row.
 */
export function Save(draft: storage$0.SavedQuery): $CancellablePromise<storage$0.SavedQuery> {
    return $Call.ByName("catdb/internal/services.SavedQueryService.Save", draft).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = storage$0.SavedQuery.createFrom;
const $$createType1 = $Create.Array($$createType0);
