// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService exposes user preferences (currently the UI locale) to the
 * front-end. Values are persisted in the app_settings key/value table.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetLocale returns the persisted UI locale (e.g. "en-US", "zh-CN"), or ""
 * when the user has never chosen one — the front-end then falls back to the
 * system locale.
 */
export function GetLocale(): $CancellablePromise<string> {
    return $Call.ByName("catdb/internal/services.SettingsService.GetLocale");
}

/**
 * SetLocale persists the chosen UI locale and rebuilds the native menus
 * (app menu + context menus) so they switch language in step with the WebView.
 */
export function SetLocale(locale: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.SettingsService.SetLocale", locale);
}
