// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SyncService drives structure synchronization (and, in S4, data
 * synchronization): compare two databases, render the DDL that reconciles the
 * target with the source, and execute the user-approved subset.
 * 
 * Compare is read-only; Execute only ever runs the statements the front-end
 * passes back, so the user always sees exactly what will run.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CompareData runs the dry-run merge for every resolvable table: counts +
 * bounded samples, no writes.
 */
export function CompareData(req: $models.DataCompareRequest): $CancellablePromise<$models.DataCompareResult> {
    return $Call.ByName("catdb/internal/services.SyncService.CompareData", req).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CompareSchemas diffs every (selected) table and view of source vs target
 * and renders reconciliation DDL through the TARGET's dialect — that's the
 * server the statements will run on.
 */
export function CompareSchemas(req: $models.SchemaCompareRequest): $CancellablePromise<$models.SchemaCompareResult> {
    return $Call.ByName("catdb/internal/services.SyncService.CompareSchemas", req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ExecuteDataSync applies the differences for the listed tables. Writes run
 * on a dedicated target connection in batched transactions; the shared
 * connection other windows use is never blocked.
 */
export function ExecuteDataSync(req: $models.DataSyncExecRequest): $CancellablePromise<$models.DataSyncExecResult> {
    return $Call.ByName("catdb/internal/services.SyncService.ExecuteDataSync", req).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ExecuteSchemaSync runs the approved DDL statements sequentially on the
 * target connection, emitting sync:progress after each statement.
 */
export function ExecuteSchemaSync(req: $models.SchemaSyncExecRequest): $CancellablePromise<$models.SchemaSyncExecResult> {
    return $Call.ByName("catdb/internal/services.SyncService.ExecuteSchemaSync", req).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DataCompareResult.createFrom;
const $$createType1 = $models.SchemaCompareResult.createFrom;
const $$createType2 = $models.DataSyncExecResult.createFrom;
const $$createType3 = $models.SchemaSyncExecResult.createFrom;
