// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService exposes a small set of OS-level helpers to the front-end:
 * native file dialogs, message dialogs. Routes through wailsbridge so the
 * Wails alpha API never leaks into the components directly.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AllowNextClose lets the next WindowClosing succeed even with dirty tabs.
 * Call after the front-end has shown its confirm dialog and the user
 * accepted "Discard & Close".
 */
export function AllowNextClose(): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.SystemService.AllowNextClose");
}

/**
 * BroadcastConnectionSaved tells every window that a connection was saved.
 * Used by the connection-editor child window to nudge the main window into
 * refreshing its sidebar list.
 */
export function BroadcastConnectionSaved(connID: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.SystemService.BroadcastConnectionSaved", connID);
}

/**
 * BroadcastDatabaseSaved tells every window that a database was created or
 * altered. The main window's ObjectTree listens for this and refreshes the
 * matching connection's tree.
 */
export function BroadcastDatabaseSaved(connID: string, dbName: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.SystemService.BroadcastDatabaseSaved", connID, dbName);
}

/**
 * CopyToClipboard writes text to the native system clipboard. The WebView's
 * own navigator.clipboard is permission-gated (WKWebView denies it), so the
 * front-end's copy actions call this instead (api/system.copyText).
 */
export function CopyToClipboard(text: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.SystemService.CopyToClipboard", text);
}

/**
 * OpenConnectionEditor pops the connection editor as its own native window.
 * `driver` is the driver name (e.g. "mysql") and `connID` is the profile id
 * to edit (empty string for a new-connection flow).
 * 
 * The auxiliary window is keyed by name "connection-editor", so re-opening
 * while it is already on screen just brings it forward with the new params
 * instead of stacking duplicates.
 */
export function OpenConnectionEditor(driver: string, connID: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.SystemService.OpenConnectionEditor", driver, connID);
}

/**
 * OpenDataSyncDialog opens the Data Synchronization dialog as its own native
 * child window, keyed by name "data-sync".
 */
export function OpenDataSyncDialog(): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.SystemService.OpenDataSyncDialog");
}

/**
 * OpenDatabaseEditor pops the "新建/编辑数据库" form as its own native window,
 * reusing the catdb-tree-database right-click flow. Pass an empty dbName for
 * create mode; a non-empty dbName for edit mode.
 * 
 * The auxiliary window is keyed by name "database-editor" so re-opening it
 * (e.g. user right-clicks another DB while it's already open) brings the
 * existing window forward with the new params instead of stacking duplicates.
 */
export function OpenDatabaseEditor(connID: string, dbName: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.SystemService.OpenDatabaseEditor", connID, dbName);
}

/**
 * OpenExternalURL opens the given URL in the user's default browser.
 * Used by features like the update dialog's "view on GitHub" link — a plain
 * <a target="_blank"> inside the WebView either no-ops or navigates the
 * WebView itself, neither of which is what we want.
 */
export function OpenExternalURL(target: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.SystemService.OpenExternalURL", target);
}

/**
 * OpenSettingsWindow opens the app settings as its own native child window,
 * keyed by name "settings". section optionally pre-selects a settings
 * category (e.g. "ai"); empty string means the default category.
 */
export function OpenSettingsWindow(section: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.SystemService.OpenSettingsWindow", section);
}

/**
 * OpenStructureSyncDialog opens the Structure Synchronization dialog as its
 * own native child window, keyed by name "structure-sync".
 */
export function OpenStructureSyncDialog(): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.SystemService.OpenStructureSyncDialog");
}

/**
 * OpenTransferDialog opens the Data Transfer dialog as its own native
 * child window, keyed by name "transfer-editor".
 */
export function OpenTransferDialog(): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.SystemService.OpenTransferDialog");
}

/**
 * PickOpenFile shows the native Open dialog and returns the chosen path, or
 * "" if the user cancelled.
 */
export function PickOpenFile(title: string, filters: $models.FileFilterDescriptor[]): $CancellablePromise<string> {
    return $Call.ByName("catdb/internal/services.SystemService.PickOpenFile", title, filters);
}

/**
 * PickSaveFile shows the native Save dialog and returns the chosen path, or
 * "" if the user cancelled.
 */
export function PickSaveFile(title: string, defaultName: string, filters: $models.FileFilterDescriptor[]): $CancellablePromise<string> {
    return $Call.ByName("catdb/internal/services.SystemService.PickSaveFile", title, defaultName, filters);
}

/**
 * SetDirtyTabs reports how many unsaved query tabs exist. The Go-side
 * close-guard reads this on WindowClosing to decide whether to block.
 */
export function SetDirtyTabs(count: number): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.SystemService.SetDirtyTabs", count);
}

export function ShowError(title: string, message: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.SystemService.ShowError", title, message);
}

/**
 * ShowInfo / ShowError trigger native message dialogs.
 */
export function ShowInfo(title: string, message: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.SystemService.ShowInfo", title, message);
}
