// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService exposes a small set of OS-level helpers to the front-end:
 * native file dialogs, message dialogs. Routes through wailsbridge so the
 * Wails alpha API never leaks into the components directly.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AllowNextClose lets the next WindowClosing succeed even with dirty tabs.
 * Call after the front-end has shown its confirm dialog and the user
 * accepted "Discard & Close".
 */
export function AllowNextClose(): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.SystemService.AllowNextClose");
}

/**
 * BroadcastConnectionSaved tells every window that a connection was saved.
 * Used by the connection-editor child window to nudge the main window into
 * refreshing its sidebar list.
 */
export function BroadcastConnectionSaved(connID: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.SystemService.BroadcastConnectionSaved", connID);
}

/**
 * OpenConnectionEditor pops the connection editor as its own native window.
 * `driver` is the driver name (e.g. "mysql") and `connID` is the profile id
 * to edit (empty string for a new-connection flow).
 * 
 * The auxiliary window is keyed by name "connection-editor", so re-opening
 * while it is already on screen just brings it forward with the new params
 * instead of stacking duplicates.
 */
export function OpenConnectionEditor(driver: string, connID: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.SystemService.OpenConnectionEditor", driver, connID);
}

/**
 * OpenExternalURL opens the given URL in the user's default browser.
 * Used by features like the update dialog's "view on GitHub" link — a plain
 * <a target="_blank"> inside the WebView either no-ops or navigates the
 * WebView itself, neither of which is what we want.
 */
export function OpenExternalURL(target: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.SystemService.OpenExternalURL", target);
}

/**
 * PickOpenFile shows the native Open dialog and returns the chosen path, or
 * "" if the user cancelled.
 */
export function PickOpenFile(title: string, filters: $models.FileFilterDescriptor[]): $CancellablePromise<string> {
    return $Call.ByName("catdb/internal/services.SystemService.PickOpenFile", title, filters);
}

/**
 * PickSaveFile shows the native Save dialog and returns the chosen path, or
 * "" if the user cancelled.
 */
export function PickSaveFile(title: string, defaultName: string, filters: $models.FileFilterDescriptor[]): $CancellablePromise<string> {
    return $Call.ByName("catdb/internal/services.SystemService.PickSaveFile", title, defaultName, filters);
}

/**
 * SetDirtyTabs reports how many unsaved query tabs exist. The Go-side
 * close-guard reads this on WindowClosing to decide whether to block.
 */
export function SetDirtyTabs(count: number): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.SystemService.SetDirtyTabs", count);
}

export function ShowError(title: string, message: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.SystemService.ShowError", title, message);
}

/**
 * ShowInfo / ShowError trigger native message dialogs.
 */
export function ShowInfo(title: string, message: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.SystemService.ShowInfo", title, message);
}
