// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService exposes a small set of OS-level helpers to the front-end:
 * native file dialogs, message dialogs. Routes through wailsbridge so the
 * Wails alpha API never leaks into the components directly.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AllowNextClose lets the next WindowClosing succeed even with dirty tabs.
 * Call after the front-end has shown its confirm dialog and the user
 * accepted "Discard & Close".
 */
export function AllowNextClose(): $CancellablePromise<void> {
    return $Call.ByID(540885912);
}

/**
 * PickOpenFile shows the native Open dialog and returns the chosen path, or
 * "" if the user cancelled.
 */
export function PickOpenFile(title: string, filters: $models.FileFilterDescriptor[]): $CancellablePromise<string> {
    return $Call.ByID(3227827043, title, filters);
}

/**
 * PickSaveFile shows the native Save dialog and returns the chosen path, or
 * "" if the user cancelled.
 */
export function PickSaveFile(title: string, defaultName: string, filters: $models.FileFilterDescriptor[]): $CancellablePromise<string> {
    return $Call.ByID(973255610, title, defaultName, filters);
}

/**
 * SetDirtyTabs reports how many unsaved query tabs exist. The Go-side
 * close-guard reads this on WindowClosing to decide whether to block.
 */
export function SetDirtyTabs(count: number): $CancellablePromise<void> {
    return $Call.ByID(3642892468, count);
}

export function ShowError(title: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(167066461, title, message);
}

/**
 * ShowInfo / ShowError trigger native message dialogs.
 */
export function ShowInfo(title: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(2515121281, title, message);
}
