// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TransferService wraps export + import. It owns no streaming state itself —
 * each call opens, writes, and closes — so multiple concurrent exports are
 * safe as long as ctx for each is independent.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExportQuery runs sqlText and streams every row through the chosen format
 * into opts.Path. Returns when EOF (or ctx cancel / error).
 * 
 * For Excel: uses excelize NewStreamWriter — rows are flushed to disk as we
 * go; memory stays bounded.
 * For CSV/JSON: encoding/csv + json.Encoder with newline framing (JSON Lines).
 * For SQL: per-row INSERT (lightweight, easy to import anywhere).
 */
export function ExportQuery(connID: string, sqlText: string, opts: $models.ExportOptions): $CancellablePromise<$models.ExportResult> {
    return $Call.ByName("catdb/internal/services.TransferService.ExportQuery", connID, sqlText, opts).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ExportTable is a convenience wrapper around ExportQuery for "dump this
 * whole table". When IncludeDDL is true the resulting SQL file gets a
 * CREATE TABLE prefix from the driver's metadata layer.
 */
export function ExportTable(connID: string, db: string, schema: string, table: string, opts: $models.ExportOptions): $CancellablePromise<$models.ExportResult> {
    return $Call.ByName("catdb/internal/services.TransferService.ExportTable", connID, db, schema, table, opts).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportFile streams Path into the target DB. Path comes from the native
 * OpenFile dialog (so the back-end has filesystem access).
 */
export function ImportFile(connID: string, opts: $models.ImportOptions): $CancellablePromise<$models.ImportResult> {
    return $Call.ByName("catdb/internal/services.TransferService.ImportFile", connID, opts).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * StartTransfer copies data from source-connection tables to target-connection
 * tables. The method is synchronous — callers cancel via ctx; progress events
 * fire on transfer:progress.
 */
export function StartTransfer(req: $models.DataTransferRequest): $CancellablePromise<$models.DataTransferResult> {
    return $Call.ByName("catdb/internal/services.TransferService.StartTransfer", req).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ExportResult.createFrom;
const $$createType1 = $models.ImportResult.createFrom;
const $$createType2 = $models.DataTransferResult.createFrom;
