// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService exposes the auto-updater to the front-end:
 * 
 * 	CheckForUpdate     — talk to GitHub Releases, compare to currentVersion
 * 	GetSkippedVersion  — what version the user has chosen to ignore
 * 	SkipVersion        — persist a skip decision
 * 	StartInstall       — download the matched asset and hand off to the
 * 	                     platform installer; the app quits when control
 * 	                     returns from the installer spawn.
 * 
 * The repo is hard-coded to updater.DefaultRepo ("peisp/catdb") — there is
 * no per-user override yet.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdate compares the latest GitHub release to currentVersion. Returns
 * a fully populated result even when no update is available (so the UI can
 * render "you're up to date" instead of throwing).
 */
export function CheckForUpdate(currentVersion: string): $CancellablePromise<$models.UpdateCheckResult> {
    return $Call.ByName("catdb/internal/services.UpdateService.CheckForUpdate", currentVersion).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetSkippedVersion returns the version the user previously chose to skip,
 * or "" if none.
 */
export function GetSkippedVersion(): $CancellablePromise<string> {
    return $Call.ByName("catdb/internal/services.UpdateService.GetSkippedVersion");
}

/**
 * SkipVersion persists version as the "ignore this release" marker.
 */
export function SkipVersion(version: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.UpdateService.SkipVersion", version);
}

/**
 * StartInstall downloads the matched asset for currentVersion→latest and
 * then hands off to the OS-specific installer. It emits update:progress
 * events while running and finally quits the app so the swap can complete.
 * 
 * Returns once the installer has been spawned (or an error before that). The
 * caller (front-end) should already have shown a confirm dialog by this point.
 */
export function StartInstall(currentVersion: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.UpdateService.StartInstall", currentVersion);
}

// Private type creation functions
const $$createType0 = $models.UpdateCheckResult.createFrom;
