// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService exposes the auto-updater to the front-end:
 * 
 * 	CheckForUpdate     — talk to GitHub Releases, compare to currentVersion
 * 	GetSkippedVersion  — what version the user has chosen to ignore
 * 	SkipVersion        — persist a skip decision
 * 	DownloadUpdate     — download the matched asset and stage it locally;
 * 	                     the install waits for the user's explicit go-ahead
 * 	RestartAndInstall  — hand the staged asset to the platform installer
 * 	                     (silent) and quit so the swap can complete
 * 
 * The repo is hard-coded to updater.DefaultRepo ("peisp/catdb") — there is
 * no per-user override yet.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdate compares the latest GitHub release to currentVersion. Returns
 * a fully populated result even when no update is available (so the UI can
 * render "you're up to date" instead of throwing).
 */
export function CheckForUpdate(currentVersion: string): $CancellablePromise<$models.UpdateCheckResult> {
    return $Call.ByName("catdb/internal/services.UpdateService.CheckForUpdate", currentVersion).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DownloadUpdate downloads the matched asset for currentVersion→latest and
 * stages it locally. It emits update:progress events while running and ends
 * in phase "downloaded" — installing/restarting waits for the user to call
 * RestartAndInstall explicitly.
 */
export function DownloadUpdate(currentVersion: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.UpdateService.DownloadUpdate", currentVersion);
}

/**
 * GetChannel returns the effective update channel for the given running
 * version ("stable" | "beta").
 */
export function GetChannel(currentVersion: string): $CancellablePromise<string> {
    return $Call.ByName("catdb/internal/services.UpdateService.GetChannel", currentVersion);
}

/**
 * GetLastCheckDate returns the timestamp (ISO 8601) of the last successful
 * update check, or "" if none.
 */
export function GetLastCheckDate(): $CancellablePromise<string> {
    return $Call.ByName("catdb/internal/services.UpdateService.GetLastCheckDate");
}

/**
 * GetSkippedVersion returns the version the user previously chose to skip,
 * or "" if none.
 */
export function GetSkippedVersion(): $CancellablePromise<string> {
    return $Call.ByName("catdb/internal/services.UpdateService.GetSkippedVersion");
}

/**
 * RestartAndInstall hands the staged asset from the last DownloadUpdate to
 * the OS-specific installer (silent — no installer UI) and then quits the
 * app so the swap can complete; the installer relaunches the app afterwards.
 */
export function RestartAndInstall(): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.UpdateService.RestartAndInstall");
}

/**
 * SetChannel persists the user's update channel choice.
 */
export function SetChannel(channel: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.UpdateService.SetChannel", channel);
}

/**
 * SetLastCheckDate persists the timestamp string after a successful check.
 */
export function SetLastCheckDate(date: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.UpdateService.SetLastCheckDate", date);
}

/**
 * SkipVersion persists version as the "ignore this release" marker.
 */
export function SkipVersion(version: string): $CancellablePromise<void> {
    return $Call.ByName("catdb/internal/services.UpdateService.SkipVersion", version);
}

// Private type creation functions
const $$createType0 = $models.UpdateCheckResult.createFrom;
