// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Capabilities lets the UI hide features the underlying database does not support.
 */
export class Capabilities {
    "schemas": boolean;
    "storedProcedures": boolean;
    "triggers": boolean;
    "views": boolean;
    "transactions": boolean;
    "explainPlan": boolean;

    /**
     * DatabaseEditor reports whether the driver's Metadata implements the
     * optional DatabaseEditor extension (CREATE/ALTER DATABASE). The UI hides
     * the 「新建/编辑数据库」 actions when false (e.g. SQLite, which has no such
     * statement — a database is a file).
     */
    "databaseEditor": boolean;

    /** Creates a new Capabilities instance. */
    constructor($$source: Partial<Capabilities> = {}) {
        if (!("schemas" in $$source)) {
            this["schemas"] = false;
        }
        if (!("storedProcedures" in $$source)) {
            this["storedProcedures"] = false;
        }
        if (!("triggers" in $$source)) {
            this["triggers"] = false;
        }
        if (!("views" in $$source)) {
            this["views"] = false;
        }
        if (!("transactions" in $$source)) {
            this["transactions"] = false;
        }
        if (!("explainPlan" in $$source)) {
            this["explainPlan"] = false;
        }
        if (!("databaseEditor" in $$source)) {
            this["databaseEditor"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Capabilities instance from a string or object.
     */
    static createFrom($$source: any = {}): Capabilities {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Capabilities($$parsedSource as Partial<Capabilities>);
    }
}

/**
 * ColumnMeta is the column descriptor returned by a ResultSet — sent to the
 * front-end once per query (NOT per row) to keep IPC payloads small.
 */
export class ColumnMeta {
    "name": string;

    /**
     * e.g. "VARCHAR", "BIGINT", "DATETIME(6)"
     */
    "nativeType": string;
    "logicalType": LogicalType;
    "nullable": boolean;
    "length"?: number;
    "precision"?: number;
    "scale"?: number;
    "default"?: string | null;
    "isPrimaryKey"?: boolean;
    "isAutoIncrement"?: boolean;
    "comment"?: string;

    /** Creates a new ColumnMeta instance. */
    constructor($$source: Partial<ColumnMeta> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("nativeType" in $$source)) {
            this["nativeType"] = "";
        }
        if (!("logicalType" in $$source)) {
            this["logicalType"] = LogicalType.$zero;
        }
        if (!("nullable" in $$source)) {
            this["nullable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnMeta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnMeta($$parsedSource as Partial<ColumnMeta>);
    }
}

/**
 * ConnParamField describes one field of a driver's connection form.
 * The front-end renders the form dynamically from this list; adding a new
 * database does not require a front-end change.
 */
export class ConnParamField {
    "key": string;
    "label": string;

    /**
     * text | number | password | select | bool
     */
    "type": string;
    "default"?: string;
    "required"?: boolean;
    "options"?: string[];

    /**
     * stable key, front-end localizes: "general" | "advanced" | "ssl" | "ssh"
     */
    "group"?: string;
    "help"?: string;

    /** Creates a new ConnParamField instance. */
    constructor($$source: Partial<ConnParamField> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnParamField instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnParamField {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField5_0($$parsedSource["options"]);
        }
        return new ConnParamField($$parsedSource as Partial<ConnParamField>);
    }
}

/**
 * DatabaseOptionField describes one field of the create/alter-database form.
 * Like ConnParamField, the front-end renders the form dynamically from this
 * list, so each driver exposes its own native concepts (MySQL:
 * charset/collation; Postgres: owner/template/encoding/lc_collate/lc_ctype/
 * tablespace) without front-end changes. Every field is a select; choices
 * are server-derived at DatabaseOptionFields time.
 */
export class DatabaseOptionField {
    /**
     * Key is the stable identifier used in the options map and for front-end
     * label localization (databaseEditor.field.*), with Label as fallback.
     */
    "key": string;

    /**
     * English baseline
     */
    "label": string;

    /**
     * Options are the selectable values. When DependsOn is set, use OptionsBy
     * keyed by the parent field's current value instead.
     */
    "options"?: string[];

    /**
     * DependsOn narrows the choices by another field's value (MySQL:
     * collation depends on charset). OptionsBy maps parent value → choices;
     * DefaultBy maps parent value → the value to snap to when the parent
     * changes and the current pick no longer belongs.
     */
    "dependsOn"?: string;
    "optionsBy"?: { [_ in string]?: string[] };
    "defaultBy"?: { [_ in string]?: string };

    /**
     * Default preselects the field in create mode. Empty = leave blank
     * (server/template default applies).
     */
    "default"?: string;

    /**
     * FixedOnAlter marks fields the database cannot change after creation
     * (Postgres: encoding/collation/template). The editor disables them in
     * edit mode and never passes them to AlterDatabaseSQL.
     */
    "fixedOnAlter"?: boolean;

    /** Creates a new DatabaseOptionField instance. */
    constructor($$source: Partial<DatabaseOptionField> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DatabaseOptionField instance from a string or object.
     */
    static createFrom($$source: any = {}): DatabaseOptionField {
        const $$createField2_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField2_0($$parsedSource["options"]);
        }
        if ("optionsBy" in $$parsedSource) {
            $$parsedSource["optionsBy"] = $$createField4_0($$parsedSource["optionsBy"]);
        }
        if ("defaultBy" in $$parsedSource) {
            $$parsedSource["defaultBy"] = $$createField5_0($$parsedSource["defaultBy"]);
        }
        return new DatabaseOptionField($$parsedSource as Partial<DatabaseOptionField>);
    }
}

/**
 * ExecResult is returned by non-SELECT statements.
 */
export class ExecResult {
    "rowsAffected": number;
    "lastInsertId": number;

    /** Creates a new ExecResult instance. */
    constructor($$source: Partial<ExecResult> = {}) {
        if (!("rowsAffected" in $$source)) {
            this["rowsAffected"] = 0;
        }
        if (!("lastInsertId" in $$source)) {
            this["lastInsertId"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ExecResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExecResult($$parsedSource as Partial<ExecResult>);
    }
}

/**
 * ForeignKeyInfo describes one FK constraint.
 */
export class ForeignKeyInfo {
    "name": string;
    "columns": string[];
    "referencedSchema"?: string;
    "referencedTable": string;
    "referencedColumns": string[];
    "onUpdate"?: string;
    "onDelete"?: string;

    /** Creates a new ForeignKeyInfo instance. */
    constructor($$source: Partial<ForeignKeyInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("referencedTable" in $$source)) {
            this["referencedTable"] = "";
        }
        if (!("referencedColumns" in $$source)) {
            this["referencedColumns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForeignKeyInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ForeignKeyInfo {
        const $$createField1_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField1_0($$parsedSource["columns"]);
        }
        if ("referencedColumns" in $$parsedSource) {
            $$parsedSource["referencedColumns"] = $$createField4_0($$parsedSource["referencedColumns"]);
        }
        return new ForeignKeyInfo($$parsedSource as Partial<ForeignKeyInfo>);
    }
}

/**
 * IndexColumn is one column entry inside an index, with its sort direction.
 */
export class IndexColumn {
    "name": string;

    /**
     * ASC | DESC | "" (HASH / unsortable)
     */
    "order"?: string;

    /** Creates a new IndexColumn instance. */
    constructor($$source: Partial<IndexColumn> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexColumn instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexColumn {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IndexColumn($$parsedSource as Partial<IndexColumn>);
    }
}

/**
 * IndexInfo describes one index on a table.
 */
export class IndexInfo {
    "name": string;
    "columns": IndexColumn[];
    "unique": boolean;
    "primary": boolean;

    /**
     * BTREE, HASH, FULLTEXT, ...
     */
    "type"?: string;

    /**
     * index comment
     */
    "comment"?: string;

    /** Creates a new IndexInfo instance. */
    constructor($$source: Partial<IndexInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("unique" in $$source)) {
            this["unique"] = false;
        }
        if (!("primary" in $$source)) {
            this["primary"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexInfo {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField1_0($$parsedSource["columns"]);
        }
        return new IndexInfo($$parsedSource as Partial<IndexInfo>);
    }
}

/**
 * LogicalType is the cross-database column type after Dialect.MapType normalization.
 */
export enum LogicalType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TypeUnknown = "unknown",
    TypeBool = "bool",
    TypeInt = "int",
    TypeBigInt = "bigint",
    TypeFloat = "float",
    TypeDecimal = "decimal",
    TypeString = "string",
    TypeText = "text",
    TypeBytes = "bytes",
    TypeJSON = "json",
    TypeDate = "date",
    TypeTime = "time",
    TypeDateTime = "datetime",
    TypeTimestamp = "timestamp",
    TypeUUID = "uuid",
    TypeEnum = "enum",
};

/**
 * RoutineInfo covers stored procedures, functions, and triggers.
 */
export class RoutineInfo {
    "name": string;
    "schema"?: string;

    /**
     * PROCEDURE | FUNCTION | TRIGGER
     */
    "type": string;
    "definition"?: string;
    "comment"?: string;

    /** Creates a new RoutineInfo instance. */
    constructor($$source: Partial<RoutineInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RoutineInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): RoutineInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RoutineInfo($$parsedSource as Partial<RoutineInfo>);
    }
}

/**
 * SSHConfig describes an SSH jump tunnel. Auth is mutually exclusive:
 * password OR private key OR ssh-agent.
 */
export class SSHConfig {
    "host": string;
    "port": number;
    "user": string;
    "password"?: string;
    "privateKey"?: string;
    "privateKeyPass"?: string;
    "useAgent"?: boolean;

    /**
     * for FixedHostKey verification
     */
    "knownHostsPath"?: string;

    /** Creates a new SSHConfig instance. */
    constructor($$source: Partial<SSHConfig> = {}) {
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHConfig($$parsedSource as Partial<SSHConfig>);
    }
}

/**
 * SSLConfig is the framework-agnostic SSL/TLS profile passed to drivers.
 */
export class SSLConfig {
    /**
     * disable | prefer | require | verify-ca | verify-full
     */
    "mode": string;
    "caCert"?: string;
    "clientCert"?: string;
    "clientKey"?: string;
    "serverName"?: string;

    /** Creates a new SSLConfig instance. */
    constructor($$source: Partial<SSLConfig> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSLConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): SSLConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSLConfig($$parsedSource as Partial<SSLConfig>);
    }
}

/**
 * ServerInfo holds runtime metadata about a database server — what you get
 * from `SELECT VERSION(), USER()` in MySQL. Populated on connect and cached
 * by the front-end store for the status bar.
 */
export class ServerInfo {
    /**
     * e.g. "8.0.32"
     */
    "version": string;

    /**
     * e.g. "root@localhost"
     */
    "user": string;

    /** Creates a new ServerInfo instance. */
    constructor($$source: Partial<ServerInfo> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerInfo($$parsedSource as Partial<ServerInfo>);
    }
}

/**
 * TableInfo is a row in the object tree at the table level.
 * 
 * Options carries driver-specific display attributes (MySQL: "engine",
 * "collation"). Generic layers must not interpret the keys; the driver's UI
 * dialect descriptor tells the front-end which ones to show.
 */
export class TableInfo {
    "name": string;
    "schema"?: string;
    "comment"?: string;
    "rows"?: number;
    "dataLength": number;
    "createTime": string;
    "updateTime": string;
    "options"?: { [_ in string]?: string };

    /** Creates a new TableInfo instance. */
    constructor($$source: Partial<TableInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("dataLength" in $$source)) {
            this["dataLength"] = 0;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = "";
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TableInfo {
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField7_0($$parsedSource["options"]);
        }
        return new TableInfo($$parsedSource as Partial<TableInfo>);
    }
}

/**
 * UIAutoIncrement describes auto-increment column rules for the editor.
 */
export class UIAutoIncrement {
    /**
     * Supported: the dialect has an auto-increment column flag at all.
     */
    "supported"?: boolean;

    /**
     * BaseTypes restricts the flag to these base types (empty = any).
     */
    "baseTypes"?: string[];

    /**
     * MaxPerTable caps flagged columns per table (0 = unlimited).
     */
    "maxPerTable"?: number;

    /** Creates a new UIAutoIncrement instance. */
    constructor($$source: Partial<UIAutoIncrement> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UIAutoIncrement instance from a string or object.
     */
    static createFrom($$source: any = {}): UIAutoIncrement {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("baseTypes" in $$parsedSource) {
            $$parsedSource["baseTypes"] = $$createField1_0($$parsedSource["baseTypes"]);
        }
        return new UIAutoIncrement($$parsedSource as Partial<UIAutoIncrement>);
    }
}

/**
 * UIDialect is the driver's declarative UI descriptor: everything the
 * front-end must know about this database's SQL surface that is not runtime
 * metadata — identifier quoting, editor dialect, the structure editor's type
 * system, completion catalogs. Shipped once per driver via
 * ConnectionService.ListDrivers, so adding a database never means editing
 * front-end components.
 * 
 * i18n rule: all Key fields are stable identifiers the front-end translates
 * (with the raw key as fallback); free-text fields (Info, Detail) are English
 * technical reference text shown as-is.
 */
export class UIDialect {
    /**
     * EditorDialect selects the CodeMirror SQL dialect by id:
     * "mysql" | "mariadb" | "postgresql" | "sqlite" | "mssql" | "plsql" |
     * "standard". Unknown ids fall back to "standard".
     */
    "editorDialect": string;

    /**
     * IdentQuote is the identifier quote character ("`", "\"", "[").
     */
    "identQuote": string;

    /**
     * StringBackslashEscapes: backslash escapes inside '…' string literals
     * (MySQL). Off for ANSI-conforming databases — a backslash is literal.
     */
    "stringBackslashEscapes"?: boolean;

    /**
     * SystemSchemas are catalog/system namespaces hidden from casual
     * completion until the user types a matching prefix.
     */
    "systemSchemas"?: string[];

    /**
     * DefaultSchema is the namespace new objects land in when the user gives
     * none (Postgres "public"). Empty for drivers without a schema level.
     */
    "defaultSchema"?: string;

    /**
     * NamespaceTerm names what ListDatabases returns — the object tree's
     * top-level container and the query tab's namespace dropdown. Stable key
     * the front-end localizes and picks node icons by: "database"
     * (MySQL/Postgres/SQLite) or "schema" (DM, where the schema level sits in
     * the database position). Empty means "database".
     */
    "namespaceTerm"?: string;

    /**
     * Keywords are dialect-specific keywords/phrases offered by completion in
     * addition to the front-end's generic ANSI set.
     */
    "keywords"?: string[];

    /**
     * Functions is the completion catalog of built-in functions.
     */
    "functions"?: UIFunction[];

    /**
     * Snippets are dialect-specific completion snippets. Body uses CodeMirror
     * snippet syntax (${placeholder}).
     */
    "snippets"?: UISnippet[];

    /**
     * TypeGroups is the grouped catalog of column base types for the
     * structure editor's type dropdown. The first type of the first group is
     * the default for newly-added columns.
     */
    "typeGroups"?: UITypeGroup[];

    /**
     * TypeFormats describes, per base type (uppercase), how its params field
     * behaves. Types absent from the map take {Kind:"none"}.
     */
    "typeFormats"?: { [_ in string]?: UITypeFormat };

    /**
     * DefaultColumnType/Params seed a newly-added column row
     * (MySQL: VARCHAR / 255).
     */
    "defaultColumnType"?: string;
    "defaultColumnParams"?: string;

    /**
     * HasUnsigned reports whether the dialect has an UNSIGNED column modifier
     * at all (drives the column-editor toggle column visibility).
     */
    "hasUnsigned"?: boolean;

    /**
     * AutoIncrement describes the dialect's auto-increment column rules.
     */
    "autoIncrement": UIAutoIncrement;

    /**
     * PrimaryKeyForcesNotNull: ticking PK forces NOT NULL in the editor.
     */
    "primaryKeyForcesNotNull"?: boolean;

    /**
     * IndexTypes are the selectable index methods (MySQL: BTREE/HASH/FULLTEXT;
     * Postgres: btree/hash/gin/gist). Empty hides the selector.
     */
    "indexTypes"?: string[];

    /**
     * DefaultCharset preselects the database editor's charset picker
     * (MySQL: utf8mb4). Empty leaves the picker blank.
     */
    "defaultCharset"?: string;

    /** Creates a new UIDialect instance. */
    constructor($$source: Partial<UIDialect> = {}) {
        if (!("editorDialect" in $$source)) {
            this["editorDialect"] = "";
        }
        if (!("identQuote" in $$source)) {
            this["identQuote"] = "";
        }
        if (!("autoIncrement" in $$source)) {
            this["autoIncrement"] = (new UIAutoIncrement());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UIDialect instance from a string or object.
     */
    static createFrom($$source: any = {}): UIDialect {
        const $$createField3_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType6;
        const $$createField8_0 = $$createType8;
        const $$createField9_0 = $$createType10;
        const $$createField10_0 = $$createType12;
        const $$createField14_0 = $$createType13;
        const $$createField16_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("systemSchemas" in $$parsedSource) {
            $$parsedSource["systemSchemas"] = $$createField3_0($$parsedSource["systemSchemas"]);
        }
        if ("keywords" in $$parsedSource) {
            $$parsedSource["keywords"] = $$createField6_0($$parsedSource["keywords"]);
        }
        if ("functions" in $$parsedSource) {
            $$parsedSource["functions"] = $$createField7_0($$parsedSource["functions"]);
        }
        if ("snippets" in $$parsedSource) {
            $$parsedSource["snippets"] = $$createField8_0($$parsedSource["snippets"]);
        }
        if ("typeGroups" in $$parsedSource) {
            $$parsedSource["typeGroups"] = $$createField9_0($$parsedSource["typeGroups"]);
        }
        if ("typeFormats" in $$parsedSource) {
            $$parsedSource["typeFormats"] = $$createField10_0($$parsedSource["typeFormats"]);
        }
        if ("autoIncrement" in $$parsedSource) {
            $$parsedSource["autoIncrement"] = $$createField14_0($$parsedSource["autoIncrement"]);
        }
        if ("indexTypes" in $$parsedSource) {
            $$parsedSource["indexTypes"] = $$createField16_0($$parsedSource["indexTypes"]);
        }
        return new UIDialect($$parsedSource as Partial<UIDialect>);
    }
}

/**
 * UIFunction is one completion catalog entry.
 */
export class UIFunction {
    "name": string;

    /**
     * Category is a stable key ("aggregate", "string", "numeric", "datetime",
     * "control", "json", "cast", "system") shown as the completion detail.
     */
    "category"?: string;

    /**
     * Info is an optional English one-liner (signature/summary).
     */
    "info"?: string;

    /**
     * Params are the snippet placeholders; "…" marks variadic tails and is
     * skipped on insert. Nil with NoArgs=false inserts "fn(${})".
     */
    "params"?: string[];

    /**
     * NoArgs functions insert as "fn()".
     */
    "noArgs"?: boolean;

    /** Creates a new UIFunction instance. */
    constructor($$source: Partial<UIFunction> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UIFunction instance from a string or object.
     */
    static createFrom($$source: any = {}): UIFunction {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField3_0($$parsedSource["params"]);
        }
        return new UIFunction($$parsedSource as Partial<UIFunction>);
    }
}

/**
 * UISnippet is one completion snippet.
 */
export class UISnippet {
    "label": string;
    "detail"?: string;
    "body": string;

    /** Creates a new UISnippet instance. */
    constructor($$source: Partial<UISnippet> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UISnippet instance from a string or object.
     */
    static createFrom($$source: any = {}): UISnippet {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UISnippet($$parsedSource as Partial<UISnippet>);
    }
}

/**
 * UITypeFormat describes the params field behavior for one base type.
 */
export class UITypeFormat {
    /**
     * Kind is one of "length", "displayWidth", "precisionScale",
     * "fractionalSeconds", "enumValues", "none".
     */
    "kind": string;

    /**
     * SupportsUnsigned enables the UNSIGNED toggle for this type.
     */
    "supportsUnsigned"?: boolean;

    /**
     * ParamsRequired marks the params field mandatory (e.g. VARCHAR length).
     */
    "paramsRequired"?: boolean;

    /** Creates a new UITypeFormat instance. */
    constructor($$source: Partial<UITypeFormat> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UITypeFormat instance from a string or object.
     */
    static createFrom($$source: any = {}): UITypeFormat {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UITypeFormat($$parsedSource as Partial<UITypeFormat>);
    }
}

/**
 * UITypeGroup is one group in the structure editor's type dropdown. Key is a
 * stable identifier ("string", "integer", "decimal", "datetime", "binary",
 * "boolean", "other") the front-end localizes.
 */
export class UITypeGroup {
    "key": string;
    "types": string[];

    /** Creates a new UITypeGroup instance. */
    constructor($$source: Partial<UITypeGroup> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("types" in $$source)) {
            this["types"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UITypeGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): UITypeGroup {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("types" in $$parsedSource) {
            $$parsedSource["types"] = $$createField1_0($$parsedSource["types"]);
        }
        return new UITypeGroup($$parsedSource as Partial<UITypeGroup>);
    }
}

/**
 * ViewInfo is a view in the object tree.
 */
export class ViewInfo {
    "name": string;
    "schema"?: string;
    "comment"?: string;

    /** Creates a new ViewInfo instance. */
    constructor($$source: Partial<ViewInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ViewInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ViewInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ViewInfo($$parsedSource as Partial<ViewInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = IndexColumn.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = UIFunction.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = UISnippet.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = UITypeGroup.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = UITypeFormat.createFrom;
const $$createType12 = $Create.Map($Create.Any, $$createType11);
const $$createType13 = UIAutoIncrement.createFrom;
