// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Capabilities lets the UI hide features the underlying database does not support.
 */
export class Capabilities {
    "schemas": boolean;
    "storedProcedures": boolean;
    "triggers": boolean;
    "views": boolean;
    "transactions": boolean;
    "explainPlan": boolean;

    /** Creates a new Capabilities instance. */
    constructor($$source: Partial<Capabilities> = {}) {
        if (!("schemas" in $$source)) {
            this["schemas"] = false;
        }
        if (!("storedProcedures" in $$source)) {
            this["storedProcedures"] = false;
        }
        if (!("triggers" in $$source)) {
            this["triggers"] = false;
        }
        if (!("views" in $$source)) {
            this["views"] = false;
        }
        if (!("transactions" in $$source)) {
            this["transactions"] = false;
        }
        if (!("explainPlan" in $$source)) {
            this["explainPlan"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Capabilities instance from a string or object.
     */
    static createFrom($$source: any = {}): Capabilities {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Capabilities($$parsedSource as Partial<Capabilities>);
    }
}

/**
 * ColumnMeta is the column descriptor returned by a ResultSet — sent to the
 * front-end once per query (NOT per row) to keep IPC payloads small.
 */
export class ColumnMeta {
    "name": string;

    /**
     * e.g. "VARCHAR", "BIGINT", "DATETIME(6)"
     */
    "nativeType": string;
    "logicalType": LogicalType;
    "nullable": boolean;
    "length"?: number;
    "precision"?: number;
    "scale"?: number;
    "default"?: string | null;
    "isPrimaryKey"?: boolean;
    "isAutoIncrement"?: boolean;
    "comment"?: string;

    /** Creates a new ColumnMeta instance. */
    constructor($$source: Partial<ColumnMeta> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("nativeType" in $$source)) {
            this["nativeType"] = "";
        }
        if (!("logicalType" in $$source)) {
            this["logicalType"] = LogicalType.$zero;
        }
        if (!("nullable" in $$source)) {
            this["nullable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnMeta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnMeta($$parsedSource as Partial<ColumnMeta>);
    }
}

/**
 * ConnParamField describes one field of a driver's connection form.
 * The front-end renders the form dynamically from this list; adding a new
 * database does not require a front-end change.
 */
export class ConnParamField {
    "key": string;
    "label": string;

    /**
     * text | number | password | select | bool
     */
    "type": string;
    "default"?: string;
    "required"?: boolean;
    "options"?: string[];

    /**
     * "常规" | "SSL" | "SSH"
     */
    "group"?: string;
    "help"?: string;

    /** Creates a new ConnParamField instance. */
    constructor($$source: Partial<ConnParamField> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnParamField instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnParamField {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField5_0($$parsedSource["options"]);
        }
        return new ConnParamField($$parsedSource as Partial<ConnParamField>);
    }
}

/**
 * ExecResult is returned by non-SELECT statements.
 */
export class ExecResult {
    "rowsAffected": number;
    "lastInsertId": number;

    /** Creates a new ExecResult instance. */
    constructor($$source: Partial<ExecResult> = {}) {
        if (!("rowsAffected" in $$source)) {
            this["rowsAffected"] = 0;
        }
        if (!("lastInsertId" in $$source)) {
            this["lastInsertId"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ExecResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExecResult($$parsedSource as Partial<ExecResult>);
    }
}

/**
 * ForeignKeyInfo describes one FK constraint.
 */
export class ForeignKeyInfo {
    "name": string;
    "columns": string[];
    "referencedSchema"?: string;
    "referencedTable": string;
    "referencedColumns": string[];
    "onUpdate"?: string;
    "onDelete"?: string;

    /** Creates a new ForeignKeyInfo instance. */
    constructor($$source: Partial<ForeignKeyInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("referencedTable" in $$source)) {
            this["referencedTable"] = "";
        }
        if (!("referencedColumns" in $$source)) {
            this["referencedColumns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForeignKeyInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ForeignKeyInfo {
        const $$createField1_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField1_0($$parsedSource["columns"]);
        }
        if ("referencedColumns" in $$parsedSource) {
            $$parsedSource["referencedColumns"] = $$createField4_0($$parsedSource["referencedColumns"]);
        }
        return new ForeignKeyInfo($$parsedSource as Partial<ForeignKeyInfo>);
    }
}

/**
 * IndexInfo describes one index on a table.
 */
export class IndexInfo {
    "name": string;
    "columns": string[];
    "unique": boolean;
    "primary": boolean;

    /**
     * BTREE, HASH, FULLTEXT, ...
     */
    "type"?: string;

    /** Creates a new IndexInfo instance. */
    constructor($$source: Partial<IndexInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("unique" in $$source)) {
            this["unique"] = false;
        }
        if (!("primary" in $$source)) {
            this["primary"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexInfo {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField1_0($$parsedSource["columns"]);
        }
        return new IndexInfo($$parsedSource as Partial<IndexInfo>);
    }
}

/**
 * LogicalType is the cross-database column type after Dialect.MapType normalization.
 */
export enum LogicalType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TypeUnknown = "unknown",
    TypeBool = "bool",
    TypeInt = "int",
    TypeBigInt = "bigint",
    TypeFloat = "float",
    TypeDecimal = "decimal",
    TypeString = "string",
    TypeText = "text",
    TypeBytes = "bytes",
    TypeJSON = "json",
    TypeDate = "date",
    TypeTime = "time",
    TypeDateTime = "datetime",
    TypeTimestamp = "timestamp",
    TypeUUID = "uuid",
    TypeEnum = "enum",
};

/**
 * RoutineInfo covers stored procedures, functions, and triggers.
 */
export class RoutineInfo {
    "name": string;
    "schema"?: string;

    /**
     * PROCEDURE | FUNCTION | TRIGGER
     */
    "type": string;
    "definition"?: string;
    "comment"?: string;

    /** Creates a new RoutineInfo instance. */
    constructor($$source: Partial<RoutineInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RoutineInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): RoutineInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RoutineInfo($$parsedSource as Partial<RoutineInfo>);
    }
}

/**
 * SSHConfig describes an SSH jump tunnel. Auth is mutually exclusive:
 * password OR private key OR ssh-agent.
 */
export class SSHConfig {
    "host": string;
    "port": number;
    "user": string;
    "password"?: string;
    "privateKey"?: string;
    "privateKeyPass"?: string;
    "useAgent"?: boolean;

    /**
     * for FixedHostKey verification
     */
    "knownHostsPath"?: string;

    /** Creates a new SSHConfig instance. */
    constructor($$source: Partial<SSHConfig> = {}) {
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHConfig($$parsedSource as Partial<SSHConfig>);
    }
}

/**
 * SSLConfig is the framework-agnostic SSL/TLS profile passed to drivers.
 */
export class SSLConfig {
    /**
     * disable | prefer | require | verify-ca | verify-full
     */
    "mode": string;
    "caCert"?: string;
    "clientCert"?: string;
    "clientKey"?: string;
    "serverName"?: string;

    /** Creates a new SSLConfig instance. */
    constructor($$source: Partial<SSLConfig> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSLConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): SSLConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSLConfig($$parsedSource as Partial<SSLConfig>);
    }
}

/**
 * ServerInfo holds runtime metadata about a database server — what you get
 * from `SELECT VERSION(), USER()` in MySQL. Populated on connect and cached
 * by the front-end store for the status bar.
 */
export class ServerInfo {
    /**
     * e.g. "8.0.32"
     */
    "version": string;

    /**
     * e.g. "root@localhost"
     */
    "user": string;

    /** Creates a new ServerInfo instance. */
    constructor($$source: Partial<ServerInfo> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerInfo($$parsedSource as Partial<ServerInfo>);
    }
}

/**
 * TableInfo is a row in the object tree at the table level.
 */
export class TableInfo {
    "name": string;
    "schema"?: string;
    "engine"?: string;
    "comment"?: string;
    "rows"?: number;

    /** Creates a new TableInfo instance. */
    constructor($$source: Partial<TableInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TableInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TableInfo($$parsedSource as Partial<TableInfo>);
    }
}

/**
 * ViewInfo is a view in the object tree.
 */
export class ViewInfo {
    "name": string;
    "schema"?: string;
    "comment"?: string;

    /** Creates a new ViewInfo instance. */
    constructor($$source: Partial<ViewInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ViewInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ViewInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ViewInfo($$parsedSource as Partial<ViewInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
