// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ModelInfo 描述一个模型。ContextWindow 供上下文水位计算，SupportsTools 决定
 * 是否降级为纯文本补全——二者对 openai-compat 下的自定义模型无法探测，由配置提供。
 */
export class ModelInfo {
    "ID": string;
    "ContextWindow": number;
    "SupportsTools": boolean;

    /** Creates a new ModelInfo instance. */
    constructor($$source: Partial<ModelInfo> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("ContextWindow" in $$source)) {
            this["ContextWindow"] = 0;
        }
        if (!("SupportsTools" in $$source)) {
            this["SupportsTools"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelInfo($$parsedSource as Partial<ModelInfo>);
    }
}
